/**
 * Centralized product / affiliate-link data for the Baby Checklist.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 *  HOW TO ADD OR UPDATE AN AFFILIATE LINK (for Taylor)
 * ─────────────────────────────────────────────────────────────────────────────
 *  1. Find the product below by its `id`.
 *  2. Paste the real affiliate URL into `affiliateUrl` (replace
 *     `AFFILIATE_LINK_NEEDED`). Optionally add a `secondaryUrl` (e.g. a second
 *     retailer) and set `retailer` / `secondaryRetailer`.
 *  3. Save. The link updates everywhere that product is recommended — you never
 *     edit the checklist UI or paste a URL twice.
 *
 *  While `affiliateUrl` is still `AFFILIATE_LINK_NEEDED`, the editorial
 *  recommendation still shows, but NO shopping button renders (so there are
 *  never dead or placeholder links in front of a parent).
 * ─────────────────────────────────────────────────────────────────────────────
 */

/** Sentinel — a recommendation with this URL renders its editorial copy but no CTA. */
export const AFFILIATE_LINK_NEEDED = 'AFFILIATE_LINK_NEEDED' as const;

// Babylist shopping links use ShopMy, including legacy Impact destinations.
import { babylistShopMyUrl } from '@/lib/affiliateShopMy';
export const babylist = babylistShopMyUrl;

export type { RetailerLink } from '@/lib/retailerLinks';
import type { RetailerLink } from '@/lib/retailerLinks';

export type ChecklistProduct = {
  id: string;
  brand: string;
  product: string;
  /** 1–2 sentence editorial recommendation, in Taylor's advisor voice. */
  review: string;
  bestFor: string;
  standout: string;
  affiliateUrl: string;
  /** Optional exact Amazon affiliate link. When absent, an Amazon-allowed brand
   *  still gets a "Shop Amazon" button via a tagged Amazon search fallback. */
  amazonUrl?: string;
  /** Optional price. Shown as $X / $X.XX when set (paste from your Babylist data). */
  price?: number;
  priceSource?: string;
  secondaryUrl?: string;
  retailer?: string;
  secondaryRetailer?: string;
  /** Extra retailers beyond Babylist / Amazon / secondary, in display order.
   *  Admin saves accept at most 5 links in total; existing links are preserved. */
  retailerLinks?: RetailerLink[];
  imageUrl?: string;
  badge?: string;
  /** false = no affiliate relationship on this pick (kept for future use). */
  disclosure?: boolean;
  /** Checklist line this pick displays under (a ChecklistItem id). Admin-set;
   *  overrides the static recommendationId wiring in data.ts when present. */
  checklistItemId?: string;
  /** Relative order among picks assigned to the same checklist line. */
  sortOrder?: number;
};

/**
 * Keyed by product id. Checklist items reference these by `recommendationId`
 * rather than duplicating the object — one source of truth per pick.
 */
export const products: Record<string, ChecklistProduct> = {
  'britax-galaxy360': {
    id: 'britax-galaxy360',
    brand: 'Britax',
    product: 'Galaxy360',
    review:
      'A convertible seat that spins to load, so you are not folding yourself into the back seat every day. It carries a child from birth through the years you actually keep a convertible.',
    bestFor: 'Parents who want one seat that lasts and a genuinely easier daily buckle.',
    standout: '360° rotation and a wide, forgiving install.',
    affiliateUrl: AFFILIATE_LINK_NEEDED,
    retailer: 'Babylist',
    badge: "Taylor's Pick",
    disclosure: true,
  },
  'infant-car-seat-pick': {
    id: 'infant-car-seat-pick',
    brand: 'Nuna',
    product: 'PIPA RX',
    review:
      'A light infant seat that clicks in and out of the base and most stroller frames with an adapter. The weight matters more than any spec once you are the one carrying it.',
    bestFor: 'Parents who want a true click-and-go travel system in the first months.',
    standout: 'Low carry weight and a simple, confident install.',
    // Wired from your Babylist catalogue (confirmed deep link).
    affiliateUrl: babylist('https://www.babylist.com/gp/nuna-pipa-rx/16140/310275'),
    retailer: 'Babylist',
    badge: "Taylor's Pick",
    disclosure: true,
  },
  'primary-stroller-pick': {
    id: 'primary-stroller-pick',
    brand: 'UPPAbaby',
    product: 'Vista V2',
    review:
      'The stroller most families keep for years. It takes a bassinet, a toddler seat, and — with the right piece — a second child, so it grows instead of getting replaced.',
    bestFor: 'One-car, city, or suburban families who want a single frame to grow into.',
    standout: 'Expandable to two seats without buying a new stroller.',
    // Wired from your Babylist catalogue (UPPAbaby strollers — refine to the exact Vista deep link when handy).
    affiliateUrl: babylist('https://www.babylist.com/store/strollers?brand=uppababy'),
    retailer: 'Babylist',
    badge: "Taylor's Pick",
    disclosure: true,
  },
  'travel-stroller-pick': {
    id: 'travel-stroller-pick',
    brand: 'Babyzen',
    product: 'YOYO2',
    review:
      'Folds small enough for an overhead bin and opens one-handed. A second, lighter stroller earns its keep the first time you travel or tackle a tight trunk.',
    bestFor: 'Travel, transit, and quick errands once baby has head control.',
    standout: 'Carry-on fold in a genuinely usable everyday stroller.',
    affiliateUrl: AFFILIATE_LINK_NEEDED,
    retailer: 'Babylist',
    badge: 'Travel Favorite',
    disclosure: true,
  },
  'double-stroller-pick': {
    id: 'double-stroller-pick',
    brand: 'UPPAbaby',
    product: 'Vista V2 (with RumbleSeat)',
    review:
      'For twins, one frame that takes two bassinets or two seats keeps your footprint sane. Choose the double configuration around how you actually move through doorways and sidewalks.',
    bestFor: 'Twin families who want one frame instead of two separate strollers.',
    standout: 'True two-seat flexibility from a single chassis.',
    // Wired from your Babylist catalogue (UPPAbaby strollers).
    affiliateUrl: babylist('https://www.babylist.com/store/strollers?brand=uppababy'),
    retailer: 'Babylist',
    badge: "Taylor's Pick",
    disclosure: true,
  },
  'baby-carrier-pick': {
    id: 'baby-carrier-pick',
    brand: 'Ergobaby',
    product: 'Omni 360',
    review:
      'An adjustable carrier that works from newborn without an insert and adapts across caregivers of different sizes. Comfort for the wearer is what keeps a carrier in use.',
    bestFor: 'Hands-free days, contact naps, and sharing between two adults.',
    standout: 'Newborn-ready with a supportive, shareable fit.',
    affiliateUrl: AFFILIATE_LINK_NEEDED,
    retailer: 'Babylist',
    badge: "Taylor's Pick",
    disclosure: true,
  },
  'monitor-pick': {
    id: 'monitor-pick',
    brand: 'Nanit',
    product: 'Pro Camera',
    review:
      'A clear overhead view and reliable app. For one baby it is plenty; for twins, choose a system that supports two cameras on one account rather than two separate apps.',
    bestFor: 'Parents who want a dependable video view without a wall of gadgets.',
    standout: 'Two-camera capability on a single system.',
    affiliateUrl: AFFILIATE_LINK_NEEDED,
    retailer: 'Babylist',
    badge: "Taylor's Pick",
    disclosure: true,
  },
  'audio-monitor-pick': {
    id: 'audio-monitor-pick',
    brand: 'VTech',
    product: 'Audio Monitor',
    review:
      'Sometimes you just want sound, long battery, and nothing to charge or log into. A simple audio monitor is an honest, low-stress backup or primary.',
    bestFor: 'Small homes, light sleepers, and anyone who wants less screen.',
    standout: 'Reliable, distraction-free, inexpensive.',
    affiliateUrl: AFFILIATE_LINK_NEEDED,
    retailer: 'Babylist',
  },
  'bathtub-pick': {
    id: 'bathtub-pick',
    brand: 'Puj / Angelcare',
    product: 'Infant Tub',
    review:
      'A tub that supports a newborn and drains easily beats anything elaborate. For twins, one tub is fine — you are bathing one baby at a time regardless.',
    bestFor: 'First baths through the sitting-up stage.',
    standout: 'Simple support, easy to clean and store.',
    affiliateUrl: AFFILIATE_LINK_NEEDED,
    retailer: 'Babylist',
    badge: "Taylor's Pick",
    disclosure: true,
  },
  'high-chair-pick': {
    id: 'high-chair-pick',
    brand: 'Stokke',
    product: 'Tripp Trapp',
    review:
      'A chair that adjusts to the table and grows with the child, so it does not get outgrown in a year. You will not need it until around six months — register early, buy later.',
    bestFor: 'Families who want one chair for the long haul.',
    standout: 'Adjusts from baby to big-kid seating.',
    affiliateUrl: AFFILIATE_LINK_NEEDED,
    retailer: 'Babylist',
    badge: "Taylor's Pick",
    disclosure: true,
  },
  'bottle-trial-pick': {
    id: 'bottle-trial-pick',
    brand: 'Mixed',
    product: 'Bottle Trial Pack',
    review:
      'Babies are opinionated about bottles. Start with a small variety pack and let your baby tell you the winner before you commit to eight of anything.',
    bestFor: 'Every feeding plan — breast, bottle, or both.',
    standout: 'Cheap insurance against a full set your baby rejects.',
    affiliateUrl: AFFILIATE_LINK_NEEDED,
    retailer: 'Babylist',
    badge: 'Try First',
  },
  'breast-pump-pick': {
    id: 'breast-pump-pick',
    brand: 'Spectra',
    product: 'S1 Plus',
    review:
      'A workhorse pump that many parents can get through insurance — check that first. Comfort and reliable suction beat novelty every time.',
    bestFor: 'Anyone planning to pump regularly.',
    standout: 'Hospital-strength performance; often insurance-covered.',
    affiliateUrl: AFFILIATE_LINK_NEEDED,
    retailer: 'Babylist',
  },
  'diaper-pail-pick': {
    id: 'diaper-pail-pick',
    brand: 'Ubbi',
    product: 'Steel Diaper Pail',
    review:
      'Steel seals odor better than plastic and takes regular trash bags, so you are not locked into a refill subscription. One good pail serves twins fine.',
    bestFor: 'Nurseries where smell control actually matters.',
    standout: 'No proprietary refills; genuinely contains odor.',
    affiliateUrl: AFFILIATE_LINK_NEEDED,
    retailer: 'Babylist',
    badge: "Taylor's Pick",
    disclosure: true,
  },
  'playard-pick': {
    id: 'playard-pick',
    brand: 'Guava / BabyBjörn',
    product: 'Travel Crib',
    review:
      'A light travel crib doubles as a safe sleep space at grandma’s and a contained spot at home. Look for a one-piece setup you will actually use.',
    bestFor: 'Travel, visits, and a second safe sleep space.',
    standout: 'Fast setup, packs down small.',
    affiliateUrl: AFFILIATE_LINK_NEEDED,
    retailer: 'Babylist',
    badge: 'Space Saver',
  },
  'davinci-dylan-mini-crib': {
    id: 'davinci-dylan-mini-crib',
    brand: 'DaVinci',
    product: 'Dylan Folding Portable 3-in-1 Mini Crib',
    review:
      'A folding mini crib that tucks away when you need the floor space back and converts to a twin bed down the road. A smart pick for small rooms, guest rooms, or grandparents.',
    bestFor: 'Small spaces and anyone who wants a crib that folds flat and grows up.',
    standout: 'Folds flat, rolls away, and converts to a toddler/twin bed.',
    affiliateUrl:
      babylist('https://www.babylist.com/gp/davinci-dylan-folding-portable-3-in-1-mini-crib/32116/1322545'),
    retailer: 'Babylist',
    badge: "Taylor's Pick",
    disclosure: true,
  },
  'stokke-sleepi-crib': {
    id: 'stokke-sleepi-crib',
    brand: 'Stokke',
    product: 'Sleepi 3-in-1 Convertible Crib (with mattresses + extension kit)',
    review:
      'An oval convertible crib that starts small and expands as your baby grows — the mattresses and extension kit are included here, so it lasts from newborn through the toddler years.',
    bestFor: 'Families who want one beautiful crib that grows from newborn to toddler.',
    standout: 'Oval-to-bed system with the extension kit included.',
    affiliateUrl:
      babylist('https://www.babylist.com/gp/stokke-sleepi3-in-1-convertible-crib-with-mattresses-and-extension-kit/77231/2666164'),
    retailer: 'Babylist',
    badge: "Taylor's Pick",
    disclosure: true,
  },
  'nuna-demi-icon': {
    id: 'nuna-demi-icon',
    brand: 'Nuna',
    product: 'DEMI Icon',
    review:
      'A premium full-size stroller that takes a bassinet, toddler seat, and infant seat — a true grow-with-you frame with a smooth ride and a compact one-piece fold.',
    bestFor: 'Parents who want one high-end frame that adapts from newborn onward.',
    standout: 'Modular from day one, with a refined, sturdy ride.',
    affiliateUrl:
      babylist('https://www.babylist.com/gp/nuna-demi-icon/81555/3142525'),
    imageUrl:
      'https://www.macrobaby.com/cdn/shop/files/nuna-demi-icon-stroller-caviar_image_1_1000x.jpg?v=1774841535',
    retailer: 'Babylist',
    badge: "Taylor's Pick",
    disclosure: true,
  },

  // ───────────────────────────────────────────────────────────────────────────
  // Amazon Creator Connections picks.
  //
  // Each binds to a checklist line via `checklistItemId` rather than editing
  // data.ts, so no existing item or pick is touched. `review` is a deliberate
  // placeholder: these came from a product feed with no editorial copy, and
  // inventing specs or safety claims for baby gear is not acceptable — Taylor
  // writes the real line per pick.
  // ───────────────────────────────────────────────────────────────────────────
  'amzcc-angelbliss-waterproof-crib-mattress-protector-2-pack-52-x-28': {
    id: 'amzcc-angelbliss-waterproof-crib-mattress-protector-2-pack-52-x-28',
    brand: 'ANGELBLISS',
    product: 'Waterproof Crib Mattress Protector 2-Pack (52" x 28")',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0GYNWBMHM?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0GYNWBMHM?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41XlRpQr4CL.jpg',
    checklistItemId: 'mattress-protector',
    disclosure: true,
  },
  'amzcc-evolur-cove-5-in-1-convertible-wooden-crib': {
    id: 'amzcc-evolur-cove-5-in-1-convertible-wooden-crib',
    brand: 'Evolur',
    product: 'Cove 5-in-1 Convertible Wooden Crib',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0H26Q8CDB?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0H26Q8CDB?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41dm2AdR3qL.jpg',
    checklistItemId: 'crib',
    disclosure: true,
  },
  'amzcc-fisher-price-dream-on-me-meadowbrook-4-in-1-convertible-crib': {
    id: 'amzcc-fisher-price-dream-on-me-meadowbrook-4-in-1-convertible-crib',
    brand: 'Fisher-Price (Dream On Me)',
    product: 'Meadowbrook 4-in-1 Convertible Crib',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0GXKZ25PZ?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0GXKZ25PZ?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41w71+BOQvL.jpg',
    checklistItemId: 'crib',
    disclosure: true,
  },
  'amzcc-dream-on-me-synergy-flex-foldable-full-size-crib': {
    id: 'amzcc-dream-on-me-synergy-flex-foldable-full-size-crib',
    brand: 'Dream On Me',
    product: 'Synergy Flex Foldable Full-Size Crib',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B08J911ZDS?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B08J911ZDS?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41-HokwRH+L.jpg',
    checklistItemId: 'crib',
    disclosure: true,
  },
  'amzcc-evolur-cozy-dreamer-travel-bassinet': {
    id: 'amzcc-evolur-cozy-dreamer-travel-bassinet',
    brand: 'Evolur',
    product: 'Cozy Dreamer Travel Bassinet',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0DTHYS8SG?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0DTHYS8SG?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41YjU9NIGQL.jpg',
    checklistItemId: 'bassinet-if-using',
    disclosure: true,
  },
  'amzcc-gaive-bassinet-pack-and-play-bedside-sleeper': {
    id: 'amzcc-gaive-bassinet-pack-and-play-bedside-sleeper',
    brand: 'GAIVE',
    product: 'Bassinet / Pack and Play Bedside Sleeper',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0FX3MPLGR?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0FX3MPLGR?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/51xVh8k9HEL.jpg',
    checklistItemId: 'bassinet-if-using',
    disclosure: true,
  },
  'amzcc-pamo-babe-5-in-1-pack-and-play-bedside-crib': {
    id: 'amzcc-pamo-babe-5-in-1-pack-and-play-bedside-crib',
    brand: 'Pamo Babe',
    product: '5-in-1 Pack and Play Bedside Crib',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0H45KD6MX?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0H45KD6MX?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41Ozmnejw1L.jpg',
    checklistItemId: 'travel-crib',
    disclosure: true,
  },
  'amzcc-momcozy-muslin-crib-sheets-2-pack-52-x-28': {
    id: 'amzcc-momcozy-muslin-crib-sheets-2-pack-52-x-28',
    brand: 'Momcozy',
    product: 'Muslin Crib Sheets 2-Pack (52" x 28")',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0DRD5Q7RG?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0DRD5Q7RG?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41+Nzc0anNL.jpg',
    checklistItemId: 'crib-sheets',
    disclosure: true,
  },
  'amzcc-momcozy-muslin-mini-crib-pack-and-play-sheets-2-pack': {
    id: 'amzcc-momcozy-muslin-mini-crib-pack-and-play-sheets-2-pack',
    brand: 'Momcozy',
    product: 'Muslin Mini Crib / Pack and Play Sheets 2-Pack',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0DRD4CLS7?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0DRD4CLS7?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/4185IPFgvgL.jpg',
    checklistItemId: 'crib-sheets',
    disclosure: true,
  },
  'amzcc-momcozy-sleep-sack-1-5-tog': {
    id: 'amzcc-momcozy-sleep-sack-1-5-tog',
    brand: 'Momcozy',
    product: 'Sleep Sack 1.5 TOG',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0G43W94RN?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0G43W94RN?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/31BECxtb-1L.jpg',
    checklistItemId: 'sleep-sacks',
    disclosure: true,
  },
  'amzcc-momcozy-quiet-fastener-swaddle-0-3m': {
    id: 'amzcc-momcozy-quiet-fastener-swaddle-0-3m',
    brand: 'Momcozy',
    product: 'Quiet Fastener Swaddle 0-3M',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0FYQ5HFBB?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0FYQ5HFBB?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41Sh09Ta1lL.jpg',
    checklistItemId: 'swaddles',
    disclosure: true,
  },
  'amzcc-momcozy-muslin-swaddle-blankets-4-pack': {
    id: 'amzcc-momcozy-muslin-swaddle-blankets-4-pack',
    brand: 'Momcozy',
    product: 'Muslin Swaddle Blankets 4-Pack',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B098NY9KW8?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B098NY9KW8?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41k5gWkxQgL.jpg',
    checklistItemId: 'swaddles',
    disclosure: true,
  },
  'amzcc-momcozy-video-baby-monitor-5-1080p': {
    id: 'amzcc-momcozy-video-baby-monitor-5-1080p',
    brand: 'Momcozy',
    product: 'Video Baby Monitor 5" 1080P',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0BG83KWQT?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0BG83KWQT?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/314-uyPa00L.jpg',
    checklistItemId: 'monitor',
    disclosure: true,
  },
  'amzcc-dreamegg-portable-white-noise-machine': {
    id: 'amzcc-dreamegg-portable-white-noise-machine',
    brand: 'Dreamegg',
    product: 'Portable White Noise Machine',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0D1K5JMDH?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0D1K5JMDH?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/31SIO7upAkL.jpg',
    checklistItemId: 'portable-sound-machine',
    disclosure: true,
  },
  'amzcc-baby-shusher-firefly-soother-with-nightlight': {
    id: 'amzcc-baby-shusher-firefly-soother-with-nightlight',
    brand: 'Baby Shusher',
    product: 'Firefly Soother with Nightlight',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0CZGN89H9?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0CZGN89H9?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/310-3m96YlL.jpg',
    checklistItemId: 'night-light',
    disclosure: true,
  },
  'amzcc-baby-shusher-shusher-sloth': {
    id: 'amzcc-baby-shusher-shusher-sloth',
    brand: 'Baby Shusher',
    product: 'Shusher Sloth',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0D61H7GPR?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0D61H7GPR?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/417733Fg2sL.jpg',
    checklistItemId: 'sound-machine',
    disclosure: true,
  },
  'amzcc-hiccapop-blackout-tent-for-pack-and-play': {
    id: 'amzcc-hiccapop-blackout-tent-for-pack-and-play',
    brand: 'Hiccapop',
    product: 'Blackout Tent for Pack and Play',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0B488NXCZ?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0B488NXCZ?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/51Equ2bVfBL.jpg',
    checklistItemId: 'blackout',
    disclosure: true,
  },
  'amzcc-evolur-aurora-7-drawer-double-dresser': {
    id: 'amzcc-evolur-aurora-7-drawer-double-dresser',
    brand: 'Evolur',
    product: 'Aurora 7-Drawer Double Dresser',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B01CYAMDBW?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B01CYAMDBW?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/31e4Sv1ab4L.jpg',
    checklistItemId: 'nursery-landing-zone',
    disclosure: true,
  },
  'amzcc-evolur-raleigh-plus-glider-recliner': {
    id: 'amzcc-evolur-raleigh-plus-glider-recliner',
    brand: 'Evolur',
    product: 'Raleigh Plus Glider Recliner',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0H6KMXNKP?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0H6KMXNKP?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/31ivHsyKr6L.jpg',
    checklistItemId: 'nursery-landing-zone',
    disclosure: true,
  },
  'amzcc-dream-on-me-synergy-glider-recliner': {
    id: 'amzcc-dream-on-me-synergy-glider-recliner',
    brand: 'Dream On Me',
    product: 'Synergy Glider Recliner',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0H71SRJ21?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0H71SRJ21?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41PLsHc-ufL.jpg',
    checklistItemId: 'nursery-landing-zone',
    disclosure: true,
  },
  'amzcc-dream-on-me-chatham-rocking-glider': {
    id: 'amzcc-dream-on-me-chatham-rocking-glider',
    brand: 'Dream On Me',
    product: 'Chatham Rocking Glider',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0DH8GFTVP?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0DH8GFTVP?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/318MxCEYMCL.jpg',
    checklistItemId: 'nursery-landing-zone',
    disclosure: true,
  },
  'amzcc-tommee-tippee-natural-start-perfect-latch-trial-kit': {
    id: 'amzcc-tommee-tippee-natural-start-perfect-latch-trial-kit',
    brand: 'Tommee Tippee',
    product: 'Natural Start Perfect Latch Trial Kit',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0H8VDN743?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0H8VDN743?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/31a1Tk84M6L.jpg',
    checklistItemId: 'bottle-trial',
    disclosure: true,
  },
  'amzcc-tommee-tippee-silicone-coated-glass-bottles-5oz-2-pack': {
    id: 'amzcc-tommee-tippee-silicone-coated-glass-bottles-5oz-2-pack',
    brand: 'Tommee Tippee',
    product: 'Silicone-Coated Glass Bottles 5oz 2-Pack',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0GF3JGCGP?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0GF3JGCGP?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/31FrnhOYhkL.jpg',
    checklistItemId: 'additional-bottles',
    disclosure: true,
  },
  'amzcc-momcozy-m5-wearable-breast-pump': {
    id: 'amzcc-momcozy-m5-wearable-breast-pump',
    brand: 'Momcozy',
    product: 'M5 Wearable Breast Pump',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0G647K9TN?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0G647K9TN?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41qH3Ff72gL.jpg',
    checklistItemId: 'wearable-pump',
    disclosure: true,
  },
  'amzcc-momcozy-m6-mobile-style-wearable-breast-pump': {
    id: 'amzcc-momcozy-m6-mobile-style-wearable-breast-pump',
    brand: 'Momcozy',
    product: 'M6 Mobile Style Wearable Breast Pump',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0DLGXVQXL?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0DLGXVQXL?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/31ohHdojnFL.jpg',
    checklistItemId: 'wearable-pump',
    disclosure: true,
  },
  'amzcc-momcozy-m9-mobile-flow-wearable-breast-pump': {
    id: 'amzcc-momcozy-m9-mobile-flow-wearable-breast-pump',
    brand: 'Momcozy',
    product: 'M9 Mobile Flow Wearable Breast Pump',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0FC6CTCY9?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0FC6CTCY9?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/31FqbIMLY9L.jpg',
    checklistItemId: 'wearable-pump',
    disclosure: true,
  },
  'amzcc-momcozy-s12-pro-wearable-breast-pump': {
    id: 'amzcc-momcozy-s12-pro-wearable-breast-pump',
    brand: 'Momcozy',
    product: 'S12 Pro Wearable Breast Pump',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0D4QYP5G7?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0D4QYP5G7?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41wcKOBTDvL.jpg',
    checklistItemId: 'wearable-pump',
    disclosure: true,
  },
  'amzcc-momcozy-wellness-1-warm-massage-wearable-pump': {
    id: 'amzcc-momcozy-wellness-1-warm-massage-wearable-pump',
    brand: 'Momcozy',
    product: 'Wellness 1 Warm-Massage Wearable Pump',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0G6417BM1?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0G6417BM1?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/410-AI1nFKL.jpg',
    checklistItemId: 'wearable-pump',
    disclosure: true,
  },
  'amzcc-mommed-s33-wearable-breast-pump': {
    id: 'amzcc-mommed-s33-wearable-breast-pump',
    brand: 'MomMed',
    product: 'S33 Wearable Breast Pump',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0GWMNGXDX?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0GWMNGXDX?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/31Zt1BZkaFL.jpg',
    checklistItemId: 'wearable-pump',
    disclosure: true,
  },
  'amzcc-momcozy-a1pro-lactation-massager-with-heat': {
    id: 'amzcc-momcozy-a1pro-lactation-massager-with-heat',
    brand: 'Momcozy',
    product: 'A1Pro Lactation Massager with Heat',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0DM5YGBMS?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0DM5YGBMS?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41ATvuUAg-L.jpg',
    checklistItemId: 'nursing-pads-balm',
    disclosure: true,
  },
  'amzcc-momcozy-nipple-cream-lanolin-free': {
    id: 'amzcc-momcozy-nipple-cream-lanolin-free',
    brand: 'Momcozy',
    product: 'Nipple Cream (Lanolin-Free)',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0C48SFRZR?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0C48SFRZR?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41fnfzfnGRL.jpg',
    checklistItemId: 'nursing-pads-balm',
    disclosure: true,
  },
  'amzcc-momcozy-cozypro-nursing-pillow': {
    id: 'amzcc-momcozy-cozypro-nursing-pillow',
    brand: 'Momcozy',
    product: 'CozyPro Nursing Pillow',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0DWWYWHPB?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0DWWYWHPB?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41BMbWP07hL.jpg',
    checklistItemId: 'nursing-pillow',
    disclosure: true,
  },
  'amzcc-haakaa-colostrum-collector-kit': {
    id: 'amzcc-haakaa-colostrum-collector-kit',
    brand: 'haakaa',
    product: 'Colostrum Collector Kit',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B08PV95M1D?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B08PV95M1D?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41fpkktcFJL.jpg',
    checklistItemId: 'milk-collectors',
    disclosure: true,
  },
  'amzcc-momcozy-22oz-portable-breastmilk-cooler': {
    id: 'amzcc-momcozy-22oz-portable-breastmilk-cooler',
    brand: 'Momcozy',
    product: '22oz Portable Breastmilk Cooler',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0DT4B8VCT?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0DT4B8VCT?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41+YuRg8frL.jpg',
    checklistItemId: 'insulated-bottle-cooler',
    disclosure: true,
  },
  'amzcc-papablic-glass-breast-milk-formula-pitcher': {
    id: 'amzcc-papablic-glass-breast-milk-formula-pitcher',
    brand: 'Papablic',
    product: 'Glass Breast Milk / Formula Pitcher',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0DN63XPMG?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0DN63XPMG?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41s+D2HQmtL.jpg',
    checklistItemId: 'formula-prep',
    disclosure: true,
  },
  'amzcc-momcozy-kleanpal-pro-bottle-washer-sterilizer-dryer': {
    id: 'amzcc-momcozy-kleanpal-pro-bottle-washer-sterilizer-dryer',
    brand: 'Momcozy',
    product: 'KleanPal Pro Bottle Washer, Sterilizer & Dryer',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0FFN1RJ8V?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0FFN1RJ8V?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/317awChDkVL.jpg',
    checklistItemId: 'bottle-washer',
    disclosure: true,
  },
  'amzcc-papablic-safeguardplus-bottle-washer-sterilizer-dryer': {
    id: 'amzcc-papablic-safeguardplus-bottle-washer-sterilizer-dryer',
    brand: 'Papablic',
    product: 'SafeguardPlus Bottle Washer, Sterilizer & Dryer',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0GX1Q8V3L?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0GX1Q8V3L?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41h3+dSQmML.jpg',
    checklistItemId: 'bottle-washer',
    disclosure: true,
  },
  'amzcc-eufy-bottle-washer-s1-non-pro': {
    id: 'amzcc-eufy-bottle-washer-s1-non-pro',
    brand: 'eufy',
    product: 'Bottle Washer S1 (non-Pro)',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0GRG52P1F?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0GRG52P1F?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/31lXqD8-nPL.jpg',
    checklistItemId: 'bottle-washer',
    disclosure: true,
  },
  'amzcc-papablic-bottle-washer-tablets-120ct': {
    id: 'amzcc-papablic-bottle-washer-tablets-120ct',
    brand: 'Papablic',
    product: 'Bottle Washer Tablets 120ct',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0FQ4Z6CP4?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0FQ4Z6CP4?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/415tX6bzyQL.jpg',
    checklistItemId: 'bottle-brush',
    disclosure: true,
  },
  'amzcc-haakaa-bottle-drying-rack-with-tray': {
    id: 'amzcc-haakaa-bottle-drying-rack-with-tray',
    brand: 'haakaa',
    product: 'Bottle Drying Rack with Tray',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0H6WQDB6R?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0H6WQDB6R?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41LRbEjX0UL.jpg',
    checklistItemId: 'bottle-drying-rack',
    disclosure: true,
  },
  'amzcc-haakaa-portable-foldable-bottle-drying-rack': {
    id: 'amzcc-haakaa-portable-foldable-bottle-drying-rack',
    brand: 'haakaa',
    product: 'Portable Foldable Bottle Drying Rack',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0DJR2TB5P?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0DJR2TB5P?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41EAzXCkutL.jpg',
    checklistItemId: 'bottle-drying-rack',
    disclosure: true,
  },
  'amzcc-momcozy-7-in-1-bottle-brush-set-with-drying-rack': {
    id: 'amzcc-momcozy-7-in-1-bottle-brush-set-with-drying-rack',
    brand: 'Momcozy',
    product: '7-in-1 Bottle Brush Set with Drying Rack',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0DCZNX8NZ?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0DCZNX8NZ?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41by9cpwo-L.jpg',
    checklistItemId: 'bottle-brush',
    disclosure: true,
  },
  'amzcc-momcozy-push-press-foam-bottle-brush-kit': {
    id: 'amzcc-momcozy-push-press-foam-bottle-brush-kit',
    brand: 'Momcozy',
    product: 'Push-Press Foam Bottle Brush Kit',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0D9Y3MSDY?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0D9Y3MSDY?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41+Yp-nftBL.jpg',
    checklistItemId: 'bottle-brush',
    disclosure: true,
  },
  'amzcc-haakaa-double-ended-silicone-bottle-brush': {
    id: 'amzcc-haakaa-double-ended-silicone-bottle-brush',
    brand: 'haakaa',
    product: 'Double-Ended Silicone Bottle Brush',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B09DCCWFX9?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B09DCCWFX9?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41kURkxa6kL.jpg',
    checklistItemId: 'bottle-brush',
    disclosure: true,
  },
  'amzcc-papablic-portable-uv-pacifier-sanitizer': {
    id: 'amzcc-papablic-portable-uv-pacifier-sanitizer',
    brand: 'Papablic',
    product: 'Portable UV Pacifier Sanitizer',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B08P5CSF9W?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B08P5CSF9W?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/31nf46ALPzL.jpg',
    checklistItemId: 'sterilizer',
    disclosure: true,
  },
  'amzcc-stokke-tripp-trapp-high-chair-baby-set-newborn-set': {
    id: 'amzcc-stokke-tripp-trapp-high-chair-baby-set-newborn-set',
    brand: 'Stokke',
    product: 'Tripp Trapp High Chair + Baby Set / Newborn Set',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0D5KJNRVH?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0D5KJNRVH?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/31FYCsf+C-L.jpg',
    checklistItemId: 'high-chair',
    disclosure: true,
  },
  'amzcc-stokke-clikk-high-chair-tray-harness': {
    id: 'amzcc-stokke-clikk-high-chair-tray-harness',
    brand: 'Stokke',
    product: 'Clikk High Chair (tray + harness)',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0BLHVZ4H7?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0BLHVZ4H7?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/31OeJ0BNt4L.jpg',
    checklistItemId: 'high-chair',
    disclosure: true,
  },
  'amzcc-stokke-steps-high-chair': {
    id: 'amzcc-stokke-steps-high-chair',
    brand: 'Stokke',
    product: 'Steps High Chair',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0GHPLLM1Y?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0GHPLLM1Y?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/31T8Mmssp+L.jpg',
    checklistItemId: 'high-chair',
    disclosure: true,
  },
  'amzcc-stokke-steps-baby-set-cushion': {
    id: 'amzcc-stokke-steps-baby-set-cushion',
    brand: 'Stokke',
    product: 'Steps Baby Set Cushion',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B09L1MPRTK?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B09L1MPRTK?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/31GMe3xRY4L.jpg',
    checklistItemId: 'high-chair-fit-extras',
    disclosure: true,
  },
  'amzcc-stokke-clikk-cushion': {
    id: 'amzcc-stokke-clikk-cushion',
    brand: 'Stokke',
    product: 'Clikk Cushion',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0F2B1W2PN?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0F2B1W2PN?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/31RVa1FaaAL.jpg',
    checklistItemId: 'high-chair-fit-extras',
    disclosure: true,
  },
  'amzcc-stokke-clikk-high-chair-travel-bag': {
    id: 'amzcc-stokke-clikk-high-chair-travel-bag',
    brand: 'Stokke',
    product: 'Clikk High Chair Travel Bag',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B08Q35B7L6?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B08Q35B7L6?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/31szRxAkJ8L.jpg',
    checklistItemId: 'portable-high-chair',
    disclosure: true,
  },
  'amzcc-haakaa-fruit-feeder-freezer-nibble-tray-combo': {
    id: 'amzcc-haakaa-fruit-feeder-freezer-nibble-tray-combo',
    brand: 'haakaa',
    product: 'Fruit Feeder & Freezer Nibble Tray Combo',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B09VL3D9QG?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B09VL3D9QG?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41SMm4qbc6L.jpg',
    checklistItemId: 'snack-food-storage',
    disclosure: true,
  },
  'amzcc-haakaa-clover-fruit-feeder-teether-pear-freezer-tray': {
    id: 'amzcc-haakaa-clover-fruit-feeder-teether-pear-freezer-tray',
    brand: 'haakaa',
    product: 'Clover Fruit Feeder & Teether + Pear Freezer Tray',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0DP9L89NR?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0DP9L89NR?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41SLQDfWl+L.jpg',
    checklistItemId: 'snack-food-storage',
    disclosure: true,
  },
  'amzcc-haakaa-flower-fruit-feeder-mini-freezer-tray': {
    id: 'amzcc-haakaa-flower-fruit-feeder-mini-freezer-tray',
    brand: 'haakaa',
    product: 'Flower Fruit Feeder + Mini Freezer Tray',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0CP1ZHT74?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0CP1ZHT74?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/410DG7UJF7L.jpg',
    checklistItemId: 'snack-food-storage',
    disclosure: true,
  },
  'amzcc-haakaa-octopus-fruit-feeder-mini-freezer-tray': {
    id: 'amzcc-haakaa-octopus-fruit-feeder-mini-freezer-tray',
    brand: 'haakaa',
    product: 'Octopus Fruit Feeder + Mini Freezer Tray',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0CXT9X846?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0CXT9X846?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/415gy7m4pOL.jpg',
    checklistItemId: 'snack-food-storage',
    disclosure: true,
  },
  'amzcc-haakaa-silicone-training-open-cup-5oz': {
    id: 'amzcc-haakaa-silicone-training-open-cup-5oz',
    brand: 'haakaa',
    product: 'Silicone Training Open Cup 5oz',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0FBGC3GJS?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0FBGC3GJS?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/313fMznzv0L.jpg',
    checklistItemId: 'open-straw-cups',
    disclosure: true,
  },
  'amzcc-evolur-snuggle-bum-diapers-size-1': {
    id: 'amzcc-evolur-snuggle-bum-diapers-size-1',
    brand: 'Evolur',
    product: 'Snuggle Bum Diapers Size 1',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0FMYK27DZ?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0FMYK27DZ?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41-SLmgNOsL.jpg',
    checklistItemId: 'size-one-diapers',
    disclosure: true,
  },
  'amzcc-grownsy-odor-locking-diaper-pail': {
    id: 'amzcc-grownsy-odor-locking-diaper-pail',
    brand: 'GROWNSY',
    product: 'Odor-Locking Diaper Pail',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0GFD65QGN?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0GFD65QGN?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/21zYlOgQN7L.jpg',
    checklistItemId: 'diaper-pail',
    disclosure: true,
  },
  'amzcc-woddle-smart-changing-pad-with-scale': {
    id: 'amzcc-woddle-smart-changing-pad-with-scale',
    brand: 'Woddle',
    product: 'Smart Changing Pad with Scale',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0DV48QLRD?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0DV48QLRD?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41L4svgBNfL.jpg',
    checklistItemId: 'changing-pad',
    disclosure: true,
  },
  'amzcc-lovevook-diaper-bag-backpack-with-changing-pad': {
    id: 'amzcc-lovevook-diaper-bag-backpack-with-changing-pad',
    brand: 'LOVEVOOK',
    product: 'Diaper Bag Backpack with Changing Pad',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0F1S7GLJY?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0F1S7GLJY?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41o5eefbKyL.jpg',
    checklistItemId: 'diaper-bag-backpack',
    disclosure: true,
  },
  'amzcc-momcozy-diaper-bag-backpack': {
    id: 'amzcc-momcozy-diaper-bag-backpack',
    brand: 'Momcozy',
    product: 'Diaper Bag Backpack',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0H7X49K96?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0H7X49K96?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41jjc-yS9JL.jpg',
    checklistItemId: 'diaper-bag-backpack',
    disclosure: true,
  },
  'amzcc-stokke-flexi-bath-x-large-tub': {
    id: 'amzcc-stokke-flexi-bath-x-large-tub',
    brand: 'Stokke',
    product: 'Flexi Bath X-Large Tub',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B07RJ3C7DX?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B07RJ3C7DX?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/31sIQdZ-O5L.jpg',
    checklistItemId: 'bathtub',
    disclosure: true,
  },
  'amzcc-stokke-flexi-bath-x-large-bundle-with-newborn-insert': {
    id: 'amzcc-stokke-flexi-bath-x-large-bundle-with-newborn-insert',
    brand: 'Stokke',
    product: 'Flexi Bath X-Large Bundle (with newborn insert)',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0C51LQKHC?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0C51LQKHC?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/31iTyCKwliL.jpg',
    checklistItemId: 'bathtub',
    disclosure: true,
  },
  'amzcc-stokke-flexi-bath-newborn-support': {
    id: 'amzcc-stokke-flexi-bath-newborn-support',
    brand: 'Stokke',
    product: 'Flexi Bath Newborn Support',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B00JWHAUDE?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B00JWHAUDE?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/319Drlwxf3L.jpg',
    checklistItemId: 'bathtub',
    disclosure: true,
  },
  'amzcc-jveoo-bath-kneeler-elbow-rest-set': {
    id: 'amzcc-jveoo-bath-kneeler-elbow-rest-set',
    brand: 'JVEOO',
    product: 'Bath Kneeler & Elbow Rest Set',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0GX1B6MBQ?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0GX1B6MBQ?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/416fizOtw5L.jpg',
    checklistItemId: 'kneeler',
    disclosure: true,
  },
  'amzcc-haakaa-silicone-shampoo-cradle-cap-brush': {
    id: 'amzcc-haakaa-silicone-shampoo-cradle-cap-brush',
    brand: 'haakaa',
    product: 'Silicone Shampoo / Cradle Cap Brush',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B08CV611V1?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B08CV611V1?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41ZOFc-z+KL.jpg',
    checklistItemId: 'baby-wash',
    disclosure: true,
  },
  'amzcc-momcozy-baby-hooded-towels': {
    id: 'amzcc-momcozy-baby-hooded-towels',
    brand: 'Momcozy',
    product: 'Baby Hooded Towels',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0CKXKR1RV?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0CKXKR1RV?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41PjOK7YCBL.jpg',
    checklistItemId: 'hooded-towels',
    disclosure: true,
  },
  'amzcc-haakaa-silicone-nasal-aspirator-bulb': {
    id: 'amzcc-haakaa-silicone-nasal-aspirator-bulb',
    brand: 'haakaa',
    product: 'Silicone Nasal Aspirator (bulb)',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B09Q61B4MM?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B09Q61B4MM?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/31QEHsnbqhL.jpg',
    checklistItemId: 'nasal-saline',
    disclosure: true,
  },
  'amzcc-haakaa-swan-neck-nasal-aspirator': {
    id: 'amzcc-haakaa-swan-neck-nasal-aspirator',
    brand: 'haakaa',
    product: 'Swan Neck Nasal Aspirator',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0FKGJYDFH?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0FKGJYDFH?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/31hYgdKgDDL.jpg',
    checklistItemId: 'nasal-saline',
    disclosure: true,
  },
  'amzcc-haakaa-crocodile-nose-ear-cleaner': {
    id: 'amzcc-haakaa-crocodile-nose-ear-cleaner',
    brand: 'haakaa',
    product: 'Crocodile Nose & Ear Cleaner',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0DXPYSLBH?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0DXPYSLBH?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41X0LrTr3RL.jpg',
    checklistItemId: 'nasal-saline',
    disclosure: true,
  },
  'amzcc-haakaa-medicine-dispenser-set': {
    id: 'amzcc-haakaa-medicine-dispenser-set',
    brand: 'haakaa',
    product: 'Medicine Dispenser Set',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0DJVLSZQ7?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0DJVLSZQ7?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41SR7rFE41L.jpg',
    checklistItemId: 'oral-syringe',
    disclosure: true,
  },
  'amzcc-haakaa-penguin-dual-feeding-syringe-set': {
    id: 'amzcc-haakaa-penguin-dual-feeding-syringe-set',
    brand: 'haakaa',
    product: 'Penguin Dual Feeding Syringe Set',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0DQ4HTWQ5?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0DQ4HTWQ5?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/410lywaR+0L.jpg',
    checklistItemId: 'oral-syringe',
    disclosure: true,
  },
  'amzcc-haakaa-silicone-finger-toothbrush': {
    id: 'amzcc-haakaa-silicone-finger-toothbrush',
    brand: 'haakaa',
    product: 'Silicone Finger Toothbrush',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B09MJ2SWKQ?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B09MJ2SWKQ?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41ci47jGvdL.jpg',
    checklistItemId: 'toothbrush-teethers',
    disclosure: true,
  },
  'amzcc-haakaa-training-toothbrush-set': {
    id: 'amzcc-haakaa-training-toothbrush-set',
    brand: 'haakaa',
    product: 'Training Toothbrush Set',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0DCB8RJG3?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0DCB8RJG3?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41YusY5hftL.jpg',
    checklistItemId: 'toothbrush-teethers',
    disclosure: true,
  },
  'amzcc-mommy-s-bliss-infants-acetaminophen-dye-free': {
    id: 'amzcc-mommy-s-bliss-infants-acetaminophen-dye-free',
    brand: 'Mommy\'s Bliss',
    product: 'Infants\' Acetaminophen (dye-free)',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0CX2WPYCP?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0CX2WPYCP?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41pCTxbgflL.jpg',
    checklistItemId: 'first-aid-basics',
    disclosure: true,
  },
  'amzcc-bugaboo-butterfly-2-plus-travel-stroller': {
    id: 'amzcc-bugaboo-butterfly-2-plus-travel-stroller',
    brand: 'Bugaboo',
    product: 'Butterfly 2 Plus Travel Stroller',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0H4MBSTGD?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0H4MBSTGD?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/419RVJ6VPML.jpg',
    checklistItemId: 'travel-system-stroller',
    disclosure: true,
  },
  'amzcc-bugaboo-donkey-6-single-to-double-twin-stroller': {
    id: 'amzcc-bugaboo-donkey-6-single-to-double-twin-stroller',
    brand: 'Bugaboo',
    product: 'Donkey 6 Single-to-Double / Twin Stroller',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0G5J346Q9?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0G5J346Q9?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41AVfFnrhQL.jpg',
    checklistItemId: 'primary-stroller',
    disclosure: true,
  },
  'amzcc-bugaboo-kangaroo-single-to-double-tandem-stroller': {
    id: 'amzcc-bugaboo-kangaroo-single-to-double-tandem-stroller',
    brand: 'Bugaboo',
    product: 'Kangaroo Single-to-Double Tandem Stroller',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0GLQSHTF1?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0GLQSHTF1?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41vIU+aUd0L.jpg',
    checklistItemId: 'primary-stroller',
    disclosure: true,
  },
  'amzcc-bugaboo-kangaroo-travel-system-with-turtle-air-shield': {
    id: 'amzcc-bugaboo-kangaroo-travel-system-with-turtle-air-shield',
    brand: 'Bugaboo',
    product: 'Kangaroo Travel System (with Turtle Air Shield)',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0H5FX385Y?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0H5FX385Y?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/31iOHoupLxL.jpg',
    checklistItemId: 'primary-stroller',
    disclosure: true,
  },
  'amzcc-bugaboo-turtle-air-shield-by-nuna-infant-car-seat': {
    id: 'amzcc-bugaboo-turtle-air-shield-by-nuna-infant-car-seat',
    brand: 'Bugaboo',
    product: 'Turtle Air Shield by Nuna Infant Car Seat',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0DG6JDL1M?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0DG6JDL1M?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/31RbsBKL4pL.jpg',
    checklistItemId: 'infant-car-seat',
    disclosure: true,
  },
  'amzcc-baby-trend-secure-lift-infant-car-seat': {
    id: 'amzcc-baby-trend-secure-lift-infant-car-seat',
    brand: 'Baby Trend',
    product: 'Secure-Lift Infant Car Seat',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0C8HD88DW?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0C8HD88DW?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41RoPyTGWTL.jpg',
    checklistItemId: 'infant-car-seat',
    disclosure: true,
  },
  'amzcc-stokke-yoyo3-travel-stroller-6m': {
    id: 'amzcc-stokke-yoyo3-travel-stroller-6m',
    brand: 'Stokke',
    product: 'YOYO3 Travel Stroller (6M+)',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0D8JRBLN4?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0D8JRBLN4?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41O4E6HttqL.jpg',
    checklistItemId: 'travel-system-stroller',
    disclosure: true,
  },
  'amzcc-stokke-yoyo3-stroller-newborn-to-toddler': {
    id: 'amzcc-stokke-yoyo3-stroller-newborn-to-toddler',
    brand: 'Stokke',
    product: 'YOYO3 Stroller Newborn-to-Toddler',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0D8JRDHWM?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0D8JRDHWM?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41dMgxcOWLL.jpg',
    checklistItemId: 'travel-system-stroller',
    disclosure: true,
  },
  'amzcc-stokke-yoyo3-frame-only': {
    id: 'amzcc-stokke-yoyo3-frame-only',
    brand: 'Stokke',
    product: 'YOYO3 Frame Only',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0D8JVPCZS?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0D8JVPCZS?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41-nhX-gXaL.jpg',
    checklistItemId: 'travel-system-stroller',
    disclosure: true,
  },
  'amzcc-stokke-yoyo-0-newborn-pack': {
    id: 'amzcc-stokke-yoyo-0-newborn-pack',
    brand: 'Stokke',
    product: 'YOYO 0+ Newborn Pack',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0D8JTPHPY?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0D8JTPHPY?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/31SnWDpDA6L.jpg',
    checklistItemId: 'stroller-bassinet',
    disclosure: true,
  },
  'amzcc-stokke-yoyo-6-color-pack': {
    id: 'amzcc-stokke-yoyo-6-color-pack',
    brand: 'Stokke',
    product: 'YOYO 6+ Color Pack',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0D8JVSBF1?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0D8JVSBF1?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/310Q5v-f5iL.jpg',
    checklistItemId: 'travel-system-stroller',
    disclosure: true,
  },
  'amzcc-stokke-yoyo-car-seat-adapters': {
    id: 'amzcc-stokke-yoyo-car-seat-adapters',
    brand: 'Stokke',
    product: 'YOYO Car Seat Adapters',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0F1GC9ND4?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0F1GC9ND4?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/31hsY0G0Z7L.jpg',
    checklistItemId: 'car-seat-adapters',
    disclosure: true,
  },
  'amzcc-stokke-yoyo-board-sibling': {
    id: 'amzcc-stokke-yoyo-board-sibling',
    brand: 'Stokke',
    product: 'YOYO Board (sibling)',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0CXZDKHRD?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0CXZDKHRD?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/31-l0qpvlPL.jpg',
    checklistItemId: 'sibling-stroller-kit',
    disclosure: true,
  },
  'amzcc-stokke-yoyo-connect-double-conversion': {
    id: 'amzcc-stokke-yoyo-connect-double-conversion',
    brand: 'Stokke',
    product: 'YOYO Connect (double conversion)',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0F9B8KX77?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0F9B8KX77?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/31-3Y1lYJAL.jpg',
    checklistItemId: 'sibling-stroller-kit',
    disclosure: true,
  },
  'amzcc-stokke-yoyo-accessories-parasol-footmuff-bag-rain-covers-nets': {
    id: 'amzcc-stokke-yoyo-accessories-parasol-footmuff-bag-rain-covers-nets',
    brand: 'Stokke',
    product: 'YOYO Accessories (parasol, footmuff, bag, rain covers, nets)',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0CXZBDGBY?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0CXZBDGBY?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/212CVbek3QL.jpg',
    checklistItemId: 'stroller-weather-accessories',
    disclosure: true,
  },
  'amzcc-mompush-nexis-carbon-fiber-travel-stroller': {
    id: 'amzcc-mompush-nexis-carbon-fiber-travel-stroller',
    brand: 'mompush',
    product: 'Nexis Carbon Fiber Travel Stroller',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0FPFYG1BS?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0FPFYG1BS?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41MPlKUCMpL.jpg',
    checklistItemId: 'travel-system-stroller',
    disclosure: true,
  },
  'amzcc-mompush-lithe-v2-travel-stroller': {
    id: 'amzcc-mompush-lithe-v2-travel-stroller',
    brand: 'mompush',
    product: 'Lithe V2 Travel Stroller',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0B7MFS2W4?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0B7MFS2W4?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41gUExdf72L.jpg',
    checklistItemId: 'travel-system-stroller',
    disclosure: true,
  },
  'amzcc-mompush-meteor2-bassinet-stroller': {
    id: 'amzcc-mompush-meteor2-bassinet-stroller',
    brand: 'mompush',
    product: 'Meteor2 Bassinet Stroller',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B093KTNC1M?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B093KTNC1M?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41gONpMwGYL.jpg',
    checklistItemId: 'primary-stroller',
    disclosure: true,
  },
  'amzcc-evolur-trailblazer-double-wagon-stroller': {
    id: 'amzcc-evolur-trailblazer-double-wagon-stroller',
    brand: 'Evolur',
    product: 'Trailblazer Double Wagon Stroller',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0G6SPVQSG?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0G6SPVQSG?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/419f9EYwEpL.jpg',
    checklistItemId: 'primary-stroller',
    disclosure: true,
  },
  'amzcc-wildbird-ring-sling-linen': {
    id: 'amzcc-wildbird-ring-sling-linen',
    brand: 'WildBird',
    product: 'Ring Sling (linen)',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B087SJZ1RL?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B087SJZ1RL?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/31GiumAhFlL.jpg',
    checklistItemId: 'soft-wrap-carrier',
    disclosure: true,
  },
  'amzcc-grownsy-ergonomic-baby-carrier-7-44-lb': {
    id: 'amzcc-grownsy-ergonomic-baby-carrier-7-44-lb',
    brand: 'GROWNSY',
    product: 'Ergonomic Baby Carrier (7-44 lb)',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0F7WVV82S?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0F7WVV82S?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/419kPHT4F4L.jpg',
    checklistItemId: 'carrier',
    disclosure: true,
  },
  'amzcc-grownsy-cooling-baby-carrier-with-built-in-fan': {
    id: 'amzcc-grownsy-cooling-baby-carrier-with-built-in-fan',
    brand: 'GROWNSY',
    product: 'Cooling Baby Carrier with Built-in Fan',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0GZ4F1V61?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0GZ4F1V61?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41b81r09MBL.jpg',
    checklistItemId: 'carrier',
    disclosure: true,
  },
  'amzcc-momcozy-baby-wrap-carrier-2-piece': {
    id: 'amzcc-momcozy-baby-wrap-carrier-2-piece',
    brand: 'Momcozy',
    product: 'Baby Wrap Carrier (2-piece)',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B098X8WS7Y?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B098X8WS7Y?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41aNHmYjfGL.jpg',
    checklistItemId: 'soft-wrap-carrier',
    disclosure: true,
  },
  'amzcc-momcozy-2-in-1-hip-seat-carrier': {
    id: 'amzcc-momcozy-2-in-1-hip-seat-carrier',
    brand: 'Momcozy',
    product: '2-in-1 Hip Seat Carrier',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0DSP23G39?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0DSP23G39?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/414vFVwxSxL.jpg',
    checklistItemId: 'carrier',
    disclosure: true,
  },
  'amzcc-momcozy-hip-seat-carrier-up-to-45-lb': {
    id: 'amzcc-momcozy-hip-seat-carrier-up-to-45-lb',
    brand: 'Momcozy',
    product: 'Hip Seat Carrier (up to 45 lb)',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0H7CFSNNJ?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0H7CFSNNJ?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41Y+LuuVUTL.jpg',
    checklistItemId: 'carrier',
    disclosure: true,
  },
  'amzcc-angelbliss-6-in-1-hip-seat-carrier': {
    id: 'amzcc-angelbliss-6-in-1-hip-seat-carrier',
    brand: 'ANGELBLISS',
    product: '6-in-1 Hip Seat Carrier',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0GVQJHJ12?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0GVQJHJ12?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41vM49HiZCL.jpg',
    checklistItemId: 'carrier',
    disclosure: true,
  },
  'amzcc-safety-1st-4-in-1-convertible-carrier': {
    id: 'amzcc-safety-1st-4-in-1-convertible-carrier',
    brand: 'Safety 1st',
    product: '4-in-1 Convertible Carrier',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0GY5SH3BM?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0GY5SH3BM?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41ocnwzSGRL.jpg',
    checklistItemId: 'carrier',
    disclosure: true,
  },
  'amzcc-haakaa-silicone-clover-teether': {
    id: 'amzcc-haakaa-silicone-clover-teether',
    brand: 'haakaa',
    product: 'Silicone Clover Teether',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0GKZT51YX?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0GKZT51YX?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/31Z6omq847L.jpg',
    checklistItemId: 'teethers',
    disclosure: true,
  },
  'amzcc-haakaa-silicone-palm-teether': {
    id: 'amzcc-haakaa-silicone-palm-teether',
    brand: 'haakaa',
    product: 'Silicone Palm Teether',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0F52P8B9H?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0F52P8B9H?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/31efsYXd7yL.jpg',
    checklistItemId: 'teethers',
    disclosure: true,
  },
  'amzcc-dream-on-me-curio-sit-n-seek-activity-center': {
    id: 'amzcc-dream-on-me-curio-sit-n-seek-activity-center',
    brand: 'Dream On Me',
    product: 'Curio Sit N Seek Activity Center',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0CBL33FG3?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0CBL33FG3?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41G1zgL8JvL.jpg',
    checklistItemId: 'activity-center',
    disclosure: true,
  },
  'amzcc-grownsy-dual-motion-baby-swing': {
    id: 'amzcc-grownsy-dual-motion-baby-swing',
    brand: 'GROWNSY',
    product: 'Dual Motion Baby Swing',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0GK6V1PCM?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0GK6V1PCM?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/41ANx5fpP-L.jpg',
    checklistItemId: 'swing',
    disclosure: true,
  },
  'amzcc-momcozy-2-in-1-electric-baby-swing': {
    id: 'amzcc-momcozy-2-in-1-electric-baby-swing',
    brand: 'Momcozy',
    product: '2-in-1 Electric Baby Swing',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0FH6Q7T6B?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0FH6Q7T6B?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/31RVgwl32CL.jpg',
    checklistItemId: 'swing',
    disclosure: true,
  },
  'amzcc-grownsy-postpartum-recovery-kit': {
    id: 'amzcc-grownsy-postpartum-recovery-kit',
    brand: 'GROWNSY',
    product: 'Postpartum Recovery Kit',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0BXWGT29Z?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0BXWGT29Z?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/410tQwTY0hL.jpg',
    checklistItemId: 'postpartum-underwear-pads',
    disclosure: true,
  },
  'amzcc-haakaa-seamless-nursing-bra': {
    id: 'amzcc-haakaa-seamless-nursing-bra',
    brand: 'haakaa',
    product: 'Seamless Nursing Bra',
    review: 'An Amazon pick from Taylor\'s storefront. Check the listing for current specs, sizing and price.',
    bestFor: '',
    standout: '',
    affiliateUrl: 'https://www.amazon.com/dp/B0FK9VT9W6?tag=taylormadebab-20',
    amazonUrl: 'https://www.amazon.com/dp/B0FK9VT9W6?tag=taylormadebab-20',
    retailer: 'Amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/31s-UTF3zbL.jpg',
    checklistItemId: 'nursing-pumping-bras',
    disclosure: true,
  },

};

export function getProduct(id: string | undefined): ChecklistProduct | undefined {
  if (!id) return undefined;
  return products[id];
}

/** True when a real affiliate URL has been pasted in (so a CTA should render). */
export function hasLiveLink(product: ChecklistProduct | undefined): boolean {
  return Boolean(product && product.affiliateUrl && product.affiliateUrl !== AFFILIATE_LINK_NEEDED);
}
