import type { Prisma } from '@prisma/client';
import {
  sanitizeGuideAffiliateModules,
  sanitizeGuideFaqItems,
  sanitizeStringList,
} from '@/lib/guides/types';

export const guideEditorSelect = {
  id: true,
  title: true,
  slug: true,
  excerpt: true,
  intro: true,
  content: true,
  conclusion: true,
  heroImageUrl: true,
  heroImageAlt: true,
  authorId: true,
  category: true,
  topicCluster: true,
  status: true,
  publishedAt: true,
  scheduledFor: true,
  archivedAt: true,
  seoTitle: true,
  seoDescription: true,
  ogTitle: true,
  ogDescription: true,
  ogImageUrl: true,
  ogImageAlt: true,
  canonicalUrl: true,
  targetKeyword: true,
  secondaryKeywords: true,
  internalLinkNotes: true,
  tableOfContentsEnabled: true,
  faqItems: true,
  affiliateDisclosureEnabled: true,
  affiliateDisclosureText: true,
  affiliateDisclosurePlacement: true,
  affiliateModules: true,
  consultationCtaEnabled: true,
  consultationCtaLabel: true,
  newsletterCtaEnabled: true,
  newsletterCtaLabel: true,
  newsletterCtaDescription: true,
  newsletterCtaHref: true,
  nextStepCtaLabel: true,
  nextStepCtaHref: true,
  founderSignatureEnabled: true,
  founderSignatureText: true,
  relatedGuideIds: true,
  views: true,
  createdAt: true,
  updatedAt: true,
  author: {
    select: {
      name: true,
      email: true,
    },
  },
} satisfies Prisma.GuideSelect;

export type GuideEditorQueryResult = Prisma.GuideGetPayload<{
  select: typeof guideEditorSelect;
}>;

export function toGuideEditorRecord(guide: GuideEditorQueryResult) {
  return {
    id: guide.id,
    title: guide.title,
    slug: guide.slug,
    excerpt: guide.excerpt,
    intro: guide.intro,
    content: guide.content,
    conclusion: guide.conclusion,
    heroImageUrl: guide.heroImageUrl,
    heroImageAlt: guide.heroImageAlt,
    authorId: guide.authorId,
    authorLabel: guide.author.name?.trim() || guide.author.email,
    category: guide.category,
    topicCluster: guide.topicCluster,
    status: guide.status,
    publishedAt: guide.publishedAt,
    scheduledFor: guide.scheduledFor,
    archivedAt: guide.archivedAt,
    seoTitle: guide.seoTitle,
    seoDescription: guide.seoDescription,
    ogTitle: guide.ogTitle,
    ogDescription: guide.ogDescription,
    ogImageUrl: guide.ogImageUrl,
    ogImageAlt: guide.ogImageAlt,
    canonicalUrl: guide.canonicalUrl,
    targetKeyword: guide.targetKeyword,
    secondaryKeywords: sanitizeStringList(guide.secondaryKeywords),
    internalLinkNotes: guide.internalLinkNotes,
    tableOfContentsEnabled: guide.tableOfContentsEnabled,
    faqItems: sanitizeGuideFaqItems(guide.faqItems),
    affiliateDisclosureEnabled: guide.affiliateDisclosureEnabled,
    affiliateDisclosureText: guide.affiliateDisclosureText,
    affiliateDisclosurePlacement: guide.affiliateDisclosurePlacement,
    affiliateModules: sanitizeGuideAffiliateModules(guide.affiliateModules),
    consultationCtaEnabled: guide.consultationCtaEnabled,
    consultationCtaLabel: guide.consultationCtaLabel,
    newsletterCtaEnabled: guide.newsletterCtaEnabled,
    newsletterCtaLabel: guide.newsletterCtaLabel,
    newsletterCtaDescription: guide.newsletterCtaDescription,
    newsletterCtaHref: guide.newsletterCtaHref,
    nextStepCtaLabel: guide.nextStepCtaLabel,
    nextStepCtaHref: guide.nextStepCtaHref,
    founderSignatureEnabled: guide.founderSignatureEnabled,
    founderSignatureText: guide.founderSignatureText,
    relatedGuideIds: sanitizeStringList(guide.relatedGuideIds),
    views: guide.views,
    createdAt: guide.createdAt,
    updatedAt: guide.updatedAt,
  };
}

