import type { GuideProductExampleData } from '@/lib/guides/productExamples';

export const CAR_SEAT_PRODUCT_GROUPS = {
  infant: [
    {
      name: 'Nuna PIPA RX',
      brand: 'Nuna',
      productName: 'PIPA RX',
      imageAlt: 'Nuna PIPA RX infant car seat.',
      typeLabel: 'Infant Car Seat',
      bestFor: 'lightweight luxury plus easier everyday carrying',
      shortReview:
        'A strong infant anchor because it keeps the newborn stage simple: premium, light in the hand, and easier to carry when the seat will move with you often.',
      specGroups: [
        { label: 'Usage', items: ['4-30 lbs', '16-30 in'] },
        { label: 'Weight', items: ['7.6 lbs (carrier only)'] },
      ],
      notes: ['One of the lightest premium infant seats.', 'Ideal for frequent in-and-out use.'],
      ctaLabel: 'View Nuna PIPA RX',
      standout: 'Lightweight premium infant lane',
      pros: ['Light carrier weight', 'Premium build', 'Easy day-to-day carrying'],
    },
    {
      name: 'UPPAbaby Mesa V3',
      brand: 'UPPAbaby',
      productName: 'Mesa V3',
      imageAlt: 'UPPAbaby Mesa V3 infant car seat.',
      typeLabel: 'Infant Car Seat',
      bestFor: 'seamless UPPAbaby system integration',
      shortReview:
        'Helpful because it shows how much smoother the infant stage can feel when the seat, stroller, and install routine all work together without extra friction.',
      specGroups: [
        { label: 'Usage', items: ['Birth to around 1 year', '4-30 lbs', 'Up to 32 in'] },
        {
          label: 'Dimensions',
          items: [
            'Seat: 17"W x 25.8"L x 23"H',
            'With base: 17"W x 28"L x 25"H',
            'Base only: 14.5"W x 21.3"L x 10.3"H',
          ],
        },
        { label: 'Weight', items: ['Carrier: 9.9 lbs', 'Base: 9 lbs'] },
      ],
      notes: ['One of the easiest installs in the category.', 'Best for Vista and Cruz users.'],
      ctaLabel: 'View Mesa V3',
      standout: 'Stroller-system ease',
      pros: ['Smooth UPPAbaby integration', 'Straightforward install', 'Strong early-stage convenience'],
    },
    {
      name: 'Clek Liing',
      brand: 'Clek',
      productName: 'Liing',
      imageAlt: 'Clek Liing infant car seat.',
      typeLabel: 'Infant Car Seat',
      bestFor: 'safety-focused minimal design',
      shortReview:
        'A useful infant example because it keeps the conversation grounded in installation confidence, clean design, and solid everyday execution instead of just carry-handle marketing.',
      specGroups: [
        { label: 'Usage', items: ['4-30 lbs', 'Up to 32 in'] },
        { label: 'Weight', items: ['9 lbs (carrier)', '25 lbs with base'] },
      ],
      notes: ['Rigid LATCH system.', 'Excellent build quality.'],
      ctaLabel: 'View Clek Liing',
      standout: 'Installation confidence',
      pros: ['Rigid LATCH base', 'Premium build quality', 'Strong safety-minded design'],
    },
    {
      name: 'CYBEX Aton Swivel',
      brand: 'CYBEX',
      productName: 'Aton Swivel',
      imageAlt: 'CYBEX Aton Swivel infant car seat.',
      typeLabel: 'Infant Car Seat',
      bestFor: 'rotation plus easier loading',
      shortReview:
        'Important here because it shows that rotation can start in the infant lane too, which keeps the swivel conversation from collapsing into convertible-only thinking.',
      specGroups: [
        { label: 'Usage', items: ['4-30 lbs', 'Up to 30 in'] },
        { label: 'Weight', items: ['9 lbs'] },
        { label: 'Dimensions', items: ['26.1"L x 17.5"W x 14.7"H'] },
      ],
      notes: ['Swivel functionality simplifies loading.'],
      ctaLabel: 'View CYBEX Aton Swivel',
      standout: 'Rotating infant example',
      pros: ['Swivel loading help', 'Infant-stage convenience', 'Keeps rotation stage-specific'],
    },
  ],
  convertible: [
    {
      name: 'Nuna RAVA',
      brand: 'Nuna',
      productName: 'RAVA',
      imageAlt: 'Nuna RAVA convertible car seat.',
      typeLabel: 'Convertible',
      bestFor: 'extended rear-facing plus everyday comfort',
      shortReview:
        'A strong convertible anchor because it represents the installed-seat lane at its clearest: long-run use, everyday comfort, and less focus on portability.',
      specGroups: [
        {
          label: 'Rear-facing',
          items: ['5-50 lbs (seat belt)', '5-35 lbs (LATCH)', '18-49 in'],
        },
        {
          label: 'Forward-facing',
          items: ['30-65 lbs', '34-49 in'],
        },
        { label: 'Weight', items: ['26.5 lbs'] },
      ],
      notes: ['One of the most recommended all-around seats.'],
      ctaLabel: 'View Nuna RAVA',
      standout: 'Long-run everyday seat',
      pros: ['Extended rear-facing', 'Comfortable daily-use seat', 'Strong all-around convertible fit'],
    },
    {
      name: 'Britax Poplar S',
      brand: 'Britax',
      productName: 'Poplar S',
      imageAlt: 'Britax Poplar S convertible car seat.',
      typeLabel: 'Convertible',
      bestFor: 'compact installs plus easier everyday use',
      shortReview:
        'Helpful because it shows how the convertible lane can still solve space problems well when you need a strong installed seat without a huge footprint.',
      specGroups: [
        { label: 'Usage', items: ['5-65 lbs'] },
        { label: 'Rear-facing', items: ['5-50 lbs', 'Under 49 in'] },
        { label: 'Forward-facing', items: ['30-65 lbs'] },
        { label: 'Dimensions', items: ['20.5 x 17 x 23.5 in'] },
      ],
      notes: ['Slim profile.', 'Great for smaller vehicles.'],
      ctaLabel: 'View Poplar S',
      standout: 'Smaller-car convertible',
      pros: ['Compact footprint', 'Easier fit in smaller vehicles', 'Clear installed-seat logic'],
    },
    {
      name: 'Clek Foonf',
      brand: 'Clek',
      productName: 'Foonf',
      imageAlt: 'Clek Foonf convertible car seat.',
      typeLabel: 'Convertible',
      bestFor: 'extended rear-facing plus durability',
      shortReview:
        'A good comparison point because it reminds parents that convertible is a broad category, and some seats lean heavily into durability and long-run substance.',
      specGroups: [
        { label: 'Rear-facing', items: ['14-50 lbs', '24-43 in'] },
        { label: 'Forward-facing', items: ['22-65 lbs', '30-49 in'] },
        { label: 'Weight', items: ['33 lbs'] },
      ],
      notes: ['Tank-level build quality.', 'Heavy, but extremely durable.'],
      ctaLabel: 'View Clek Foonf',
      standout: 'Durability-first convertible',
      pros: ['Extended rear-facing', 'Extremely durable build', 'Strong long-run seat'],
    },
    {
      name: 'Nuna REVV',
      brand: 'Nuna',
      productName: 'REVV',
      imageAlt: 'Nuna REVV rotating convertible car seat.',
      typeLabel: 'Rotating Convertible',
      bestFor: 'daily convenience plus rotation',
      shortReview:
        'Useful because it keeps the rotating conversation grounded inside the convertible lane, where the swivel feature is meant to make daily loading feel easier.',
      specGroups: [
        { label: 'Rear-facing', items: ['5-40 lbs', '18-43 in'] },
        { label: 'Forward-facing', items: ['30-65 lbs', '34-49 in'] },
        { label: 'Weight', items: ['30.6 lbs'] },
      ],
      notes: ['360-degree rotation.', 'Easier loading for everyday use.'],
      ctaLabel: 'View Nuna REVV',
      standout: 'Convertible with rotation',
      pros: ['360-degree swivel', 'Daily loading convenience', 'Primary-car fit'],
    },
    {
      name: 'Maxi-Cosi Romi',
      brand: 'Maxi-Cosi',
      productName: 'Romi',
      imageAlt: 'Maxi-Cosi Romi travel-friendly convertible car seat.',
      typeLabel: 'Convertible (Travel-Friendly)',
      bestFor: 'lighter weight plus travel use',
      shortReview:
        'Helpful because it shows that some convertibles are solving a very different problem: portability, travel, and easier movement between places.',
      specGroups: [
        { label: 'Rear-facing', items: ['5-40 lbs', '19-40 in'] },
        { label: 'Forward-facing', items: ['30-50 lbs', '34.4-44 in'] },
        { label: 'Weight', items: ['Around 9 lbs'] },
      ],
      notes: ['Extremely lightweight.', 'Airplane-friendly.'],
      ctaLabel: 'View Maxi-Cosi Romi',
      standout: 'Travel-friendly convertible',
      pros: ['Very light weight', 'Travel-ready design', 'Useful backup or secondary seat'],
    },
  ],
  allInOne: [
    {
      name: 'CYBEX Callisto',
      brand: 'CYBEX',
      productName: 'Callisto',
      imageAlt: 'CYBEX Callisto all-in-one car seat.',
      typeLabel: 'All-in-One',
      bestFor: 'full lifespan coverage',
      shortReview:
        'A strong all-in-one example because it makes the broad lifecycle promise of the category easy to see without pretending that one seat solves every stage in exactly the same way.',
      specGroups: [
        { label: 'Rear-facing', items: ['4-40 lbs', 'Up to 43.3 in'] },
        { label: 'Forward-facing', items: ['26.5-65 lbs', 'Up to 49.2 in'] },
        { label: 'Booster', items: ['40-120 lbs', 'Up to 57 in'] },
        { label: 'Weight', items: ['35 lbs'] },
      ],
      notes: ['Full lifecycle seat.', 'No need to upgrade right away.'],
      ctaLabel: 'View CYBEX Callisto',
      standout: 'Long lifecycle coverage',
      pros: ['Rear-facing to booster', 'Long-run coverage', 'Strong planning-ahead fit'],
    },
    {
      name: 'Nuna EXEC',
      brand: 'Nuna',
      productName: 'EXEC',
      imageAlt: 'Nuna EXEC all-in-one car seat.',
      typeLabel: 'All-in-One',
      bestFor: 'a luxury long-term solution',
      shortReview:
        'Useful here because it represents the all-in-one lane at its most premium: one larger seat built for parents planning farther down the road.',
      specGroups: [
        { label: 'Rear-facing', items: ['5-50 lbs'] },
        { label: 'Forward-facing', items: ['30-65 lbs'] },
        { label: 'Booster', items: ['40-110 lbs'] },
      ],
      notes: ['Premium materials.', 'Built to grow with your child.'],
      ctaLabel: 'View Nuna EXEC',
      standout: 'Luxury long-run seat',
      pros: ['Premium materials', 'Multi-stage coverage', 'Long-view planning fit'],
    },
    {
      name: 'Britax One4Life',
      brand: 'Britax',
      productName: 'One4Life',
      imageAlt: 'Britax One4Life all-in-one car seat.',
      typeLabel: 'All-in-One',
      bestFor: 'extended usability plus long-term value',
      shortReview:
        'Helpful because it shows what many parents are actually after in the all-in-one lane: a broad runway and a longer-term value story.',
      specGroups: [
        { label: 'Rear-facing', items: ['5-50 lbs'] },
        { label: 'Forward-facing', items: ['30-65 lbs'] },
        { label: 'Booster', items: ['40-120 lbs'] },
      ],
      notes: ['Wide range.', 'Feels like a long-term investment.'],
      ctaLabel: 'View One4Life',
      standout: 'Broad stage range',
      pros: ['Long usable range', 'Strong value over time', 'Clear all-in-one purpose'],
    },
  ],
  travelLightweight: [
    {
      name: 'WAYB Pico',
      brand: 'WAYB',
      productName: 'Pico',
      imageAlt: 'WAYB Pico travel car seat.',
      typeLabel: 'Travel Car Seat',
      bestFor: 'flying plus genuine portability',
      shortReview:
        'A useful travel anchor because it makes the specialty-seat question very clear: this is about portability first, not pretending every travel seat should replace the main seat at home.',
      specGroups: [
        { label: 'Weight', items: ['8 lbs'] },
        { label: 'Dimensions', items: ['Compact fold for overhead bins'] },
      ],
      notes: ['Ultra-light.', 'Ideal for travel-only use.'],
      ctaLabel: 'View WAYB Pico',
      standout: 'Travel-first seat',
      pros: ['Very light', 'Compact fold', 'Strong fit for flights and occasional travel'],
    },
  ],
  booster: [
    {
      name: 'Clek Oobr',
      brand: 'Clek',
      productName: 'Oobr',
      imageAlt: 'Clek Oobr high-back booster seat.',
      typeLabel: 'High-Back Booster',
      bestFor: 'a high-back booster with a safety-first build',
      shortReview:
        'A strong booster anchor because it keeps the later-stage conversation serious: belt positioning, structure, and everyday usability still matter here.',
      specGroups: [
        { label: 'Usage', items: ['40-100 lbs', '40-57 in'] },
        { label: 'Weight', items: ['20 lbs', '10 lbs backless'] },
      ],
      notes: ['Rigid LATCH booster.', 'Strong safety-minded design.'],
      ctaLabel: 'View Clek Oobr',
      standout: 'Safety-minded booster',
      pros: ['Rigid LATCH option', 'Strong build', 'Clear later-stage fit'],
    },
    {
      name: 'UPPAbaby Alta',
      brand: 'UPPAbaby',
      productName: 'Alta',
      imageAlt: 'UPPAbaby Alta high-back booster seat.',
      typeLabel: 'High-Back Booster',
      bestFor: 'premium finish plus adjustable comfort',
      shortReview:
        'Useful because it shows that booster shopping is still real shopping. Comfort, adjustability, and fit still shape whether the seat works well every day.',
      specGroups: [
        { label: 'Dimensions', items: ['20"L x 17.5"W x 25.5-33"H'] },
        { label: 'Weight', items: ['17.1 lbs'] },
      ],
      notes: ['Premium look and feel.', 'Comfortable and adjustable.'],
      ctaLabel: 'View UPPAbaby Alta',
      standout: 'Comfortable premium booster',
      pros: ['Adjustable fit', 'Comfort-focused design', 'Later-stage ease'],
    },
  ],
  rotating: [
    {
      name: 'CYBEX Aton Swivel',
      brand: 'CYBEX',
      productName: 'Aton Swivel',
      imageAlt: 'CYBEX Aton Swivel rotating infant car seat.',
      typeLabel: 'Rotating Infant Car Seat',
      bestFor: 'rotation during the infant stage',
      shortReview:
        'Important because it keeps rotating seats separated by stage. This is the infant example, not a signal that every swivel seat solves the same job.',
      specGroups: [
        { label: 'Usage', items: ['4-30 lbs', 'Up to 30 in'] },
        { label: 'Weight', items: ['9 lbs'] },
        { label: 'Dimensions', items: ['26.1"L x 17.5"W x 14.7"H'] },
      ],
      notes: ['Swivel functionality simplifies loading.'],
      ctaLabel: 'View CYBEX Aton Swivel',
      standout: 'Rotating infant lane',
      pros: ['Infant-stage rotation', 'Easier loading', 'Clear stage-specific use case'],
    },
    {
      name: 'Nuna REVV',
      brand: 'Nuna',
      productName: 'REVV',
      imageAlt: 'Nuna REVV rotating convertible car seat.',
      typeLabel: 'Rotating Convertible',
      bestFor: 'rotation inside the convertible lane',
      shortReview:
        'A clear rotating convertible example because it shows the swivel feature doing its real job: easier loading in a primary vehicle you use all the time.',
      specGroups: [
        { label: 'Rear-facing', items: ['5-40 lbs', '18-43 in'] },
        { label: 'Forward-facing', items: ['30-65 lbs', '34-49 in'] },
        { label: 'Weight', items: ['30.6 lbs'] },
      ],
      notes: ['360-degree rotation.', 'Easier loading for everyday use.'],
      ctaLabel: 'View Nuna REVV',
      standout: 'Rotating convertible lane',
      pros: ['Swivel convenience', 'Primary-car fit', 'Daily-use benefit'],
    },
    {
      name: 'CYBEX Callisto',
      brand: 'CYBEX',
      productName: 'Callisto',
      imageAlt: 'CYBEX Callisto rotating all-in-one car seat.',
      typeLabel: 'Rotating All-in-One',
      bestFor: 'rotation inside a longer-run all-in-one path',
      shortReview:
        'Helpful because it rounds out the rotating conversation with the all-in-one lane, where the swivel feature sits inside a much longer planning horizon.',
      specGroups: [
        { label: 'Rear-facing', items: ['4-40 lbs', 'Up to 43.3 in'] },
        { label: 'Forward-facing', items: ['26.5-65 lbs', 'Up to 49.2 in'] },
        { label: 'Booster', items: ['40-120 lbs', 'Up to 57 in'] },
        { label: 'Weight', items: ['35 lbs'] },
      ],
      notes: ['Full lifecycle seat.', 'Longer-run rotating option.'],
      ctaLabel: 'View CYBEX Callisto',
      standout: 'Rotating all-in-one lane',
      pros: ['Multi-stage swivel option', 'Longer-run coverage', 'Stage-first rotating comparison'],
    },
  ],
} as const satisfies Record<string, GuideProductExampleData[]>;

export const CAR_SEAT_SEQUENCE_NOTE = {
  title: 'The TMBC way to think about car seats',
  intro: 'Not every seat is meant to do everything.',
  sequence: [
    '1 infant seat',
    '1 convertible or all-in-one',
    '1 travel or backup seat if your routine actually calls for it',
  ],
  closing: [
    "The goal isn't to buy more.",
    'It is to choose the right sequence.',
    "Because the best setup isn't about specs. It is about how the seat fits your real life.",
  ],
  ctaLabel: 'Explore the Car Seat Guide',
} as const;
