import type { GuideCardItem } from '@/lib/guides/presentation';
import { getGuidePath } from '@/lib/guides/routing';

export const REGISTRY_SUBGUIDE_PATHS = {
  minimalist: '/guides/registry/minimalist',
  essentials: '/guides/registry/essentials',
  mistakes: '/guides/registry/mistakes',
  'where-to-register': '/guides/registry/where-to-register',
  timeline: '/guides/registry/timeline',
  perks: '/guides/registry/perks',
} as const;

export type RegistrySubGuideSlug = keyof typeof REGISTRY_SUBGUIDE_PATHS;

type RegistrySubGuideGridItem = {
  slug: RegistrySubGuideSlug;
  title: string;
  description: string;
  laneLabel: string;
  icon: 'strategy' | 'checklist' | 'shield' | 'bag' | 'calendar' | 'book';
};

export type RegistrySubGuidePageData = {
  slug: RegistrySubGuideSlug;
  path: (typeof REGISTRY_SUBGUIDE_PATHS)[RegistrySubGuideSlug];
  title: string;
  description: string;
  seoTitle: string;
  seoDescription: string;
  content: string;
  nextStepCtaHref: string;
  nextStepCtaLabel: string;
};

export const REGISTRY_SUBGUIDE_GRID_ITEMS: RegistrySubGuideGridItem[] = [
  {
    slug: 'minimalist',
    title: 'Minimalist Registry',
    description:
      'For parents who want fewer items, clearer priorities, and a registry built around what actually gets used.',
    laneLabel: 'APPROACH',
    icon: 'strategy',
  },
  {
    slug: 'essentials',
    title: 'What to Register For First',
    description:
      'The foundation items that support sleep, feeding, diapering, and daily life before adding anything extra.',
    laneLabel: 'START',
    icon: 'checklist',
  },
  {
    slug: 'mistakes',
    title: 'Registry Mistakes to Avoid',
    description:
      'Common decisions that lead to overbuying, duplication, and items that do not fit your real routine.',
    laneLabel: 'AVOID',
    icon: 'shield',
  },
  {
    slug: 'where-to-register',
    title: 'Where to Register & Why',
    description:
      'How to choose between Target, Amazon, Babylist, and others based on perks, flexibility, and returns.',
    laneLabel: 'SETUP',
    icon: 'bag',
  },
  {
    slug: 'timeline',
    title: 'When to Buy What',
    description:
      'What to purchase early, what to delay, and how to time your registry decisions.',
    laneLabel: 'TIMING',
    icon: 'calendar',
  },
  {
    slug: 'perks',
    title: 'Free Registry Perks & Welcome Boxes',
    description:
      'What each retailer offers, how to qualify, and how to maximize free items and incentives.',
    laneLabel: 'BONUS',
    icon: 'book',
  },
];

const DEFAULT_GUIDE_IMAGE = '/assets/hero/hero-baby-editorial.jpg';

const REGISTRY_NEXT_STEP_GUIDES: GuideCardItem[] = [
  {
    slug: 'minimalist-baby-registry',
    href: getGuidePath({ slug: 'minimalist-baby-registry' }),
    title: 'Registry Hub',
    description: 'Return to the full registry decision hub.',
    imageSrc: DEFAULT_GUIDE_IMAGE,
    imageAlt: 'Taylor-Made Baby Co. registry planning hub.',
    eyebrow: 'Registry Planning',
  },
  {
    slug: 'best-strollers',
    href: getGuidePath({ slug: 'best-strollers' }),
    title: 'Stroller Guide',
    description: 'Use this once you are ready to narrow stroller tradeoffs.',
    imageSrc: DEFAULT_GUIDE_IMAGE,
    imageAlt: 'Taylor-Made Baby Co. stroller guide.',
    eyebrow: 'Strollers',
  },
  {
    slug: 'best-infant-car-seats',
    href: getGuidePath({ slug: 'best-infant-car-seats' }),
    title: 'Car Seat Guide',
    description: 'Use this when you are ready to sort infant and convertible seat fit.',
    imageSrc: DEFAULT_GUIDE_IMAGE,
    imageAlt: 'Taylor-Made Baby Co. car seat guide.',
    eyebrow: 'Car Seats',
  },
  {
    slug: 'nursery-setup-guide',
    href: getGuidePath({ slug: 'nursery-setup-guide' }),
    title: 'Nursery Guide',
    description: 'Use this when the room plan starts affecting the registry list.',
    imageSrc: DEFAULT_GUIDE_IMAGE,
    imageAlt: 'Taylor-Made Baby Co. nursery guide.',
    eyebrow: 'Nursery Planning',
  },
];

function buildNextStepsSection() {
  return [
    '## Next Steps',
    '',
    '- [Return to the Registry Hub](/guides/registry)',
    '- [Compare stroller options](/guides/strollers)',
    '- [Compare car seat options](/guides/car-seats)',
    '- [Plan the nursery setup](/guides/nursery)',
  ].join('\n');
}

const REGISTRY_SUBGUIDE_PAGES: Record<RegistrySubGuideSlug, RegistrySubGuidePageData> = {
  minimalist: {
    slug: 'minimalist',
    path: REGISTRY_SUBGUIDE_PATHS.minimalist,
    title: 'Minimalist Baby Registry',
    description: 'Build a tighter registry around daily use, space, and what you can decide with confidence now.',
    seoTitle: 'Minimalist Baby Registry | Taylor-Made Baby Co.',
    seoDescription:
      'A structured guide to building a smaller, smarter baby registry around daily use, space, and clear priorities.',
    nextStepCtaHref: '/guides/registry',
    nextStepCtaLabel: 'Return to the Registry Hub',
    content: [
      'A minimalist registry is a filtering method.',
      '',
      'Keep the list focused on what supports daily life in the first stretch. Delay specialty items until you know you need them.',
      '',
      '## Use this approach if',
      '- You want a shorter list that still covers the basics.',
      '- You have limited storage, budget, or patience for duplicates.',
      '- You prefer to add items later based on real use.',
      '',
      '## Keep on the first-pass registry',
      '- A safe sleep space.',
      '- A basic feeding setup.',
      '- Diapering supplies for the first weeks.',
      '- Everyday clothing in a small range of sizes.',
      '- One simple travel setup, not multiple versions of the same function.',
      '',
      '## Delay until after baby arrives',
      '- Extra bottle systems before you know feeding preference.',
      '- Large toy collections.',
      '- Specialty soothing gear with one narrow use case.',
      '- Backup versions of products you have not tested yet.',
      '',
      '## Skip unless you have a clear reason',
      '- Multiple swings, loungers, or containers.',
      '- Decor-first items that do not improve function.',
      '- Large quantities of one diaper or wipe brand before fit testing.',
      '- Category duplicates added only because they are popular online.',
      '',
      '## Quick filter for every item',
      '- Does this solve a real daily task?',
      '- Does it fit the space you actually have?',
      '- Would you still buy it yourself if nobody gifted it?',
      '- Can this wait until after birth without creating a problem?',
      '',
      '## A simple registry rule',
      '- Put must-have items on the main list.',
      '- Move maybe-later items to a private shopping note.',
      '- Revisit the note during the completion discount window.',
      '',
      buildNextStepsSection(),
    ].join('\n'),
  },
  essentials: {
    slug: 'essentials',
    path: REGISTRY_SUBGUIDE_PATHS.essentials,
    title: 'What to Register For First',
    description: 'Start with the categories that support sleep, feeding, diapering, and basic daily setup.',
    seoTitle: 'What to Register For First | Taylor-Made Baby Co.',
    seoDescription:
      'A structured first-pass baby registry guide covering sleep, feeding, diapering, and everyday setup before extras.',
    nextStepCtaHref: '/guides/registry',
    nextStepCtaLabel: 'Return to the Registry Hub',
    content: [
      'Build the first pass around function, not variety.',
      '',
      'Register for the items that let you handle sleep, feeding, diapering, and basic movement before adding convenience extras.',
      '',
      '## Start with these categories',
      '- Sleep',
      '- Feeding',
      '- Diapering',
      '- Clothing and linens',
      '- Daily movement and carrying',
      '',
      '## Sleep basics first',
      '- One primary sleep space.',
      '- Fitted sheets sized for that sleep space.',
      '- Swaddles or sleep sacks in a small first batch.',
      '- Monitor only if it matches the room setup and your comfort level.',
      '',
      '## Feeding basics first',
      '- A small starter bottle set if you plan to bottle feed or combo feed.',
      '- Burp cloths and bibs.',
      '- Breast pump and support items if relevant to your plan.',
      '- Do not register for large quantities of one bottle style before testing.',
      '',
      '## Diapering basics first',
      '- Newborn and size-one diapers in modest quantities.',
      '- Wipes.',
      '- Diaper cream.',
      '- One realistic changing setup with storage nearby.',
      '',
      '## Daily life basics',
      '- Zip sleepers and simple layers.',
      '- Laundry support.',
      '- One diaper bag setup.',
      '- A safe place to put baby down in the rooms you use most.',
      '',
      '## Hold for round two',
      '- Specialty feeding accessories.',
      '- Large toy sets.',
      '- Category backups.',
      '- Optional gear tied to a routine you have not lived yet.',
      '',
      buildNextStepsSection(),
    ].join('\n'),
  },
  mistakes: {
    slug: 'mistakes',
    path: REGISTRY_SUBGUIDE_PATHS.mistakes,
    title: 'Registry Mistakes to Avoid',
    description: 'Avoid the decisions that make a registry longer, less useful, and harder to shop from.',
    seoTitle: 'Registry Mistakes to Avoid | Taylor-Made Baby Co.',
    seoDescription:
      'A clear list of baby registry mistakes that lead to overbuying, duplication, and a list that does not match real life.',
    nextStepCtaHref: '/guides/registry',
    nextStepCtaLabel: 'Return to the Registry Hub',
    content: [
      'Most registry problems are structure problems.',
      '',
      'The list gets too long when every category is treated as urgent. Fix the order first and the list usually gets cleaner.',
      '',
      '## Common mistakes',
      '- Registering by brand hype instead of by daily task.',
      '- Adding multiple products that solve the same problem.',
      '- Registering for too many newborn-size consumables.',
      '- Choosing major gear before the room plan and routine are clear.',
      '- Building a public list before deciding what you will buy yourself.',
      '',
      '## Duplication risks',
      '- Bottles from several systems.',
      '- Multiple container seats.',
      '- Too many blankets and swaddles in the same size.',
      '- More clothing than your laundry rhythm can support.',
      '',
      '## Retailer setup mistakes',
      '- Spreading the public registry across too many links.',
      '- Ignoring return policy differences.',
      '- Missing welcome-box or completion-discount steps.',
      '- Adding items from other stores without checking shipping or return friction.',
      '',
      '## Better rules to use instead',
      '- One item per function until you have a reason to add another.',
      '- Separate must-have, nice-to-have, and buy-later items.',
      '- Keep big-ticket items on a shortlist until you compare fit, space, and budget.',
      '- Review the list once for duplicates before sharing it.',
      '',
      '## Quick reset if the registry already feels messy',
      '- Remove anything you cannot explain in one sentence.',
      '- Cut duplicate categories first.',
      '- Move uncertain items to a private note.',
      '- Rebuild the public list around the first eight weeks, not the whole first year.',
      '',
      buildNextStepsSection(),
    ].join('\n'),
  },
  'where-to-register': {
    slug: 'where-to-register',
    path: REGISTRY_SUBGUIDE_PATHS['where-to-register'],
    title: 'Where to Register & Why',
    description: 'Choose a registry based on returns, convenience, perks, and how your gift givers actually shop.',
    seoTitle: 'Where to Register for a Baby Registry | Taylor-Made Baby Co.',
    seoDescription:
      'Compare Target, Amazon, and Babylist by completion discounts, welcome boxes, returns, and setup logic.',
    nextStepCtaHref: '/guides/strollers',
    nextStepCtaLabel: 'Continue to the Stroller Guide',
    content: [
      'Choose a registry for the shopping experience it creates, not just the logo on the page.',
      '',
      'For most families, the right answer depends on return convenience, online flexibility, and whether your gift givers prefer in-store shopping.',
      '',
      '## Quick recommendation',
      '- Choose Target if store access, easy returns, and in-person shoppers matter most.',
      '- Choose Amazon if selection, fast shipping, and Prime benefits matter most.',
      '- Choose Babylist if you want one list that can pull from multiple retailers.',
      '',
      '## Target',
      '- Completion discount: 15% completion coupon.',
      '- Welcome perks: free welcome kit with over $100 in samples and Target Circle bonuses.',
      '- Return strength: registry items can generally be returned for up to one year after the event date if they are new and unopened.',
      '- In-store advantage: strongest in-store support, easy store returns, and gift givers can shop locally.',
      '- Best fit: families who want one straightforward registry with strong store access.',
      '',
      '## Amazon',
      '- Completion discount: up to 15% for Prime members, multi-use during the eligibility window, max savings of $300.',
      '- Welcome perks: free Welcome Box after Prime enrollment, 10 unique registry items, a $10 registry purchase, and a box request.',
      '- Return strength: eligible registry gifts have free 365-day returns.',
      '- Online advantage: widest selection and the easiest option for online-first gift givers.',
      '- Best fit: families already deep in the Amazon and Prime ecosystem.',
      '',
      '## Babylist',
      '- Completion discount: 15% on eligible Babylist Shop purchases once the registry is 30 days old.',
      '- Timing: Babylist says the discount opens 60 days before the due date and stays active for 90 days after.',
      '- Welcome perks: Hello Baby Box requires three items from other stores, 40% checklist completion, a $30 Babylist Shop purchase, and paid shipping.',
      '- Return strength: Babylist Shop items can be returned within 9 months; items bought from other retailers follow that retailer\'s return policy.',
      '- Flexibility advantage: strongest option if you want one list that can mix retailers and specialty brands.',
      '',
      '## How the major registries compare',
      '- Completion discounts are usually around 15% across major registry programs, but exclusions and timing differ.',
      '- Welcome kits are useful for samples and coupons, not for covering major needs.',
      '- Target is the strongest in-store option.',
      '- Amazon is the strongest online-only option.',
      '- Babylist is the strongest universal-registry option.',
      '',
      '## Best setup for most parents',
      '- Use one primary public registry.',
      '- Pick the retailer that matches how your gift givers actually shop.',
      '- Open additional registries only if you have a clear perk or discount reason.',
      '- If you do use multiple registries, track them in one place so duplicates do not slip through.',
      '',
      buildNextStepsSection(),
    ].join('\n'),
  },
  timeline: {
    slug: 'timeline',
    path: REGISTRY_SUBGUIDE_PATHS.timeline,
    title: 'When to Buy What',
    description: 'Use timing to reduce rushed purchases and keep the biggest decisions in the right order.',
    seoTitle: 'When to Buy What for a Baby Registry | Taylor-Made Baby Co.',
    seoDescription:
      'A structured registry timeline covering nursery-first planning, large-purchase timing, completion discounts, and what to delay.',
    nextStepCtaHref: '/guides/registry/where-to-register',
    nextStepCtaLabel: 'Compare Registry Retailers',
    content: [
      'Timing matters because some categories create pressure earlier than others.',
      '',
      'Start with the room plan and the daily basics. Move gear and optional categories later, once your routine is clearer.',
      '',
      '## Buy or decide first',
      '- Nursery and sleep setup.',
      '- Core storage and changing setup.',
      '- Basic feeding plan.',
      '- The infant car seat you need before birth.',
      '',
      '## Nursery first',
      '- Furniture and room layout often have the longest lead times.',
      '- The room plan affects what actually fits on the registry.',
      '- A clear nursery setup makes it easier to decide what you do not need elsewhere.',
      '',
      '## Large purchase timing',
      '- Shortlist big-ticket items early enough to compare them calmly.',
      '- Buy the truly essential ones in time for delivery, assembly, and returns.',
      '- Leave optional upgrades and duplicate-use gear for later if the first-pass setup already works.',
      '',
      '## Do not rush stroller and car seat decisions too early',
      '- Move stroller comparison later in the planning order, after nursery and daily-life basics.',
      '- Finalize the infant car seat before birth, but do not let it take over the registry before the foundational categories are set.',
      '- Hold secondary gear decisions until you know your car, storage, and routine constraints.',
      '',
      '## Completion discount window',
      '- Save non-urgent big-ticket items for the completion phase when possible.',
      '- Babylist says its registry discount opens 60 days before the due date and stays active for 90 days after.',
      '- Other major registries also use late-stage discount windows, so review timing in each dashboard before you buy.',
      '',
      '## Good items to delay',
      '- Extra bottles before testing one system.',
      '- Extra swaddles and extra-size clothing.',
      '- Secondary stroller accessories.',
      '- Nice-to-have soothing products and decor.',
      '',
      buildNextStepsSection(),
    ].join('\n'),
  },
  perks: {
    slug: 'perks',
    path: REGISTRY_SUBGUIDE_PATHS.perks,
    title: 'Free Registry Perks & Welcome Boxes',
    description: 'Use the perks without letting them dictate the whole registry strategy.',
    seoTitle: 'Free Registry Perks & Welcome Boxes | Taylor-Made Baby Co.',
    seoDescription:
      'A structured guide to registry welcome boxes, completion discounts, qualification rules, and perk-stacking strategy.',
    nextStepCtaHref: '/guides/registry/where-to-register',
    nextStepCtaLabel: 'Compare Registry Retailers',
    content: [
      'Registry perks are useful when they support a plan you already trust.',
      '',
      'Use the boxes, discounts, and samples to save money on planned purchases. Do not build the whole registry around freebies.',
      '',
      '## The main perks to track',
      '- Welcome boxes or welcome kits.',
      '- Completion discounts.',
      '- Coupons and samples.',
      '- Milestone offers or registry-only deals.',
      '',
      '## Welcome boxes and kits',
      '### Target',
      '- Target advertises a free welcome kit with over $100 in samples and bonuses for registry users.',
      '- Best use: samples, coupons, and small trial items.',
      '- Watchout: terms can change, so confirm current dashboard requirements before counting on it.',
      '',
      '### Amazon',
      '- Amazon says the Welcome Box is free after Prime enrollment, 10 unique registry items, a $10 registry purchase, and a box request.',
      '- Best use: samples plus a simple way to capture Prime-specific registry perks.',
      '- Watchout: Prime membership is part of the qualification logic.',
      '',
      '### Babylist',
      '- Babylist says the Hello Baby Box requires three items from other stores, 40% checklist completion, a $30 Babylist Shop purchase, and paid shipping.',
      '- Best use: test samples and coupons while also unlocking the universal-registry setup.',
      '- Watchout: the purchase must be in the Babylist Shop, not another linked retailer.',
      '',
      '## Completion discounts',
      '- Major registry discounts usually land around 10% to 15%.',
      '- Target shows a 15% completion coupon.',
      '- Amazon shows up to 15% for Prime members, with a maximum savings cap.',
      '- Babylist shows 15% on eligible Babylist Shop purchases once the registry is 30 days old.',
      '- Save big-ticket items and non-urgent add-ons for this phase when possible.',
      '',
      '## Stacking the perks without creating duplicate chaos',
      '- Keep one registry as the main public list.',
      '- Use additional registries only if the perks are worth the tracking work.',
      '- If you open multiple registries, track what is public, what is private, and where each item lives.',
      '- Do not list the same item in multiple public places unless you want cleanup work later.',
      '',
      '## Samples and coupons',
      '- Samples are most useful for bottles, pacifiers, diapers, wipes, and postpartum basics.',
      '- Coupons matter most if they line up with products you already plan to buy.',
      '- Treat free samples as testing tools, not as proof that a category belongs on your registry.',
      '',
      '## Combining discounts with sales and rewards',
      '- Check each retailer\'s terms before assuming discounts stack.',
      '- Babylist says its registry discount can combine with Babylist gift cards or store credits, but not with other promotions.',
      '- Use price drops, rewards, and gift cards strategically, but confirm exclusions before checkout.',
      '',
      buildNextStepsSection(),
    ].join('\n'),
  },
};

export function getRegistrySubGuideGridItems() {
  return REGISTRY_SUBGUIDE_GRID_ITEMS.map((item) => ({
    ...item,
    path: REGISTRY_SUBGUIDE_PATHS[item.slug],
  }));
}

export function getRegistrySubGuideSlugs() {
  return Object.keys(REGISTRY_SUBGUIDE_PAGES) as RegistrySubGuideSlug[];
}

export function getRegistrySubGuideBySlug(slug: string) {
  return REGISTRY_SUBGUIDE_PAGES[slug as RegistrySubGuideSlug] ?? null;
}

export function getRegistrySubGuideRelatedGuides() {
  return REGISTRY_NEXT_STEP_GUIDES;
}
