import type { GuideHubIconKey } from '@/lib/guides/hubs';

export type TravelSystemEntityType = 'stroller' | 'carSeat';
export type TravelSystemConnectionType = 'direct' | 'includedAdapter' | 'adapterRequired';

export type StrollerCategory =
  | 'full-size'
  | 'full-size-non-modular'
  | 'compact'
  | 'travel'
  | 'convertible-modular'
  | 'convertible-non-modular'
  | 'double'
  | 'double-travel'
  | 'double-jogging'
  | 'jogging'
  | 'wagon'
  | 'umbrella';

export const STROLLER_CATEGORY_LABELS: Record<StrollerCategory, string> = {
  'full-size': 'Full Size / Modular',
  'full-size-non-modular': 'Full Size (Non-Modular)',
  'compact': 'Compact / Mid-Size',
  'travel': 'Travel',
  'convertible-modular': 'Single-to-Double (Modular)',
  'convertible-non-modular': 'Single-to-Double (Non-Modular)',
  'double': 'Double',
  'double-travel': 'Double Travel',
  'double-jogging': 'Double Jogger',
  'jogging': 'Jogging / All-Terrain',
  'wagon': 'Wagon',
  'umbrella': 'Umbrella',
};

export type TravelSystemEntity = {
  id: string;
  type: TravelSystemEntityType;
  brand: string;
  label: string;
  shortLabel: string;
  description: string;
  icon: GuideHubIconKey;
  aliases: string[];
  strollerCategory?: StrollerCategory;
};

type TravelSystemCompatibilityPair = {
  strollerId: string;
  carSeatId: string;
  connection: TravelSystemConnectionType;
  note: string;
  sourceLabel: string;
  sourceUrl: string;
};

export type TravelSystemResult = {
  id: string;
  stroller: TravelSystemEntity;
  carSeat: TravelSystemEntity;
  counterpart: TravelSystemEntity;
  connection: TravelSystemConnectionType;
  connectionLabel: string;
  note: string;
  sourceLabel: string;
  sourceUrl: string;
};

export const TRAVEL_SYSTEM_ENTITIES: TravelSystemEntity[] = [
  {
    id: 'bugaboo-fox-5',
    type: 'stroller',
    brand: 'Bugaboo',
    label: 'Bugaboo Fox 5',
    shortLabel: 'Fox 5',
    description: 'Full-size everyday stroller',
    icon: 'stroller',
    strollerCategory: 'full-size',
    aliases: ['fox 5', 'fox5', 'bugaboo fox', 'bugaboo fox 5'],
  },
  {
    id: 'bugaboo-butterfly',
    type: 'stroller',
    brand: 'Bugaboo',
    label: 'Bugaboo Butterfly',
    shortLabel: 'Butterfly',
    description: 'Travel stroller',
    icon: 'plane',
    strollerCategory: 'travel',
    aliases: ['butterfly', 'bugaboo butterfly'],
  },
  {
    id: 'bugaboo-donkey-6',
    type: 'stroller',
    brand: 'Bugaboo',
    label: 'Bugaboo Donkey 6',
    shortLabel: 'Donkey 6',
    description: 'Modular single-to-double convertible',
    icon: 'convertible',
    strollerCategory: 'convertible-modular',
    aliases: ['donkey', 'donkey 5', 'donkey 6', 'bugaboo donkey', 'bugaboo donkey 5', 'bugaboo donkey 6'],
  },
  {
    id: 'nuna-mixx-next',
    type: 'stroller',
    brand: 'Nuna',
    label: 'Nuna MIXX next',
    shortLabel: 'MIXX next',
    description: 'Full-size modular stroller',
    icon: 'stroller',
    strollerCategory: 'full-size',
    aliases: ['mixx', 'mixx next', 'nuna mixx', 'nuna mixx next'],
  },
  {
    id: 'nuna-trvl-lx',
    type: 'stroller',
    brand: 'Nuna',
    label: 'Nuna TRVL lx',
    shortLabel: 'TRVL lx',
    description: 'Travel stroller',
    icon: 'plane',
    strollerCategory: 'travel',
    aliases: ['trvl', 'trvl lx', 'nuna trvl', 'nuna trvl lx'],
  },
  {
    id: 'uppababy-cruz-v2',
    type: 'stroller',
    brand: 'UPPAbaby',
    label: 'UPPAbaby Cruz V2',
    shortLabel: 'Cruz V2',
    description: 'Full-size modular stroller',
    icon: 'stroller',
    strollerCategory: 'full-size',
    aliases: ['cruz', 'cruz v2', 'uppababy cruz', 'uppababy cruz v2'],
  },
  {
    id: 'uppababy-vista-v2',
    type: 'stroller',
    brand: 'UPPAbaby',
    label: 'UPPAbaby Vista V2',
    shortLabel: 'Vista V2',
    description: 'Single-to-double stroller (non-modular)',
    icon: 'convertible',
    strollerCategory: 'convertible-non-modular',
    aliases: ['vista', 'vista v2', 'uppababy vista', 'uppababy vista v2'],
  },
  {
    id: 'uppababy-minu-v2',
    type: 'stroller',
    brand: 'UPPAbaby',
    label: 'UPPAbaby Minu V2',
    shortLabel: 'Minu V2',
    description: 'Travel stroller',
    icon: 'plane',
    strollerCategory: 'travel',
    aliases: ['minu', 'minu v2', 'uppababy minu', 'uppababy minu v2'],
  },
  {
    id: 'cybex-balios-s-lux',
    type: 'stroller',
    brand: 'CYBEX',
    label: 'CYBEX Balios S Lux',
    shortLabel: 'Balios S Lux',
    description: 'Full-size modular stroller',
    icon: 'stroller',
    strollerCategory: 'full-size',
    aliases: ['balios', 'balios s lux', 'cybex balios', 'cybex balios s lux'],
  },
  {
    id: 'cybex-gazelle-s',
    type: 'stroller',
    brand: 'CYBEX',
    label: 'CYBEX Gazelle S',
    shortLabel: 'Gazelle S',
    description: 'Modular single-to-double convertible',
    icon: 'convertible',
    strollerCategory: 'convertible-modular',
    aliases: ['gazelle', 'gazelle s', 'cybex gazelle', 'cybex gazelle s'],
  },
  {
    id: 'cybex-libelle',
    type: 'stroller',
    brand: 'CYBEX',
    label: 'CYBEX Libelle',
    shortLabel: 'Libelle',
    description: 'Ultra-compact travel stroller',
    icon: 'plane',
    strollerCategory: 'travel',
    aliases: ['libelle', 'cybex libelle'],
  },
  {
    id: 'silver-cross-reef-2',
    type: 'stroller',
    brand: 'Silver Cross',
    label: 'Silver Cross Reef 2',
    shortLabel: 'Reef 2',
    description: 'Full-size modular stroller',
    icon: 'stroller',
    strollerCategory: 'full-size',
    aliases: ['reef', 'reef 2', 'silver cross reef', 'silver cross reef 2'],
  },
  {
    id: 'silver-cross-wave-3',
    type: 'stroller',
    brand: 'Silver Cross',
    label: 'Silver Cross Wave 3',
    shortLabel: 'Wave 3',
    description: 'Single-to-double stroller (non-modular)',
    icon: 'convertible',
    strollerCategory: 'convertible-non-modular',
    aliases: ['wave', 'wave 3', 'silver cross wave', 'silver cross wave 3'],
  },
  {
    id: 'silver-cross-jet-5',
    type: 'stroller',
    brand: 'Silver Cross',
    label: 'Silver Cross Jet 5',
    shortLabel: 'Jet 5',
    description: 'Travel stroller',
    icon: 'plane',
    strollerCategory: 'travel',
    aliases: ['jet', 'jet 5', 'silver cross jet', 'silver cross jet 5'],
  },
  // ── Baby Jogger ──────────────────────────────────────────────────────────────
  {
    id: 'baby-jogger-city-select',
    type: 'stroller',
    brand: 'Baby Jogger',
    label: 'Baby Jogger City Select 2',
    shortLabel: 'City Select 2',
    description: 'Modular single-to-double convertible',
    icon: 'convertible',
    strollerCategory: 'convertible-modular',
    aliases: ['city select', 'city select 2', 'baby jogger city select', 'baby jogger city select 2'],
  },
  {
    id: 'baby-jogger-city-tour',
    type: 'stroller',
    brand: 'Baby Jogger',
    label: 'Baby Jogger City Tour 2',
    shortLabel: 'City Tour 2',
    description: 'Travel stroller',
    icon: 'plane',
    strollerCategory: 'travel',
    aliases: ['city tour', 'city tour 2', 'baby jogger city tour', 'baby jogger city tour 2'],
  },
  {
    id: 'baby-jogger-city-mini',
    type: 'stroller',
    brand: 'Baby Jogger',
    label: 'Baby Jogger City Mini GT2',
    shortLabel: 'City Mini GT2',
    description: 'Compact / mid-size stroller',
    icon: 'compact',
    strollerCategory: 'compact',
    aliases: ['city mini', 'city mini gt', 'city mini gt2', 'baby jogger city mini', 'baby jogger city mini gt2'],
  },
  {
    id: 'baby-jogger-city-mini-double',
    type: 'stroller',
    brand: 'Baby Jogger',
    label: 'Baby Jogger City Mini GT2 Double',
    shortLabel: 'City Mini Double',
    description: 'Double stroller',
    icon: 'double',
    strollerCategory: 'double',
    aliases: ['city mini double', 'city mini gt2 double', 'baby jogger city mini double'],
  },
  {
    id: 'baby-jogger-city-sights',
    type: 'stroller',
    brand: 'Baby Jogger',
    label: 'Baby Jogger City Sights',
    shortLabel: 'City Sights',
    description: 'Full-size modular stroller',
    icon: 'stroller',
    strollerCategory: 'full-size',
    aliases: ['city sights', 'baby jogger city sights'],
  },
  // ── BOB ──────────────────────────────────────────────────────────────────────
  {
    id: 'bob-revolution-flex',
    type: 'stroller',
    brand: 'BOB',
    label: 'BOB Revolution Flex 3.0',
    shortLabel: 'Revolution Flex 3.0',
    description: 'Jogging / all-terrain stroller',
    icon: 'terrain',
    strollerCategory: 'jogging',
    aliases: ['bob revolution', 'revolution flex', 'bob revolution flex', 'revolution flex 3.0', 'bob revolution flex 3.0'],
  },
  {
    id: 'bob-alterrain-pro-duallie',
    type: 'stroller',
    brand: 'BOB',
    label: 'BOB Alterrain Duallie',
    shortLabel: 'Alterrain Duallie',
    description: 'Double jogging stroller',
    icon: 'terrain',
    strollerCategory: 'double-jogging',
    aliases: ['alterrain duallie', 'bob alterrain duallie', 'bob alterrain pro duallie'],
  },
  {
    id: 'baby-jogger-summit-x3-double',
    type: 'stroller',
    brand: 'Baby Jogger',
    label: 'Baby Jogger Summit X3 Double',
    shortLabel: 'Summit X3 Double',
    description: 'Double jogging stroller',
    icon: 'terrain',
    strollerCategory: 'double-jogging',
    aliases: ['summit x3 double', 'baby jogger summit x3 double'],
  },
  {
    id: 'thule-chariot-cross-2',
    type: 'stroller',
    brand: 'Thule',
    label: 'Thule Chariot Cross 2',
    shortLabel: 'Chariot Cross 2',
    description: 'Double multisport jogging stroller',
    icon: 'terrain',
    strollerCategory: 'double-jogging',
    aliases: ['chariot cross', 'chariot cross 2', 'thule chariot cross 2'],
  },
  {
    id: 'bob-renegade-wagon',
    type: 'stroller',
    brand: 'BOB',
    label: 'BOB Renegade Wagon',
    shortLabel: 'Renegade Wagon',
    description: 'Wagon stroller',
    icon: 'double',
    strollerCategory: 'wagon',
    aliases: ['bob renegade', 'renegade', 'renegade wagon', 'bob renegade wagon'],
  },
  {
    id: 'bob-wayfinder',
    type: 'stroller',
    brand: 'BOB',
    label: 'BOB Wayfinder',
    shortLabel: 'Wayfinder',
    description: 'Jogging / all-terrain stroller',
    icon: 'terrain',
    strollerCategory: 'jogging',
    aliases: ['wayfinder', 'bob wayfinder'],
  },
  {
    id: 'bob-rambler',
    type: 'stroller',
    brand: 'BOB',
    label: 'BOB Rambler',
    shortLabel: 'Rambler',
    description: 'Jogging / all-terrain stroller',
    icon: 'terrain',
    strollerCategory: 'jogging',
    aliases: ['rambler', 'bob rambler'],
  },
  // ── Bugaboo (additional) ─────────────────────────────────────────────────────
  {
    id: 'bugaboo-dragonfly',
    type: 'stroller',
    brand: 'Bugaboo',
    label: 'Bugaboo Dragonfly',
    shortLabel: 'Dragonfly',
    description: 'Compact / mid-size stroller',
    icon: 'compact',
    strollerCategory: 'compact',
    aliases: ['dragonfly', 'bugaboo dragonfly'],
  },
  // ── Bumbleride ───────────────────────────────────────────────────────────────
  {
    id: 'bumbleride-indie',
    type: 'stroller',
    brand: 'Bumbleride',
    label: 'Bumbleride Indie',
    shortLabel: 'Indie',
    description: 'Jogging / all-terrain stroller',
    icon: 'terrain',
    strollerCategory: 'jogging',
    aliases: ['indie', 'bumbleride indie'],
  },
  {
    id: 'bumbleride-speed',
    type: 'stroller',
    brand: 'Bumbleride',
    label: 'Bumbleride Speed',
    shortLabel: 'Speed',
    description: 'Jogging stroller',
    icon: 'terrain',
    strollerCategory: 'jogging',
    aliases: ['speed', 'bumbleride speed'],
  },
  {
    id: 'bumbleride-indie-twin',
    type: 'stroller',
    brand: 'Bumbleride',
    label: 'Bumbleride Indie Twin',
    shortLabel: 'Indie Twin',
    description: 'Double all-terrain stroller',
    icon: 'terrain',
    strollerCategory: 'double-jogging',
    aliases: ['indie twin', 'bumbleride indie twin'],
  },
  {
    id: 'bumbleride-era',
    type: 'stroller',
    brand: 'Bumbleride',
    label: 'Bumbleride Era',
    shortLabel: 'Era',
    description: 'Compact / mid-size stroller',
    icon: 'compact',
    strollerCategory: 'compact',
    aliases: ['era', 'bumbleride era'],
  },
  // ── CYBEX (additional) ───────────────────────────────────────────────────────
  {
    id: 'cybex-priam',
    type: 'stroller',
    brand: 'CYBEX',
    label: 'CYBEX Priam',
    shortLabel: 'Priam',
    description: 'Full-size modular stroller',
    icon: 'stroller',
    strollerCategory: 'full-size',
    aliases: ['priam', 'cybex priam'],
  },
  {
    id: 'cybex-mios',
    type: 'stroller',
    brand: 'CYBEX',
    label: 'CYBEX Mios',
    shortLabel: 'Mios',
    description: 'Compact / mid-size stroller',
    icon: 'compact',
    strollerCategory: 'compact',
    aliases: ['mios', 'cybex mios'],
  },
  {
    id: 'cybex-eezy-s-twist',
    type: 'stroller',
    brand: 'CYBEX',
    label: 'CYBEX Eezy S Twist+',
    shortLabel: 'Eezy S Twist+',
    description: 'Compact / mid-size stroller',
    icon: 'compact',
    strollerCategory: 'compact',
    aliases: ['eezy', 'eezy s', 'eezy s twist', 'cybex eezy', 'cybex eezy s twist', 'cybex eezy s twist+'],
  },
  {
    id: 'cybex-melio',
    type: 'stroller',
    brand: 'CYBEX',
    label: 'CYBEX Melio',
    shortLabel: 'Melio',
    description: 'Compact / mid-size stroller',
    icon: 'compact',
    strollerCategory: 'compact',
    aliases: ['melio', 'cybex melio'],
  },
  {
    id: 'cybex-beezy',
    type: 'stroller',
    brand: 'CYBEX',
    label: 'CYBEX Beezy',
    shortLabel: 'Beezy',
    description: 'Compact / mid-size stroller',
    icon: 'compact',
    strollerCategory: 'compact',
    aliases: ['beezy', 'cybex beezy'],
  },
  // ── Joolz ────────────────────────────────────────────────────────────────────
  {
    id: 'joolz-hub',
    type: 'stroller',
    brand: 'Joolz',
    label: 'Joolz Hub+',
    shortLabel: 'Hub+',
    description: 'Full-size modular stroller',
    icon: 'stroller',
    strollerCategory: 'full-size',
    aliases: ['hub', 'hub+', 'joolz hub', 'joolz hub+'],
  },
  {
    id: 'joolz-day5',
    type: 'stroller',
    brand: 'Joolz',
    label: 'Joolz Day5',
    shortLabel: 'Day5',
    description: 'Full-size modular stroller',
    icon: 'stroller',
    strollerCategory: 'full-size',
    aliases: ['day', 'day5', 'joolz day', 'joolz day5'],
  },
  {
    id: 'joolz-geo3',
    type: 'stroller',
    brand: 'Joolz',
    label: 'Joolz Geo3',
    shortLabel: 'Geo3',
    description: 'Modular single-to-double convertible',
    icon: 'convertible',
    strollerCategory: 'convertible-modular',
    aliases: ['geo', 'geo3', 'joolz geo', 'joolz geo3'],
  },
  {
    id: 'joolz-aer',
    type: 'stroller',
    brand: 'Joolz',
    label: 'Joolz Aer+',
    shortLabel: 'Aer+',
    description: 'Compact / mid-size stroller',
    icon: 'compact',
    strollerCategory: 'compact',
    aliases: ['aer', 'aer+', 'joolz aer', 'joolz aer+'],
  },
  // ── Mima ─────────────────────────────────────────────────────────────────────
  {
    id: 'mima-xari',
    type: 'stroller',
    brand: 'Mima',
    label: 'Mima Xari',
    shortLabel: 'Xari',
    description: 'Full-size modular stroller',
    icon: 'stroller',
    strollerCategory: 'full-size',
    aliases: ['xari', 'mima xari'],
  },
  {
    id: 'mima-zigi',
    type: 'stroller',
    brand: 'Mima',
    label: 'Mima Zigi',
    shortLabel: 'Zigi',
    description: 'Compact / mid-size stroller',
    icon: 'compact',
    strollerCategory: 'compact',
    aliases: ['zigi', 'mima zigi'],
  },
  // ── Nuna (additional) ────────────────────────────────────────────────────────
  {
    id: 'nuna-demi-next',
    type: 'stroller',
    brand: 'Nuna',
    label: 'Nuna DEMI Next',
    shortLabel: 'DEMI Next',
    description: 'Modular single-to-double convertible',
    icon: 'convertible',
    strollerCategory: 'convertible-modular',
    aliases: ['demi', 'demi next', 'nuna demi', 'nuna demi next'],
  },
  {
    id: 'nuna-tavo-next',
    type: 'stroller',
    brand: 'Nuna',
    label: 'Nuna TAVO Next',
    shortLabel: 'TAVO Next',
    description: 'Full-size stroller (non-modular)',
    icon: 'stroller',
    strollerCategory: 'full-size-non-modular',
    aliases: ['tavo', 'tavo next', 'nuna tavo', 'nuna tavo next'],
  },
  // ── Orbit Baby ───────────────────────────────────────────────────────────────
  {
    id: 'orbit-baby-g5',
    type: 'stroller',
    brand: 'Orbit Baby',
    label: 'Orbit Baby G5',
    shortLabel: 'G5',
    description: 'Single-to-double stroller (non-modular)',
    icon: 'convertible',
    strollerCategory: 'convertible-non-modular',
    aliases: ['g5', 'x5', 'orbit baby g5', 'orbit baby x5', 'orbit g5'],
  },
  // ── Peg Perego ───────────────────────────────────────────────────────────────
  {
    id: 'peg-perego-ypsi',
    type: 'stroller',
    brand: 'Peg Perego',
    label: 'Peg Perego YPSI',
    shortLabel: 'YPSI',
    description: 'Full-size modular stroller',
    icon: 'stroller',
    strollerCategory: 'full-size',
    aliases: ['ypsi', 'z4', 'peg perego ypsi', 'peg perego z4'],
  },
  {
    id: 'peg-perego-selfie',
    type: 'stroller',
    brand: 'Peg Perego',
    label: 'Peg Perego Selfie',
    shortLabel: 'Selfie',
    description: 'Compact / mid-size stroller',
    icon: 'compact',
    strollerCategory: 'compact',
    aliases: ['selfie', 'peg perego selfie'],
  },
  // ── Silver Cross (additional) ─────────────────────────────────────────────────
  {
    id: 'silver-cross-comet',
    type: 'stroller',
    brand: 'Silver Cross',
    label: 'Silver Cross Comet',
    shortLabel: 'Comet',
    description: 'Compact / mid-size stroller',
    icon: 'compact',
    strollerCategory: 'compact',
    aliases: ['comet', 'silver cross comet'],
  },
  // ── Stokke ───────────────────────────────────────────────────────────────────
  {
    id: 'stokke-xplory-x',
    type: 'stroller',
    brand: 'Stokke',
    label: 'Stokke Xplory X',
    shortLabel: 'Xplory X',
    description: 'Full-size modular stroller',
    icon: 'stroller',
    strollerCategory: 'full-size',
    aliases: ['xplory', 'xplory x', 'stokke xplory', 'stokke xplory x'],
  },
  // ── BABYZEN ──────────────────────────────────────────────────────────────────
  {
    id: 'babyzen-yoyo2',
    type: 'stroller',
    brand: 'BABYZEN',
    label: 'BABYZEN YOYO2',
    shortLabel: 'YOYO2',
    description: 'Travel stroller',
    icon: 'plane',
    strollerCategory: 'travel',
    aliases: ['yoyo', 'yoyo 2', 'yoyo2', 'babyzen yoyo', 'babyzen yoyo2', 'babyzen yoyo 2'],
  },
  // ── UPPAbaby (additional) ────────────────────────────────────────────────────
  {
    id: 'uppababy-ridge',
    type: 'stroller',
    brand: 'UPPAbaby',
    label: 'UPPAbaby Ridge',
    shortLabel: 'Ridge',
    description: 'Jogging / all-terrain stroller',
    icon: 'terrain',
    strollerCategory: 'jogging',
    aliases: ['ridge', 'uppababy ridge'],
  },
  // ── Thule ────────────────────────────────────────────────────────────────────
  {
    id: 'thule-urban-glide-2',
    type: 'stroller',
    brand: 'Thule',
    label: 'Thule Urban Glide 2',
    shortLabel: 'Urban Glide 2',
    description: 'Jogging / all-terrain stroller',
    icon: 'terrain',
    strollerCategory: 'jogging',
    aliases: ['thule urban glide', 'urban glide', 'urban glide 2', 'thule urban glide 2'],
  },
  {
    id: 'thule-shine',
    type: 'stroller',
    brand: 'Thule',
    label: 'Thule Shine',
    shortLabel: 'Shine',
    description: 'Full-size modular stroller',
    icon: 'stroller',
    strollerCategory: 'full-size',
    aliases: ['thule shine', 'shine'],
  },
  {
    id: 'thule-spring',
    type: 'stroller',
    brand: 'Thule',
    label: 'Thule Spring',
    shortLabel: 'Spring',
    description: 'Compact / mid-size stroller',
    icon: 'compact',
    strollerCategory: 'compact',
    aliases: ['thule spring', 'spring'],
  },
  // ── Veer ─────────────────────────────────────────────────────────────────────
  {
    id: 'veer-cruiser',
    type: 'stroller',
    brand: 'Veer',
    label: 'Veer Cruiser',
    shortLabel: 'Cruiser',
    description: 'Wagon stroller',
    icon: 'double',
    strollerCategory: 'wagon',
    aliases: ['veer', 'cruiser', 'veer cruiser'],
  },
  {
    id: 'veer-switchback-roll',
    type: 'stroller',
    brand: 'Veer',
    label: 'Veer Switchback Roll',
    shortLabel: 'Switchback Roll',
    description: 'Modular single-to-double convertible',
    icon: 'convertible',
    strollerCategory: 'convertible-modular',
    aliases: ['switchback roll', 'veer roll', 'veer switchback', 'veer switchback roll', 'veer &roll'],
  },
  {
    id: 'veer-switchback-jog',
    type: 'stroller',
    brand: 'Veer',
    label: 'Veer Switchback Jog',
    shortLabel: 'Switchback Jog',
    description: 'Jogging / all-terrain stroller',
    icon: 'terrain',
    strollerCategory: 'jogging',
    aliases: ['veer jog', 'switchback jog', 'veer switchback jog', 'veer &jog'],
  },
  // ── Baby Jogger (additional) ─────────────────────────────────────────────────
  {
    id: 'baby-jogger-city-mini-2',
    type: 'stroller',
    brand: 'Baby Jogger',
    label: 'Baby Jogger City Mini 2',
    shortLabel: 'City Mini 2',
    description: 'Compact / mid-size stroller',
    icon: 'compact',
    strollerCategory: 'compact',
    aliases: ['city mini 2', 'baby jogger city mini 2'],
  },
  {
    id: 'baby-jogger-summit-x3',
    type: 'stroller',
    brand: 'Baby Jogger',
    label: 'Baby Jogger Summit X3',
    shortLabel: 'Summit X3',
    description: 'Jogging / all-terrain stroller',
    icon: 'terrain',
    strollerCategory: 'jogging',
    aliases: ['summit', 'summit x3', 'baby jogger summit', 'baby jogger summit x3'],
  },
  // ── BABYZEN (additional) ─────────────────────────────────────────────────────
  {
    id: 'babyzen-yoyo-plus',
    type: 'stroller',
    brand: 'BABYZEN',
    label: 'BABYZEN YOYO+',
    shortLabel: 'YOYO+',
    description: 'Travel stroller',
    icon: 'plane',
    strollerCategory: 'travel',
    aliases: ['yoyo+', 'yoyo plus', 'babyzen yoyo+', 'babyzen yoyo plus'],
  },
  // ── BOB (additional) ─────────────────────────────────────────────────────────
  {
    id: 'bob-alterrain-pro',
    type: 'stroller',
    brand: 'BOB',
    label: 'BOB Alterrain Pro',
    shortLabel: 'Alterrain Pro',
    description: 'Jogging / all-terrain stroller',
    icon: 'terrain',
    strollerCategory: 'jogging',
    aliases: ['alterrain', 'alterrain pro', 'bob alterrain', 'bob alterrain pro'],
  },
  {
    id: 'bob-revolution-flex-duallie',
    type: 'stroller',
    brand: 'BOB',
    label: 'BOB Revolution Flex 3.0 Duallie',
    shortLabel: 'Revolution Flex Duallie',
    description: 'Double jogging stroller',
    icon: 'terrain',
    strollerCategory: 'double-jogging',
    aliases: ['duallie', 'revolution flex duallie', 'bob revolution duallie', 'bob revolution flex 3.0 duallie'],
  },
  // ── Britax ───────────────────────────────────────────────────────────────────
  {
    id: 'britax-b-clever',
    type: 'stroller',
    brand: 'Britax',
    label: 'Britax B-Clever',
    shortLabel: 'B-Clever',
    description: 'Compact / mid-size stroller',
    icon: 'compact',
    strollerCategory: 'compact',
    aliases: ['b-clever', 'b clever', 'britax b-clever', 'britax b clever'],
  },
  {
    id: 'britax-b-lively',
    type: 'stroller',
    brand: 'Britax',
    label: 'Britax B-Lively',
    shortLabel: 'B-Lively',
    description: 'Compact / mid-size stroller',
    icon: 'compact',
    strollerCategory: 'compact',
    aliases: ['b-lively', 'b lively', 'britax b-lively', 'britax b lively'],
  },
  // ── Bugaboo (additional) ─────────────────────────────────────────────────────
  {
    id: 'bugaboo-butterfly-2',
    type: 'stroller',
    brand: 'Bugaboo',
    label: 'Bugaboo Butterfly 2',
    shortLabel: 'Butterfly 2',
    description: 'Travel stroller',
    icon: 'plane',
    strollerCategory: 'travel',
    aliases: ['butterfly 2', 'bugaboo butterfly 2'],
  },
  {
    id: 'bugaboo-donkey-3',
    type: 'stroller',
    brand: 'Bugaboo',
    label: 'Bugaboo Donkey 3',
    shortLabel: 'Donkey 3',
    description: 'Modular single-to-double convertible',
    icon: 'convertible',
    strollerCategory: 'convertible-modular',
    aliases: ['donkey 3', 'bugaboo donkey 3'],
  },
  {
    id: 'bugaboo-fox-2',
    type: 'stroller',
    brand: 'Bugaboo',
    label: 'Bugaboo Fox 2',
    shortLabel: 'Fox 2',
    description: 'Full-size modular stroller',
    icon: 'stroller',
    strollerCategory: 'full-size',
    aliases: ['fox 2', 'bugaboo fox 2'],
  },
  {
    id: 'bugaboo-kangaroo',
    type: 'stroller',
    brand: 'Bugaboo',
    label: 'Bugaboo Kangaroo',
    shortLabel: 'Kangaroo',
    description: 'Single-to-double stroller (non-modular)',
    icon: 'convertible',
    strollerCategory: 'convertible-non-modular',
    aliases: ['kangaroo', 'bugaboo kangaroo'],
  },
  // ── CYBEX (additional) ───────────────────────────────────────────────────────
  {
    id: 'cybex-coya',
    type: 'stroller',
    brand: 'CYBEX',
    label: 'CYBEX Coya',
    shortLabel: 'Coya',
    description: 'Compact / mid-size stroller',
    icon: 'compact',
    strollerCategory: 'compact',
    aliases: ['coya', 'cybex coya'],
  },
  {
    id: 'cybex-eos',
    type: 'stroller',
    brand: 'CYBEX',
    label: 'CYBEX Eos',
    shortLabel: 'Eos',
    description: 'Compact / mid-size stroller',
    icon: 'compact',
    strollerCategory: 'compact',
    aliases: ['eos', 'cybex eos'],
  },
  // ── Egg ──────────────────────────────────────────────────────────────────────
  {
    id: 'egg-egg',
    type: 'stroller',
    brand: 'Egg',
    label: 'Egg Stroller',
    shortLabel: 'Egg',
    description: 'Full-size modular stroller',
    icon: 'stroller',
    strollerCategory: 'full-size',
    aliases: ['egg', 'egg stroller'],
  },
  // ── Joie ─────────────────────────────────────────────────────────────────────
  {
    id: 'joie-ginger',
    type: 'stroller',
    brand: 'Joie',
    label: 'Joie Ginger',
    shortLabel: 'Ginger',
    description: 'Compact / mid-size stroller',
    icon: 'compact',
    strollerCategory: 'compact',
    aliases: ['ginger', 'joie ginger'],
  },
  {
    id: 'joie-hazel',
    type: 'stroller',
    brand: 'Joie',
    label: 'Joie Hazel',
    shortLabel: 'Hazel',
    description: 'Compact / mid-size stroller',
    icon: 'compact',
    strollerCategory: 'compact',
    aliases: ['hazel', 'joie hazel'],
  },
  {
    id: 'joie-kava',
    type: 'stroller',
    brand: 'Joie',
    label: 'Joie Kava',
    shortLabel: 'Kava',
    description: 'Compact / mid-size stroller',
    icon: 'compact',
    strollerCategory: 'compact',
    aliases: ['kava', 'joie kava'],
  },
  {
    id: 'joie-nutmeg',
    type: 'stroller',
    brand: 'Joie',
    label: 'Joie Nutmeg',
    shortLabel: 'Nutmeg',
    description: 'Compact / mid-size stroller',
    icon: 'compact',
    strollerCategory: 'compact',
    aliases: ['nutmeg', 'joie nutmeg'],
  },
  {
    id: 'joie-rosemary',
    type: 'stroller',
    brand: 'Joie',
    label: 'Joie Rosemary',
    shortLabel: 'Rosemary',
    description: 'Compact / mid-size stroller',
    icon: 'compact',
    strollerCategory: 'compact',
    aliases: ['rosemary', 'joie rosemary'],
  },
  {
    id: 'joie-tansy',
    type: 'stroller',
    brand: 'Joie',
    label: 'Joie Tansy',
    shortLabel: 'Tansy',
    description: 'Compact / mid-size stroller',
    icon: 'compact',
    strollerCategory: 'compact',
    aliases: ['tansy', 'joie tansy'],
  },
  // ── Joolz (additional) ───────────────────────────────────────────────────────
  {
    id: 'joolz-day',
    type: 'stroller',
    brand: 'Joolz',
    label: 'Joolz Day',
    shortLabel: 'Day',
    description: 'Full-size modular stroller',
    icon: 'stroller',
    strollerCategory: 'full-size',
    aliases: ['joolz day'],
  },
  {
    id: 'joolz-hub-2',
    type: 'stroller',
    brand: 'Joolz',
    label: 'Joolz Hub 2',
    shortLabel: 'Hub 2',
    description: 'Full-size modular stroller',
    icon: 'stroller',
    strollerCategory: 'full-size',
    aliases: ['hub 2', 'joolz hub 2'],
  },
  // ── Joovy ────────────────────────────────────────────────────────────────────
  {
    id: 'joovy-caboose-s',
    type: 'stroller',
    brand: 'Joovy',
    label: 'Joovy Caboose S',
    shortLabel: 'Caboose S',
    description: 'Double / sit-and-stand stroller',
    icon: 'double',
    strollerCategory: 'double',
    aliases: ['caboose', 'caboose s', 'joovy caboose', 'joovy caboose s'],
  },
  {
    id: 'joovy-caboose-ultralight',
    type: 'stroller',
    brand: 'Joovy',
    label: 'Joovy Caboose Ultralight Graphite',
    shortLabel: 'Caboose Ultralight',
    description: 'Double / sit-and-stand stroller',
    icon: 'double',
    strollerCategory: 'double',
    aliases: ['caboose ultralight', 'joovy caboose ultralight'],
  },
  {
    id: 'joovy-qool',
    type: 'stroller',
    brand: 'Joovy',
    label: 'Joovy Qool',
    shortLabel: 'Qool',
    description: 'Modular single-to-double convertible',
    icon: 'convertible',
    strollerCategory: 'convertible-modular',
    aliases: ['qool', 'joovy qool'],
  },
  {
    id: 'joovy-twin-roo-plus',
    type: 'stroller',
    brand: 'Joovy',
    label: 'Joovy Twin Roo+',
    shortLabel: 'Twin Roo+',
    description: 'Double stroller / infant car seat frame',
    icon: 'double',
    strollerCategory: 'double',
    aliases: ['twin roo', 'twin roo+', 'joovy twin roo', 'joovy twin roo+'],
  },
  // ── Kinderkraft ──────────────────────────────────────────────────────────────
  {
    id: 'kinderkraft-lila',
    type: 'stroller',
    brand: 'Kinderkraft',
    label: 'Kinderkraft Lila',
    shortLabel: 'Lila',
    description: 'Compact / mid-size stroller',
    icon: 'compact',
    strollerCategory: 'compact',
    aliases: ['lila', 'kinderkraft lila'],
  },
  {
    id: 'kinderkraft-tayla',
    type: 'stroller',
    brand: 'Kinderkraft',
    label: 'Kinderkraft Tayla',
    shortLabel: 'Tayla',
    description: 'Compact / mid-size stroller',
    icon: 'compact',
    strollerCategory: 'compact',
    aliases: ['tayla', 'kinderkraft tayla'],
  },
  // ── Mima (additional) ────────────────────────────────────────────────────────
  {
    id: 'mima-creo',
    type: 'stroller',
    brand: 'Mima',
    label: 'Mima Creo',
    shortLabel: 'Creo',
    description: 'Full-size modular stroller',
    icon: 'stroller',
    strollerCategory: 'full-size',
    aliases: ['creo', 'mima creo'],
  },
  {
    id: 'mima-xari-sport',
    type: 'stroller',
    brand: 'Mima',
    label: 'Mima Xari Sport',
    shortLabel: 'Xari Sport',
    description: 'Full-size modular stroller',
    icon: 'stroller',
    strollerCategory: 'full-size',
    aliases: ['xari sport', 'mima xari sport'],
  },
  // ── Mockingbird ──────────────────────────────────────────────────────────────
  {
    id: 'mockingbird-single-3',
    type: 'stroller',
    brand: 'Mockingbird',
    label: 'Mockingbird Single 3.0',
    shortLabel: 'Single 3.0',
    description: 'Compact / mid-size stroller',
    icon: 'compact',
    strollerCategory: 'compact',
    aliases: ['mockingbird', 'mockingbird single', 'mockingbird single 3.0'],
  },
  {
    id: 'mockingbird-single-to-double-3',
    type: 'stroller',
    brand: 'Mockingbird',
    label: 'Mockingbird Single-to-Double 3.0',
    shortLabel: 'Single-to-Double 3.0',
    description: 'Modular single-to-double convertible',
    icon: 'convertible',
    strollerCategory: 'convertible-modular',
    aliases: ['mockingbird double', 'mockingbird single to double', 'mockingbird single-to-double 3.0'],
  },
  // ── Nuna (additional) ────────────────────────────────────────────────────────
  {
    id: 'nuna-swiv',
    type: 'stroller',
    brand: 'Nuna',
    label: 'Nuna SWIV',
    shortLabel: 'SWIV',
    description: 'Compact modular stroller',
    icon: 'stroller',
    strollerCategory: 'compact',
    aliases: ['swiv', 'nuna swiv'],
  },
  {
    id: 'nuna-trvl-dubl',
    type: 'stroller',
    brand: 'Nuna',
    label: 'Nuna TRVL Dubl',
    shortLabel: 'TRVL Dubl',
    description: 'Double travel stroller',
    icon: 'double',
    strollerCategory: 'double-travel',
    aliases: ['trvl dubl', 'nuna trvl dubl'],
  },
  {
    id: 'uppababy-minu-duo',
    type: 'stroller',
    brand: 'UPPAbaby',
    label: 'UPPAbaby Minu Duo',
    shortLabel: 'Minu Duo',
    description: 'Lightweight double travel stroller',
    icon: 'double',
    strollerCategory: 'double-travel',
    aliases: ['minu duo', 'uppababy minu duo'],
  },
  // ── Orbit Baby (additional) ──────────────────────────────────────────────────
  {
    id: 'orbit-baby-x5',
    type: 'stroller',
    brand: 'Orbit Baby',
    label: 'Orbit Baby X5',
    shortLabel: 'X5',
    description: 'Single-to-double stroller (non-modular)',
    icon: 'convertible',
    strollerCategory: 'convertible-non-modular',
    aliases: ['orbit x5', 'orbit baby x5'],
  },
  // ── Peg Perego (additional) ──────────────────────────────────────────────────
  {
    id: 'peg-perego-z4',
    type: 'stroller',
    brand: 'Peg Perego',
    label: 'Peg Perego Z4',
    shortLabel: 'Z4',
    description: 'Full-size modular stroller',
    icon: 'stroller',
    strollerCategory: 'full-size',
    aliases: ['z4', 'peg perego z4'],
  },
  // ── Silver Cross (additional) ─────────────────────────────────────────────────
  {
    id: 'silver-cross-reef',
    type: 'stroller',
    brand: 'Silver Cross',
    label: 'Silver Cross Reef',
    shortLabel: 'Reef',
    description: 'Full-size modular stroller',
    icon: 'stroller',
    strollerCategory: 'full-size',
    aliases: ['reef', 'silver cross reef'],
  },
  {
    id: 'silver-cross-dune-2',
    type: 'stroller',
    brand: 'Silver Cross',
    label: 'Silver Cross Dune 2',
    shortLabel: 'Dune 2',
    description: 'Full-size modular stroller',
    icon: 'stroller',
    strollerCategory: 'full-size',
    aliases: ['dune 2', 'silver cross dune 2'],
  },
  {
    id: 'silver-cross-jet-double',
    type: 'stroller',
    brand: 'Silver Cross',
    label: 'Silver Cross Jet Double',
    shortLabel: 'Jet Double',
    description: 'Double travel stroller',
    icon: 'double',
    strollerCategory: 'double-travel',
    aliases: ['jet double', 'silver cross jet double'],
  },
  {
    id: 'silver-cross-wave',
    type: 'stroller',
    brand: 'Silver Cross',
    label: 'Silver Cross Wave',
    shortLabel: 'Wave',
    description: 'Single-to-double stroller (non-modular)',
    icon: 'convertible',
    strollerCategory: 'convertible-non-modular',
    aliases: ['silver cross wave'],
  },
  // ── Stokke (additional) ──────────────────────────────────────────────────────
  {
    id: 'stokke-yoyo-3',
    type: 'stroller',
    brand: 'Stokke',
    label: 'Stokke Yoyo 3',
    shortLabel: 'Yoyo 3',
    description: 'Travel stroller',
    icon: 'plane',
    strollerCategory: 'travel',
    aliases: ['yoyo 3', 'stokke yoyo', 'stokke yoyo 3'],
  },
  // ── Thule (additional) ───────────────────────────────────────────────────────
  {
    id: 'thule-glide-2',
    type: 'stroller',
    brand: 'Thule',
    label: 'Thule Glide 2',
    shortLabel: 'Glide 2',
    description: 'Jogging stroller',
    icon: 'terrain',
    strollerCategory: 'jogging',
    aliases: ['glide', 'glide 2', 'thule glide', 'thule glide 2'],
  },
  {
    id: 'thule-sleek',
    type: 'stroller',
    brand: 'Thule',
    label: 'Thule Sleek',
    shortLabel: 'Sleek',
    description: 'Full-size modular stroller',
    icon: 'stroller',
    strollerCategory: 'full-size',
    aliases: ['sleek', 'thule sleek'],
  },
  {
    id: 'thule-urban-glide-2-double',
    type: 'stroller',
    brand: 'Thule',
    label: 'Thule Urban Glide 2 Double',
    shortLabel: 'Urban Glide 2 Double',
    description: 'Double jogging stroller',
    icon: 'terrain',
    strollerCategory: 'double-jogging',
    aliases: ['urban glide 2 double', 'thule urban glide 2 double'],
  },
  // ── UPPAbaby (additional) ────────────────────────────────────────────────────
  {
    id: 'uppababy-vista-v3',
    type: 'stroller',
    brand: 'UPPAbaby',
    label: 'UPPAbaby Vista V3',
    shortLabel: 'Vista V3',
    description: 'Single-to-double stroller (non-modular)',
    icon: 'convertible',
    strollerCategory: 'convertible-non-modular',
    aliases: ['vista v3', 'uppababy vista v3'],
  },
  {
    id: 'uppababy-cruz-v3',
    type: 'stroller',
    brand: 'UPPAbaby',
    label: 'UPPAbaby Cruz V3',
    shortLabel: 'Cruz V3',
    description: 'Full-size stroller (non-modular)',
    icon: 'stroller',
    strollerCategory: 'full-size-non-modular',
    aliases: ['cruz v3', 'uppababy cruz v3'],
  },
  {
    id: 'uppababy-minu-v3',
    type: 'stroller',
    brand: 'UPPAbaby',
    label: 'UPPAbaby Minu V3',
    shortLabel: 'Minu V3',
    description: 'Travel stroller',
    icon: 'plane',
    strollerCategory: 'travel',
    aliases: ['minu v3', 'uppababy minu v3'],
  },
  {
    id: 'bugaboo-turtle-air',
    type: 'carSeat',
    brand: 'Bugaboo',
    label: 'Bugaboo Turtle Air by Nuna',
    shortLabel: 'Turtle Air',
    description: 'Infant car seat',
    icon: 'carseat',
    aliases: ['turtle air', 'bugaboo turtle air', 'bugaboo turtle air by nuna'],
  },
  {
    id: 'bugaboo-turtle-one',
    type: 'carSeat',
    brand: 'Bugaboo',
    label: 'Bugaboo Turtle One by Nuna',
    shortLabel: 'Turtle One',
    description: 'Infant car seat',
    icon: 'carseat',
    aliases: ['turtle one', 'bugaboo turtle one', 'bugaboo turtle one by nuna', 'turtle by nuna'],
  },
  {
    id: 'nuna-pipa-rx',
    type: 'carSeat',
    brand: 'Nuna',
    label: 'Nuna PIPA RX',
    shortLabel: 'PIPA RX',
    description: 'Infant car seat',
    icon: 'carseat',
    aliases: ['pipa', 'pipa rx', 'nuna pipa', 'nuna pipa rx'],
  },
  {
    id: 'nuna-pipa-lite-rx',
    type: 'carSeat',
    brand: 'Nuna',
    label: 'Nuna PIPA Aire',
    shortLabel: 'PIPA Aire',
    description: 'Infant car seat',
    icon: 'carseat',
    aliases: ['pipa aire', 'nuna pipa aire', 'pipa lite rx', 'nuna pipa lite rx'],
  },
  {
    id: 'nuna-pipa-urbn',
    type: 'carSeat',
    brand: 'Nuna',
    label: 'Nuna PIPA urbn',
    shortLabel: 'PIPA urbn',
    description: 'Baseless infant car seat',
    icon: 'carseat',
    aliases: ['pipa urbn', 'urbn', 'nuna pipa urbn'],
  },
  {
    id: 'uppababy-aria',
    type: 'carSeat',
    brand: 'UPPAbaby',
    label: 'UPPAbaby Aria',
    shortLabel: 'Aria',
    description: 'Infant car seat',
    icon: 'carseat',
    aliases: ['aria', 'uppababy aria'],
  },
  {
    id: 'uppababy-mesa-max',
    type: 'carSeat',
    brand: 'UPPAbaby',
    label: 'UPPAbaby Mesa Max',
    shortLabel: 'Mesa Max',
    description: 'Infant car seat',
    icon: 'carseat',
    aliases: ['mesa', 'mesa max', 'uppababy mesa', 'uppababy mesa max'],
  },
  {
    id: 'cybex-aton-g',
    type: 'carSeat',
    brand: 'CYBEX',
    label: 'CYBEX Aton G',
    shortLabel: 'Aton G',
    description: 'Infant car seat',
    icon: 'carseat',
    aliases: ['aton', 'aton g', 'cybex aton', 'cybex aton g'],
  },
];

const TRAVEL_SYSTEM_PAIRS: TravelSystemCompatibilityPair[] = [
  {
    strollerId: 'bugaboo-fox-5',
    carSeatId: 'bugaboo-turtle-air',
    connection: 'adapterRequired',
    note: 'Bugaboo says Fox 5 works with Turtle Air using the Bugaboo car seat adapter.',
    sourceLabel: 'Bugaboo Fox 5',
    sourceUrl: 'https://www.bugaboo.com/us-en/strollers/bugaboo-fox-5/bugaboo-fox-5-2-in-1-stroller-black-base-grey-melange-fabrics-astro-purple-sun-canopy-PV006257.html',
  },
  {
    strollerId: 'bugaboo-fox-5',
    carSeatId: 'bugaboo-turtle-one',
    connection: 'adapterRequired',
    note: 'Bugaboo lists Fox 5 among Turtle One compatible strollers when you use the Bugaboo adapter.',
    sourceLabel: 'Bugaboo Turtle One by Nuna',
    sourceUrl: 'https://www.bugaboo.com/us-en/car-seat/bugaboo-turtle-by-nuna-baby-capsule-with-isofix-base-MI002356AU.html',
  },
  {
    strollerId: 'bugaboo-butterfly',
    carSeatId: 'bugaboo-turtle-air',
    connection: 'adapterRequired',
    note: 'Use the Butterfly car seat adapter for Turtle Air by Nuna.',
    sourceLabel: 'Bugaboo Butterfly car seat adapter',
    sourceUrl: 'https://www.bugaboo.com/us-en/accessories/adapters/bugaboo-butterfly-car-seat-adapter-100045001.html',
  },
  {
    strollerId: 'bugaboo-butterfly',
    carSeatId: 'bugaboo-turtle-one',
    connection: 'adapterRequired',
    note: 'Use the Butterfly car seat adapter for Turtle One by Nuna.',
    sourceLabel: 'Bugaboo Butterfly car seat adapter',
    sourceUrl: 'https://www.bugaboo.com/us-en/accessories/adapters/bugaboo-butterfly-car-seat-adapter-100045001.html',
  },
  {
    strollerId: 'bugaboo-butterfly',
    carSeatId: 'nuna-pipa-rx',
    connection: 'adapterRequired',
    note: 'Bugaboo lists PIPA RX on the Butterfly adapter compatibility list.',
    sourceLabel: 'Bugaboo Butterfly car seat adapter',
    sourceUrl: 'https://www.bugaboo.com/us-en/accessories/adapters/bugaboo-butterfly-car-seat-adapter-100045001.html',
  },
  {
    strollerId: 'bugaboo-donkey-6',
    carSeatId: 'bugaboo-turtle-air',
    connection: 'adapterRequired',
    note: 'The Donkey car seat adapter supports Turtle Air on Donkey 6.',
    sourceLabel: 'Bugaboo Donkey adapter for Turtle/Maxi-Cosi',
    sourceUrl: 'https://www.bugaboo.com/us-en/accessories/adapters/bugaboo-donkey-adapter-for-maxi-cosi-car-seat---mono-na-855190MC01.html',
  },
  {
    strollerId: 'bugaboo-donkey-6',
    carSeatId: 'bugaboo-turtle-one',
    connection: 'adapterRequired',
    note: 'Bugaboo lists Turtle One across current Bugaboo stroller travel systems, including Donkey.',
    sourceLabel: 'Bugaboo travel systems',
    sourceUrl: 'https://www.bugaboo.com/us-en/strollers/travel-systems/',
  },
  {
    strollerId: 'nuna-mixx-next',
    carSeatId: 'nuna-pipa-rx',
    connection: 'includedAdapter',
    note: 'MIXX next includes the ring adapter and Nuna says all PIPA infant car seats are compatible.',
    sourceLabel: 'Nuna MIXX next FAQ',
    sourceUrl: 'https://usasupport.nunababy.com/hc/en-us/articles/12836208311311-MIXX-next-FAQ',
  },
  {
    strollerId: 'nuna-mixx-next',
    carSeatId: 'nuna-pipa-lite-rx',
    connection: 'includedAdapter',
    note: 'MIXX next includes the ring adapter and Nuna says all PIPA infant car seats are compatible.',
    sourceLabel: 'Nuna MIXX next FAQ',
    sourceUrl: 'https://usasupport.nunababy.com/hc/en-us/articles/12836208311311-MIXX-next-FAQ',
  },
  {
    strollerId: 'nuna-mixx-next',
    carSeatId: 'nuna-pipa-urbn',
    connection: 'includedAdapter',
    note: 'MIXX next includes the ring adapter and Nuna says all PIPA infant car seats are compatible.',
    sourceLabel: 'Nuna MIXX next FAQ',
    sourceUrl: 'https://usasupport.nunababy.com/hc/en-us/articles/12836208311311-MIXX-next-FAQ',
  },
  {
    strollerId: 'nuna-trvl-lx',
    carSeatId: 'nuna-pipa-rx',
    connection: 'direct',
    note: 'TRVL lx connects directly with Nuna PIPA series seats and does not need adapters.',
    sourceLabel: 'Nuna TRVL lx',
    sourceUrl: 'https://nunababy.com/usa/strollers/newborn-strollers-bassinets/trvl-lx-stroller-bmw-collection',
  },
  {
    strollerId: 'nuna-trvl-lx',
    carSeatId: 'nuna-pipa-lite-rx',
    connection: 'direct',
    note: 'TRVL lx connects directly with Nuna PIPA series seats and does not need adapters.',
    sourceLabel: 'Nuna TRVL lx',
    sourceUrl: 'https://nunababy.com/usa/strollers/newborn-strollers-bassinets/trvl-lx-stroller-bmw-collection',
  },
  {
    strollerId: 'nuna-trvl-lx',
    carSeatId: 'nuna-pipa-urbn',
    connection: 'direct',
    note: 'TRVL lx connects directly with Nuna PIPA series seats and does not need adapters.',
    sourceLabel: 'Nuna TRVL lx',
    sourceUrl: 'https://nunababy.com/usa/strollers/newborn-strollers-bassinets/trvl-lx-stroller-bmw-collection',
  },
  {
    strollerId: 'uppababy-cruz-v2',
    carSeatId: 'uppababy-aria',
    connection: 'direct',
    note: 'Aria attaches directly to the Cruz with no adapters.',
    sourceLabel: 'UPPAbaby Aria support',
    sourceUrl: 'https://support.uppababy.com/hc/en-us/articles/21520031651351-What-UB-strollers-is-the-Aria-compatible-with',
  },
  {
    strollerId: 'uppababy-cruz-v2',
    carSeatId: 'uppababy-mesa-max',
    connection: 'direct',
    note: 'Mesa Max attaches directly to the Cruz with no adapters.',
    sourceLabel: 'UPPAbaby Mesa Max support',
    sourceUrl: 'https://support.uppababy.com/hc/en-us/articles/8527621997719-Does-the-Mesa-Max-attach-to-UPPAbaby-strollers',
  },
  {
    strollerId: 'uppababy-cruz-v2',
    carSeatId: 'nuna-pipa-rx',
    connection: 'adapterRequired',
    note: 'Use the Vista/Cruz Nuna adapter for PIPA RX.',
    sourceLabel: 'UPPAbaby Vista/Cruz adapters',
    sourceUrl: 'https://uppababy.com/accessories/strollers-accessories/vista-cruz-maxi-cosi-adapter/',
  },
  {
    strollerId: 'uppababy-cruz-v2',
    carSeatId: 'nuna-pipa-lite-rx',
    connection: 'adapterRequired',
    note: 'Use the Vista/Cruz Nuna adapter for PIPA Aire.',
    sourceLabel: 'UPPAbaby Vista/Cruz adapters',
    sourceUrl: 'https://uppababy.com/accessories/strollers-accessories/vista-cruz-maxi-cosi-adapter/',
  },
  {
    strollerId: 'uppababy-cruz-v2',
    carSeatId: 'nuna-pipa-urbn',
    connection: 'adapterRequired',
    note: 'Use the Vista/Cruz Nuna adapter for PIPA urbn.',
    sourceLabel: 'UPPAbaby Vista/Cruz adapters',
    sourceUrl: 'https://uppababy.com/accessories/strollers-accessories/vista-cruz-maxi-cosi-adapter/',
  },
  {
    strollerId: 'uppababy-vista-v2',
    carSeatId: 'uppababy-aria',
    connection: 'direct',
    note: 'Aria attaches directly to the Vista with no adapters.',
    sourceLabel: 'UPPAbaby Aria support',
    sourceUrl: 'https://support.uppababy.com/hc/en-us/articles/21520031651351-What-UB-strollers-is-the-Aria-compatible-with',
  },
  {
    strollerId: 'uppababy-vista-v2',
    carSeatId: 'uppababy-mesa-max',
    connection: 'direct',
    note: 'Mesa Max attaches directly to the Vista with no adapters.',
    sourceLabel: 'UPPAbaby Mesa Max support',
    sourceUrl: 'https://support.uppababy.com/hc/en-us/articles/8527621997719-Does-the-Mesa-Max-attach-to-UPPAbaby-strollers',
  },
  {
    strollerId: 'uppababy-vista-v2',
    carSeatId: 'nuna-pipa-rx',
    connection: 'adapterRequired',
    note: 'Use the Vista/Cruz Nuna adapter for PIPA RX.',
    sourceLabel: 'UPPAbaby Vista/Cruz adapters',
    sourceUrl: 'https://uppababy.com/accessories/strollers-accessories/vista-cruz-maxi-cosi-adapter/',
  },
  {
    strollerId: 'uppababy-vista-v2',
    carSeatId: 'nuna-pipa-lite-rx',
    connection: 'adapterRequired',
    note: 'Use the Vista/Cruz Nuna adapter for PIPA Aire.',
    sourceLabel: 'UPPAbaby Vista/Cruz adapters',
    sourceUrl: 'https://uppababy.com/accessories/strollers-accessories/vista-cruz-maxi-cosi-adapter/',
  },
  {
    strollerId: 'uppababy-vista-v2',
    carSeatId: 'nuna-pipa-urbn',
    connection: 'adapterRequired',
    note: 'Use the Vista/Cruz Nuna adapter for PIPA urbn.',
    sourceLabel: 'UPPAbaby Vista/Cruz adapters',
    sourceUrl: 'https://uppababy.com/accessories/strollers-accessories/vista-cruz-maxi-cosi-adapter/',
  },
  {
    strollerId: 'uppababy-minu-v2',
    carSeatId: 'uppababy-aria',
    connection: 'adapterRequired',
    note: 'Minu V2 uses the UPPAbaby infant car seat adapter for Aria.',
    sourceLabel: 'UPPAbaby Minu adapters',
    sourceUrl: 'https://uppababy.com/accessories/strollers-accessories/minu-mesa-bassinet-adapters/',
  },
  {
    strollerId: 'uppababy-minu-v2',
    carSeatId: 'uppababy-mesa-max',
    connection: 'adapterRequired',
    note: 'Minu V2 uses adapters for Mesa Max.',
    sourceLabel: 'UPPAbaby Mesa Max support',
    sourceUrl: 'https://support.uppababy.com/hc/en-us/articles/8527621997719-Does-the-Mesa-Max-attach-to-UPPAbaby-strollers',
  },
  {
    strollerId: 'uppababy-minu-v2',
    carSeatId: 'nuna-pipa-rx',
    connection: 'adapterRequired',
    note: 'Use the Minu adapter for select Nuna seats, including PIPA RX.',
    sourceLabel: 'UPPAbaby Minu Nuna/Cybex adapters',
    sourceUrl: 'https://uppababy.com/accessories/strollers-accessories/minu-v2-maxi-cosi-adapter/',
  },
  {
    strollerId: 'uppababy-minu-v2',
    carSeatId: 'nuna-pipa-lite-rx',
    connection: 'adapterRequired',
    note: 'Use the Minu adapter for select Nuna seats, including PIPA Aire.',
    sourceLabel: 'UPPAbaby Minu Nuna/Cybex adapters',
    sourceUrl: 'https://uppababy.com/accessories/strollers-accessories/minu-v2-maxi-cosi-adapter/',
  },
  {
    strollerId: 'uppababy-minu-v2',
    carSeatId: 'nuna-pipa-urbn',
    connection: 'adapterRequired',
    note: 'Use the Minu adapter for select Nuna seats, including PIPA urbn.',
    sourceLabel: 'UPPAbaby Minu Nuna/Cybex adapters',
    sourceUrl: 'https://uppababy.com/accessories/strollers-accessories/minu-v2-maxi-cosi-adapter/',
  },
  {
    strollerId: 'cybex-balios-s-lux',
    carSeatId: 'cybex-aton-g',
    connection: 'includedAdapter',
    note: 'CYBEX says Balios S Lux works with all CYBEX infant seats using the included adapters.',
    sourceLabel: 'CYBEX Balios S Lux',
    sourceUrl: 'https://www.cybex-online.com/en/us/p/ST_GO_Balios_S_Lux_US.html',
  },
  {
    strollerId: 'cybex-balios-s-lux',
    carSeatId: 'nuna-pipa-rx',
    connection: 'adapterRequired',
    note: 'Use the Balios S Lux car seat adapter for PIPA RX.',
    sourceLabel: 'CYBEX Balios S Lux car seat adapter',
    sourceUrl: 'https://www.cybex-online.com/en/us/p/AC_GO_Adapter_CS_Balios_S_Talos_S_Line_EN.html',
  },
  {
    strollerId: 'cybex-balios-s-lux',
    carSeatId: 'nuna-pipa-lite-rx',
    connection: 'adapterRequired',
    note: 'Use the Balios S Lux car seat adapter for PIPA Aire.',
    sourceLabel: 'CYBEX Balios S Lux car seat adapter',
    sourceUrl: 'https://www.cybex-online.com/en/us/p/AC_GO_Adapter_CS_Balios_S_Talos_S_Line_EN.html',
  },
  {
    strollerId: 'cybex-gazelle-s',
    carSeatId: 'cybex-aton-g',
    connection: 'includedAdapter',
    note: 'CYBEX says Gazelle S works with any CYBEX infant seat using the included adapters.',
    sourceLabel: 'CYBEX Gazelle S',
    sourceUrl: 'https://www.cybex-online.com/en/us/p/Set_ST_GO_Gazelle_S_US.html',
  },
  {
    strollerId: 'cybex-libelle',
    carSeatId: 'cybex-aton-g',
    connection: 'includedAdapter',
    note: 'CYBEX says Libelle works with all CYBEX infant seats using the included adapters.',
    sourceLabel: 'CYBEX Libelle',
    sourceUrl: 'https://www.cybex-online.com/en/us/p/10102486.html',
  },
];

export const FEATURED_TRAVEL_SYSTEM_ENTITY_IDS = [
  'bugaboo-butterfly',
  'nuna-pipa-rx',
  'uppababy-cruz-v2',
  'uppababy-mesa-max',
  'cybex-balios-s-lux',
  'nuna-pipa-urbn',
] as const;

const TRAVEL_SYSTEM_ENTITY_MAP = Object.fromEntries(TRAVEL_SYSTEM_ENTITIES.map((entity) => [entity.id, entity])) as Record<
  string,
  TravelSystemEntity
>;

function normalizeSearchValue(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
}

function scoreEntityMatch(entity: TravelSystemEntity, query: string) {
  const normalizedQuery = normalizeSearchValue(query);
  if (!normalizedQuery) {
    return -1;
  }

  const candidates = [entity.label, entity.shortLabel, entity.brand, ...entity.aliases].map(normalizeSearchValue);
  let bestScore = -1;

  for (const candidate of candidates) {
    if (!candidate) {
      continue;
    }

    if (candidate === normalizedQuery) {
      return 100;
    }

    if (candidate.startsWith(normalizedQuery)) {
      bestScore = Math.max(bestScore, 80);
      continue;
    }

    if (normalizedQuery.split(' ').every((token) => candidate.includes(token))) {
      bestScore = Math.max(bestScore, 64);
      continue;
    }

    if (candidate.includes(normalizedQuery)) {
      bestScore = Math.max(bestScore, 48);
    }
  }

  return bestScore;
}

function connectionLabel(connection: TravelSystemConnectionType) {
  switch (connection) {
    case 'direct':
      return 'Direct attach';
    case 'includedAdapter':
      return 'Included adapter';
    case 'adapterRequired':
    default:
      return 'Adapter required';
  }
}

export function getTravelSystemEntity(entityId: string) {
  return TRAVEL_SYSTEM_ENTITY_MAP[entityId] ?? null;
}

export function getFeaturedTravelSystemEntities() {
  return FEATURED_TRAVEL_SYSTEM_ENTITY_IDS.map((entityId) => TRAVEL_SYSTEM_ENTITY_MAP[entityId]).filter(Boolean);
}

export function findTravelSystemEntities(query: string) {
  return TRAVEL_SYSTEM_ENTITIES.map((entity) => ({
    entity,
    score: scoreEntityMatch(entity, query),
  }))
    .filter((item) => item.score >= 0)
    .sort((left, right) => right.score - left.score || left.entity.label.localeCompare(right.entity.label))
    .map((item) => item.entity);
}

export function getTravelSystemResults(entityId: string): TravelSystemResult[] {
  return TRAVEL_SYSTEM_PAIRS.filter((pair) => pair.strollerId === entityId || pair.carSeatId === entityId)
    .map((pair) => {
      const stroller = TRAVEL_SYSTEM_ENTITY_MAP[pair.strollerId];
      const carSeat = TRAVEL_SYSTEM_ENTITY_MAP[pair.carSeatId];
      const counterpart = pair.strollerId === entityId ? carSeat : stroller;

      return {
        id: `${pair.strollerId}__${pair.carSeatId}`,
        stroller,
        carSeat,
        counterpart,
        connection: pair.connection,
        connectionLabel: connectionLabel(pair.connection),
        note: pair.note,
        sourceLabel: pair.sourceLabel,
        sourceUrl: pair.sourceUrl,
      };
    })
    .sort(
      (left, right) =>
        left.counterpart.label.localeCompare(right.counterpart.label) ||
        left.stroller.label.localeCompare(right.stroller.label) ||
        left.carSeat.label.localeCompare(right.carSeat.label),
    );
}
