-- Materialize the frozen BOB / Thule / Veer travel-system audit.
-- Source artifact: reports/travel-system-inventory/BTV_FROZEN_V1.md
-- Input CSV: reports/travel-system-inventory/TMBC_Compatibility_Row_Audit_BOB_Thule_Veer.csv
-- Frozen totals: 392 audited rows = 87 manufacturer-listed + 30 should-work + 202 unknown + 19 identity dedup + 54 excluded products.
-- Public materialization: remove the audited BTV block, then insert only the 117 consumer-visible rows.

CREATE TEMP TABLE _btv_audit_pairs (
  stroller_brand text NOT NULL,
  stroller_model text NOT NULL,
  car_seat_brand text NOT NULL,
  car_seat_model text NOT NULL
) ON COMMIT DROP;

INSERT INTO _btv_audit_pairs (stroller_brand, stroller_model, car_seat_brand, car_seat_model)
VALUES
  ('BOB', 'Alterrain Pro', 'Britax', 'Cypress S'),
  ('BOB', 'Alterrain Pro', 'Britax', 'Willow S'),
  ('BOB', 'Alterrain Pro', 'Nuna', 'PIPA Aire'),
  ('BOB', 'Alterrain Pro', 'Nuna', 'PIPA Aire rx'),
  ('BOB', 'Alterrain Pro', 'Nuna', 'PIPA RX'),
  ('BOB', 'Alterrain Pro', 'Nuna', 'PIPA urbn'),
  ('BOB', 'Alterrain Pro', 'UPPAbaby', 'Aria'),
  ('BOB', 'Alterrain Pro', 'UPPAbaby', 'Aria V2'),
  ('BOB', 'Alterrain Pro', 'UPPAbaby', 'Mesa V3'),
  ('BOB', 'Rambler', 'Britax', 'Cypress S'),
  ('BOB', 'Rambler', 'Britax', 'Willow S'),
  ('BOB', 'Rambler', 'Nuna', 'PIPA Aire rx'),
  ('BOB', 'Rambler', 'Nuna', 'PIPA RX'),
  ('BOB', 'Rambler', 'Nuna', 'PIPA urbn'),
  ('BOB', 'Renegade Wagon', 'Britax', 'Cypress S'),
  ('BOB', 'Renegade Wagon', 'Britax', 'Willow S'),
  ('BOB', 'Renegade Wagon', 'Nuna', 'PIPA Aire rx'),
  ('BOB', 'Renegade Wagon', 'Nuna', 'PIPA RX'),
  ('BOB', 'Renegade Wagon', 'Nuna', 'PIPA urbn'),
  ('BOB', 'Revolution Flex 3.0', 'Britax', 'Cypress S'),
  ('BOB', 'Revolution Flex 3.0', 'Britax', 'Willow S'),
  ('BOB', 'Revolution Flex 3.0', 'Britax', 'Willow SC'),
  ('BOB', 'Revolution Flex 3.0', 'Chicco', 'KeyFit 30'),
  ('BOB', 'Revolution Flex 3.0', 'Chicco', 'KeyFit 30 ClearTex'),
  ('BOB', 'Revolution Flex 3.0', 'Chicco', 'KeyFit Max ClearTex'),
  ('BOB', 'Revolution Flex 3.0', 'Chicco', 'KeyFit Max Zip ClearLux'),
  ('BOB', 'Revolution Flex 3.0', 'Chicco', 'KeyFit Max Zip ClearTex'),
  ('BOB', 'Revolution Flex 3.0', 'Clek', 'Liing'),
  ('BOB', 'Revolution Flex 3.0', 'Clek', 'Liingo'),
  ('BOB', 'Revolution Flex 3.0', 'Cybex', 'Aton G2'),
  ('BOB', 'Revolution Flex 3.0', 'Cybex', 'Aton G2 Swivel'),
  ('BOB', 'Revolution Flex 3.0', 'Cybex', 'Cloud G Pro Comfort Extend'),
  ('BOB', 'Revolution Flex 3.0', 'Cybex', 'Cloud T'),
  ('BOB', 'Revolution Flex 3.0', 'Graco', 'GoMax'),
  ('BOB', 'Revolution Flex 3.0', 'Graco', 'SnugRide Lite LX'),
  ('BOB', 'Revolution Flex 3.0', 'Graco', 'SnugRide SnugFit'),
  ('BOB', 'Revolution Flex 3.0', 'Graco', 'SnugRide SnugFit DLX'),
  ('BOB', 'Revolution Flex 3.0', 'Graco', 'SnugRide SnugFit LX'),
  ('BOB', 'Revolution Flex 3.0', 'Maxi-Cosi', 'Ambra'),
  ('BOB', 'Revolution Flex 3.0', 'Maxi-Cosi', 'Mico Luxe'),
  ('BOB', 'Revolution Flex 3.0', 'Maxi-Cosi', 'Mico Pro'),
  ('BOB', 'Revolution Flex 3.0', 'Maxi-Cosi', 'Peri 180'),
  ('BOB', 'Revolution Flex 3.0', 'Nuna', 'PIPA Aire'),
  ('BOB', 'Revolution Flex 3.0', 'Nuna', 'PIPA Aire rx'),
  ('BOB', 'Revolution Flex 3.0', 'Nuna', 'PIPA RX'),
  ('BOB', 'Revolution Flex 3.0', 'Nuna', 'PIPA urbn'),
  ('BOB', 'Revolution Flex 3.0', 'Peg Perego', 'Primo Viaggio 4-35'),
  ('BOB', 'Revolution Flex 3.0', 'Peg Perego', 'Primo Viaggio Lounge'),
  ('BOB', 'Revolution Flex 3.0', 'Peg Perego', 'Primo Viaggio Nido'),
  ('BOB', 'Revolution Flex 3.0', 'UPPAbaby', 'Aria V2'),
  ('BOB', 'Revolution Flex 3.0', 'UPPAbaby', 'Mesa V3'),
  ('BOB', 'Revolution Flex 3.0 Duallie', 'Britax', 'Cypress S'),
  ('BOB', 'Revolution Flex 3.0 Duallie', 'Britax', 'Willow S'),
  ('BOB', 'Revolution Flex 3.0 Duallie', 'Britax', 'Willow SC'),
  ('BOB', 'Revolution Flex 3.0 Duallie', 'Chicco', 'KeyFit 30'),
  ('BOB', 'Revolution Flex 3.0 Duallie', 'Chicco', 'KeyFit 30 ClearTex'),
  ('BOB', 'Revolution Flex 3.0 Duallie', 'Chicco', 'KeyFit Max ClearTex'),
  ('BOB', 'Revolution Flex 3.0 Duallie', 'Chicco', 'KeyFit Max Zip ClearLux'),
  ('BOB', 'Revolution Flex 3.0 Duallie', 'Chicco', 'KeyFit Max Zip ClearTex'),
  ('BOB', 'Revolution Flex 3.0 Duallie', 'Graco', 'GoMax'),
  ('BOB', 'Revolution Flex 3.0 Duallie', 'Graco', 'SnugRide Lite LX'),
  ('BOB', 'Revolution Flex 3.0 Duallie', 'Graco', 'SnugRide SnugFit'),
  ('BOB', 'Revolution Flex 3.0 Duallie', 'Graco', 'SnugRide SnugFit DLX'),
  ('BOB', 'Revolution Flex 3.0 Duallie', 'Graco', 'SnugRide SnugFit LX'),
  ('BOB', 'Revolution Flex 3.0 Duallie', 'Nuna', 'PIPA Aire'),
  ('BOB', 'Revolution Flex 3.0 Duallie', 'Nuna', 'PIPA Aire rx'),
  ('BOB', 'Revolution Flex 3.0 Duallie', 'Nuna', 'PIPA RX'),
  ('BOB', 'Revolution Flex 3.0 Duallie', 'Nuna', 'PIPA urbn'),
  ('BOB', 'Revolution Flex 3.0 Duallie', 'UPPAbaby', 'Aria V2'),
  ('BOB', 'Revolution Flex 3.0 Duallie', 'UPPAbaby', 'Mesa V3'),
  ('BOB', 'Wayfinder', 'Britax', 'Cypress S'),
  ('BOB', 'Wayfinder', 'Britax', 'Willow S'),
  ('BOB', 'Wayfinder', 'Britax', 'Willow SC'),
  ('BOB', 'Wayfinder', 'Clek', 'Liing'),
  ('BOB', 'Wayfinder', 'Clek', 'Liingo'),
  ('BOB', 'Wayfinder', 'Cybex', 'Aton G2'),
  ('BOB', 'Wayfinder', 'Cybex', 'Aton G2 Swivel'),
  ('BOB', 'Wayfinder', 'Cybex', 'Cloud G Pro Comfort Extend'),
  ('BOB', 'Wayfinder', 'Cybex', 'Cloud T'),
  ('BOB', 'Wayfinder', 'Maxi-Cosi', 'Ambra'),
  ('BOB', 'Wayfinder', 'Maxi-Cosi', 'Mico Luxe'),
  ('BOB', 'Wayfinder', 'Maxi-Cosi', 'Mico Pro'),
  ('BOB', 'Wayfinder', 'Maxi-Cosi', 'Peri 180'),
  ('BOB', 'Wayfinder', 'Nuna', 'PIPA Aire'),
  ('BOB', 'Wayfinder', 'Nuna', 'PIPA Aire rx'),
  ('BOB', 'Wayfinder', 'Nuna', 'PIPA RX'),
  ('BOB', 'Wayfinder', 'Nuna', 'PIPA urbn'),
  ('Thule', 'Glide 2', 'Maxi-Cosi', 'Mico Luxe'),
  ('Thule', 'Glide 2', 'Maxi-Cosi', 'Mico Pro'),
  ('Thule', 'Glide 2', 'Maxi-Cosi', 'Peri 180'),
  ('Thule', 'Glide 2', 'Nuna', 'PIPA Aire'),
  ('Thule', 'Glide 2', 'Nuna', 'PIPA Aire rx'),
  ('Thule', 'Glide 2', 'Nuna', 'PIPA RX'),
  ('Thule', 'Glide 2', 'Nuna', 'PIPA urbn'),
  ('Thule', 'Glide 2', 'UPPAbaby', 'Aria V2'),
  ('Thule', 'Glide 2', 'UPPAbaby', 'Mesa V3'),
  ('Thule', 'Shine', 'Chicco', 'KeyFit 30'),
  ('Thule', 'Shine', 'Chicco', 'KeyFit 30 ClearTex'),
  ('Thule', 'Shine', 'Chicco', 'KeyFit Max ClearTex'),
  ('Thule', 'Shine', 'Chicco', 'KeyFit Max Zip ClearLux'),
  ('Thule', 'Shine', 'Chicco', 'KeyFit Max Zip ClearTex'),
  ('Thule', 'Shine', 'Clek', 'Liing'),
  ('Thule', 'Shine', 'Clek', 'Liingo'),
  ('Thule', 'Shine', 'Cybex', 'Aton G2'),
  ('Thule', 'Shine', 'Cybex', 'Aton G2 Swivel'),
  ('Thule', 'Shine', 'Cybex', 'Cloud G Pro Comfort Extend'),
  ('Thule', 'Shine', 'Cybex', 'Cloud T'),
  ('Thule', 'Shine', 'Maxi-Cosi', 'Ambra'),
  ('Thule', 'Shine', 'Maxi-Cosi', 'Mico Luxe'),
  ('Thule', 'Shine', 'Maxi-Cosi', 'Mico Pro'),
  ('Thule', 'Shine', 'Maxi-Cosi', 'Mico XP'),
  ('Thule', 'Shine', 'Maxi-Cosi', 'Peri 180'),
  ('Thule', 'Shine', 'Nuna', 'PIPA Aire'),
  ('Thule', 'Shine', 'Nuna', 'PIPA Aire rx'),
  ('Thule', 'Shine', 'Nuna', 'PIPA RX'),
  ('Thule', 'Shine', 'Nuna', 'PIPA urbn'),
  ('Thule', 'Sleek', 'Maxi-Cosi', 'Ambra'),
  ('Thule', 'Sleek', 'Maxi-Cosi', 'Mico Luxe'),
  ('Thule', 'Sleek', 'Maxi-Cosi', 'Mico Pro'),
  ('Thule', 'Sleek', 'Maxi-Cosi', 'Peri 180'),
  ('Thule', 'Sleek', 'Nuna', 'PIPA Aire'),
  ('Thule', 'Sleek', 'Nuna', 'PIPA Aire rx'),
  ('Thule', 'Sleek', 'Nuna', 'PIPA RX'),
  ('Thule', 'Sleek', 'Nuna', 'PIPA urbn'),
  ('Thule', 'Sleek', 'UPPAbaby', 'Aria'),
  ('Thule', 'Sleek', 'UPPAbaby', 'Aria V2'),
  ('Thule', 'Sleek', 'UPPAbaby', 'Mesa V3'),
  ('Thule', 'Spring 2', 'Chicco', 'KeyFit 30'),
  ('Thule', 'Spring 2', 'Chicco', 'KeyFit 30 ClearTex'),
  ('Thule', 'Spring 2', 'Chicco', 'KeyFit Max ClearTex'),
  ('Thule', 'Spring 2', 'Chicco', 'KeyFit Max Zip ClearLux'),
  ('Thule', 'Spring 2', 'Chicco', 'KeyFit Max Zip ClearTex'),
  ('Thule', 'Spring 2', 'Clek', 'Liing'),
  ('Thule', 'Spring 2', 'Clek', 'Liingo'),
  ('Thule', 'Spring 2', 'Cybex', 'Aton G2'),
  ('Thule', 'Spring 2', 'Cybex', 'Aton G2 Swivel'),
  ('Thule', 'Spring 2', 'Cybex', 'Cloud G Pro Comfort Extend'),
  ('Thule', 'Spring 2', 'Cybex', 'Cloud T'),
  ('Thule', 'Spring 2', 'Maxi-Cosi', 'Ambra'),
  ('Thule', 'Spring 2', 'Maxi-Cosi', 'Mico Luxe'),
  ('Thule', 'Spring 2', 'Maxi-Cosi', 'Mico Pro'),
  ('Thule', 'Spring 2', 'Maxi-Cosi', 'Mico XP'),
  ('Thule', 'Spring 2', 'Maxi-Cosi', 'Peri 180'),
  ('Thule', 'Spring 2', 'Nuna', 'PIPA Aire'),
  ('Thule', 'Spring 2', 'Nuna', 'PIPA Aire rx'),
  ('Thule', 'Spring 2', 'Nuna', 'PIPA RX'),
  ('Thule', 'Spring 2', 'Nuna', 'PIPA urbn'),
  ('Thule', 'Urban Glide 2', 'Maxi-Cosi', 'Mico Luxe'),
  ('Thule', 'Urban Glide 2', 'Maxi-Cosi', 'Mico Pro'),
  ('Thule', 'Urban Glide 2', 'Maxi-Cosi', 'Peri 180'),
  ('Thule', 'Urban Glide 2', 'Nuna', 'PIPA Aire'),
  ('Thule', 'Urban Glide 2', 'Nuna', 'PIPA Aire rx'),
  ('Thule', 'Urban Glide 2', 'Nuna', 'PIPA RX'),
  ('Thule', 'Urban Glide 2', 'Nuna', 'PIPA urbn'),
  ('Thule', 'Urban Glide 2', 'UPPAbaby', 'Aria'),
  ('Thule', 'Urban Glide 2', 'UPPAbaby', 'Aria V2'),
  ('Thule', 'Urban Glide 2', 'UPPAbaby', 'Mesa V3'),
  ('Thule', 'Urban Glide 2 Double', 'Maxi-Cosi', 'Mico Luxe'),
  ('Thule', 'Urban Glide 2 Double', 'Maxi-Cosi', 'Mico Pro'),
  ('Thule', 'Urban Glide 2 Double', 'Maxi-Cosi', 'Peri 180'),
  ('Thule', 'Urban Glide 2 Double', 'Nuna', 'PIPA Aire'),
  ('Thule', 'Urban Glide 2 Double', 'Nuna', 'PIPA Aire rx'),
  ('Thule', 'Urban Glide 2 Double', 'Nuna', 'PIPA RX'),
  ('Thule', 'Urban Glide 2 Double', 'Nuna', 'PIPA urbn'),
  ('Thule', 'Urban Glide 2 Double', 'UPPAbaby', 'Aria'),
  ('Thule', 'Urban Glide 2 Double', 'UPPAbaby', 'Aria V2'),
  ('Thule', 'Urban Glide 2 Double', 'UPPAbaby', 'Mesa V3'),
  ('Thule', 'Urban Glide 3', 'Clek', 'Liing'),
  ('Thule', 'Urban Glide 3', 'Clek', 'Liingo'),
  ('Thule', 'Urban Glide 3', 'Cybex', 'Aton G2'),
  ('Thule', 'Urban Glide 3', 'Cybex', 'Aton G2 Swivel'),
  ('Thule', 'Urban Glide 3', 'Cybex', 'Cloud G Pro Comfort Extend'),
  ('Thule', 'Urban Glide 3', 'Cybex', 'Cloud T'),
  ('Thule', 'Urban Glide 3', 'Maxi-Cosi', 'Ambra'),
  ('Thule', 'Urban Glide 3', 'Maxi-Cosi', 'Mico Luxe'),
  ('Thule', 'Urban Glide 3', 'Maxi-Cosi', 'Mico Pro'),
  ('Thule', 'Urban Glide 3', 'Maxi-Cosi', 'Mico XP'),
  ('Thule', 'Urban Glide 3', 'Maxi-Cosi', 'Peri 180'),
  ('Thule', 'Urban Glide 3', 'Nuna', 'PIPA Aire'),
  ('Thule', 'Urban Glide 3', 'Nuna', 'PIPA Aire rx'),
  ('Thule', 'Urban Glide 3', 'Nuna', 'PIPA RX'),
  ('Thule', 'Urban Glide 3', 'Nuna', 'PIPA urbn'),
  ('Thule', 'Urban Glide 3 Double', 'Clek', 'Liing'),
  ('Thule', 'Urban Glide 3 Double', 'Clek', 'Liingo'),
  ('Thule', 'Urban Glide 3 Double', 'Cybex', 'Aton G2'),
  ('Thule', 'Urban Glide 3 Double', 'Cybex', 'Aton G2 Swivel'),
  ('Thule', 'Urban Glide 3 Double', 'Cybex', 'Cloud G Pro Comfort Extend'),
  ('Thule', 'Urban Glide 3 Double', 'Cybex', 'Cloud T'),
  ('Thule', 'Urban Glide 3 Double', 'Maxi-Cosi', 'Ambra'),
  ('Thule', 'Urban Glide 3 Double', 'Maxi-Cosi', 'Mico Luxe'),
  ('Thule', 'Urban Glide 3 Double', 'Maxi-Cosi', 'Mico Pro'),
  ('Thule', 'Urban Glide 3 Double', 'Maxi-Cosi', 'Mico XP'),
  ('Thule', 'Urban Glide 3 Double', 'Maxi-Cosi', 'Peri 180'),
  ('Thule', 'Urban Glide 3 Double', 'Nuna', 'PIPA Aire'),
  ('Thule', 'Urban Glide 3 Double', 'Nuna', 'PIPA Aire rx'),
  ('Thule', 'Urban Glide 3 Double', 'Nuna', 'PIPA RX'),
  ('Thule', 'Urban Glide 3 Double', 'Nuna', 'PIPA urbn'),
  ('Thule', 'Urban Glide 4-wheel', 'Chicco', 'KeyFit 30'),
  ('Thule', 'Urban Glide 4-wheel', 'Chicco', 'KeyFit 30 ClearTex'),
  ('Thule', 'Urban Glide 4-wheel', 'Chicco', 'KeyFit Max ClearTex'),
  ('Thule', 'Urban Glide 4-wheel', 'Chicco', 'KeyFit Max Zip ClearLux'),
  ('Thule', 'Urban Glide 4-wheel', 'Chicco', 'KeyFit Max Zip ClearTex'),
  ('Thule', 'Urban Glide 4-wheel', 'Clek', 'Liing'),
  ('Thule', 'Urban Glide 4-wheel', 'Clek', 'Liingo'),
  ('Thule', 'Urban Glide 4-wheel', 'Cybex', 'Aton G2'),
  ('Thule', 'Urban Glide 4-wheel', 'Cybex', 'Aton G2 Swivel'),
  ('Thule', 'Urban Glide 4-wheel', 'Cybex', 'Cloud G Pro Comfort Extend'),
  ('Thule', 'Urban Glide 4-wheel', 'Cybex', 'Cloud T'),
  ('Thule', 'Urban Glide 4-wheel', 'Maxi-Cosi', 'Ambra'),
  ('Thule', 'Urban Glide 4-wheel', 'Maxi-Cosi', 'Mico Luxe'),
  ('Thule', 'Urban Glide 4-wheel', 'Maxi-Cosi', 'Mico Pro'),
  ('Thule', 'Urban Glide 4-wheel', 'Maxi-Cosi', 'Mico XP'),
  ('Thule', 'Urban Glide 4-wheel', 'Maxi-Cosi', 'Peri 180'),
  ('Thule', 'Urban Glide 4-wheel', 'Nuna', 'PIPA Aire'),
  ('Thule', 'Urban Glide 4-wheel', 'Nuna', 'PIPA Aire rx'),
  ('Thule', 'Urban Glide 4-wheel', 'Nuna', 'PIPA RX'),
  ('Thule', 'Urban Glide 4-wheel', 'Nuna', 'PIPA urbn'),
  ('Thule', 'Urban Glide 4-Wheel Single Child', 'Nuna', 'PIPA Aire'),
  ('Thule', 'Urban Glide 4-Wheel Single Child', 'Nuna', 'PIPA Aire rx'),
  ('Thule', 'Urban Glide 4-Wheel Single Child', 'Nuna', 'PIPA RX'),
  ('Thule', 'Urban Glide 4-Wheel Single Child', 'Nuna', 'PIPA urbn'),
  ('Veer', 'All-Terrain Cruiser', 'Britax', 'Cypress S'),
  ('Veer', 'All-Terrain Cruiser', 'Britax', 'Willow S'),
  ('Veer', 'All-Terrain Cruiser', 'Britax', 'Willow SC'),
  ('Veer', 'All-Terrain Cruiser', 'Cybex', 'Aton G2'),
  ('Veer', 'All-Terrain Cruiser', 'Cybex', 'Aton G2 Swivel'),
  ('Veer', 'All-Terrain Cruiser', 'Cybex', 'Cloud G Pro Comfort Extend'),
  ('Veer', 'All-Terrain Cruiser', 'Cybex', 'Cloud T'),
  ('Veer', 'All-Terrain Cruiser', 'Maxi-Cosi', 'Ambra'),
  ('Veer', 'All-Terrain Cruiser', 'Maxi-Cosi', 'Mico Luxe'),
  ('Veer', 'All-Terrain Cruiser', 'Maxi-Cosi', 'Mico Pro'),
  ('Veer', 'All-Terrain Cruiser', 'Maxi-Cosi', 'Peri 180'),
  ('Veer', 'All-Terrain Cruiser', 'Nuna', 'PIPA Aire'),
  ('Veer', 'All-Terrain Cruiser', 'Nuna', 'PIPA Aire rx'),
  ('Veer', 'All-Terrain Cruiser', 'Nuna', 'PIPA RX'),
  ('Veer', 'All-Terrain Cruiser', 'Nuna', 'PIPA urbn'),
  ('Veer', 'All-Terrain Cruiser', 'UPPAbaby', 'Aria'),
  ('Veer', 'All-Terrain Cruiser', 'UPPAbaby', 'Aria V2'),
  ('Veer', 'All-Terrain Cruiser', 'UPPAbaby', 'Mesa V3'),
  ('Veer', 'Cruiser', 'Britax', 'Cypress S'),
  ('Veer', 'Cruiser', 'Britax', 'Willow S'),
  ('Veer', 'Cruiser', 'Britax', 'Willow SC'),
  ('Veer', 'Cruiser', 'Cybex', 'Aton G2'),
  ('Veer', 'Cruiser', 'Cybex', 'Aton G2 Swivel'),
  ('Veer', 'Cruiser', 'Cybex', 'Cloud G Pro Comfort Extend'),
  ('Veer', 'Cruiser', 'Cybex', 'Cloud T'),
  ('Veer', 'Cruiser', 'Maxi-Cosi', 'Ambra'),
  ('Veer', 'Cruiser', 'Maxi-Cosi', 'Mico Luxe'),
  ('Veer', 'Cruiser', 'Maxi-Cosi', 'Mico Pro'),
  ('Veer', 'Cruiser', 'Maxi-Cosi', 'Peri 180'),
  ('Veer', 'Cruiser', 'Nuna', 'PIPA Aire'),
  ('Veer', 'Cruiser', 'Nuna', 'PIPA Aire rx'),
  ('Veer', 'Cruiser', 'Nuna', 'PIPA RX'),
  ('Veer', 'Cruiser', 'Nuna', 'PIPA urbn'),
  ('Veer', 'Cruiser', 'UPPAbaby', 'Aria'),
  ('Veer', 'Cruiser', 'UPPAbaby', 'Aria V2'),
  ('Veer', 'Cruiser', 'UPPAbaby', 'Mesa V3'),
  ('Veer', 'Cruiser City', 'Britax', 'Cypress S'),
  ('Veer', 'Cruiser City', 'Britax', 'Willow S'),
  ('Veer', 'Cruiser City', 'Britax', 'Willow SC'),
  ('Veer', 'Cruiser City', 'Cybex', 'Aton G2'),
  ('Veer', 'Cruiser City', 'Cybex', 'Aton G2 Swivel'),
  ('Veer', 'Cruiser City', 'Cybex', 'Cloud G Pro Comfort Extend'),
  ('Veer', 'Cruiser City', 'Cybex', 'Cloud T'),
  ('Veer', 'Cruiser City', 'Maxi-Cosi', 'Ambra'),
  ('Veer', 'Cruiser City', 'Maxi-Cosi', 'Mico Luxe'),
  ('Veer', 'Cruiser City', 'Maxi-Cosi', 'Mico Pro'),
  ('Veer', 'Cruiser City', 'Maxi-Cosi', 'Peri 180'),
  ('Veer', 'Cruiser City', 'Nuna', 'PIPA Aire'),
  ('Veer', 'Cruiser City', 'Nuna', 'PIPA Aire rx'),
  ('Veer', 'Cruiser City', 'Nuna', 'PIPA RX'),
  ('Veer', 'Cruiser City', 'Nuna', 'PIPA urbn'),
  ('Veer', 'Cruiser City', 'UPPAbaby', 'Aria'),
  ('Veer', 'Cruiser City', 'UPPAbaby', 'Aria V2'),
  ('Veer', 'Cruiser City', 'UPPAbaby', 'Mesa V3'),
  ('Veer', 'Cruiser City XL Essentials', 'Britax', 'Cypress S'),
  ('Veer', 'Cruiser City XL Essentials', 'Britax', 'Willow S'),
  ('Veer', 'Cruiser City XL Essentials', 'Britax', 'Willow SC'),
  ('Veer', 'Cruiser City XL Essentials', 'Cybex', 'Aton G2'),
  ('Veer', 'Cruiser City XL Essentials', 'Cybex', 'Aton G2 Swivel'),
  ('Veer', 'Cruiser City XL Essentials', 'Cybex', 'Cloud G Pro Comfort Extend'),
  ('Veer', 'Cruiser City XL Essentials', 'Cybex', 'Cloud T'),
  ('Veer', 'Cruiser City XL Essentials', 'Maxi-Cosi', 'Ambra'),
  ('Veer', 'Cruiser City XL Essentials', 'Maxi-Cosi', 'Mico Luxe'),
  ('Veer', 'Cruiser City XL Essentials', 'Maxi-Cosi', 'Mico Pro'),
  ('Veer', 'Cruiser City XL Essentials', 'Maxi-Cosi', 'Peri 180'),
  ('Veer', 'Cruiser City XL Essentials', 'Nuna', 'PIPA Aire'),
  ('Veer', 'Cruiser City XL Essentials', 'Nuna', 'PIPA Aire rx'),
  ('Veer', 'Cruiser City XL Essentials', 'Nuna', 'PIPA RX'),
  ('Veer', 'Cruiser City XL Essentials', 'Nuna', 'PIPA urbn'),
  ('Veer', 'Cruiser City XL Essentials', 'UPPAbaby', 'Aria'),
  ('Veer', 'Cruiser City XL Essentials', 'UPPAbaby', 'Aria V2'),
  ('Veer', 'Cruiser City XL Essentials', 'UPPAbaby', 'Mesa V3'),
  ('Veer', 'Cruiser Wagon Comfort Seat for Toddlers', 'Britax', 'Cypress S'),
  ('Veer', 'Cruiser Wagon Comfort Seat for Toddlers', 'Britax', 'Willow S'),
  ('Veer', 'Cruiser Wagon Comfort Seat for Toddlers', 'Britax', 'Willow SC'),
  ('Veer', 'Cruiser Wagon Comfort Seat for Toddlers', 'Cybex', 'Aton G2'),
  ('Veer', 'Cruiser Wagon Comfort Seat for Toddlers', 'Cybex', 'Aton G2 Swivel'),
  ('Veer', 'Cruiser Wagon Comfort Seat for Toddlers', 'Cybex', 'Cloud G Pro Comfort Extend'),
  ('Veer', 'Cruiser Wagon Comfort Seat for Toddlers', 'Cybex', 'Cloud T'),
  ('Veer', 'Cruiser Wagon Comfort Seat for Toddlers', 'Maxi-Cosi', 'Ambra'),
  ('Veer', 'Cruiser Wagon Comfort Seat for Toddlers', 'Maxi-Cosi', 'Mico Luxe'),
  ('Veer', 'Cruiser Wagon Comfort Seat for Toddlers', 'Maxi-Cosi', 'Mico Pro'),
  ('Veer', 'Cruiser Wagon Comfort Seat for Toddlers', 'Maxi-Cosi', 'Peri 180'),
  ('Veer', 'Cruiser Wagon Comfort Seat for Toddlers', 'Nuna', 'PIPA Aire'),
  ('Veer', 'Cruiser Wagon Comfort Seat for Toddlers', 'Nuna', 'PIPA Aire rx'),
  ('Veer', 'Cruiser Wagon Comfort Seat for Toddlers', 'Nuna', 'PIPA RX'),
  ('Veer', 'Cruiser Wagon Comfort Seat for Toddlers', 'Nuna', 'PIPA urbn'),
  ('Veer', 'Cruiser Wagon Comfort Seat for Toddlers', 'UPPAbaby', 'Aria'),
  ('Veer', 'Cruiser Wagon Comfort Seat for Toddlers', 'UPPAbaby', 'Aria V2'),
  ('Veer', 'Cruiser Wagon Comfort Seat for Toddlers', 'UPPAbaby', 'Mesa V3'),
  ('Veer', 'Cruiser Wagon XL Comfort Seat for Toddlers', 'Britax', 'Cypress S'),
  ('Veer', 'Cruiser Wagon XL Comfort Seat for Toddlers', 'Britax', 'Willow S'),
  ('Veer', 'Cruiser Wagon XL Comfort Seat for Toddlers', 'Britax', 'Willow SC'),
  ('Veer', 'Cruiser Wagon XL Comfort Seat for Toddlers', 'Cybex', 'Aton G2'),
  ('Veer', 'Cruiser Wagon XL Comfort Seat for Toddlers', 'Cybex', 'Aton G2 Swivel'),
  ('Veer', 'Cruiser Wagon XL Comfort Seat for Toddlers', 'Cybex', 'Cloud G Pro Comfort Extend'),
  ('Veer', 'Cruiser Wagon XL Comfort Seat for Toddlers', 'Cybex', 'Cloud T'),
  ('Veer', 'Cruiser Wagon XL Comfort Seat for Toddlers', 'Maxi-Cosi', 'Ambra'),
  ('Veer', 'Cruiser Wagon XL Comfort Seat for Toddlers', 'Maxi-Cosi', 'Mico Luxe'),
  ('Veer', 'Cruiser Wagon XL Comfort Seat for Toddlers', 'Maxi-Cosi', 'Mico Pro'),
  ('Veer', 'Cruiser Wagon XL Comfort Seat for Toddlers', 'Maxi-Cosi', 'Peri 180'),
  ('Veer', 'Cruiser Wagon XL Comfort Seat for Toddlers', 'Nuna', 'PIPA Aire'),
  ('Veer', 'Cruiser Wagon XL Comfort Seat for Toddlers', 'Nuna', 'PIPA Aire rx'),
  ('Veer', 'Cruiser Wagon XL Comfort Seat for Toddlers', 'Nuna', 'PIPA RX'),
  ('Veer', 'Cruiser Wagon XL Comfort Seat for Toddlers', 'Nuna', 'PIPA urbn'),
  ('Veer', 'Cruiser Wagon XL Comfort Seat for Toddlers', 'UPPAbaby', 'Aria'),
  ('Veer', 'Cruiser Wagon XL Comfort Seat for Toddlers', 'UPPAbaby', 'Aria V2'),
  ('Veer', 'Cruiser Wagon XL Comfort Seat for Toddlers', 'UPPAbaby', 'Mesa V3'),
  ('Veer', 'Cruiser XL Nap System', 'Britax', 'Cypress S'),
  ('Veer', 'Cruiser XL Nap System', 'Britax', 'Willow S'),
  ('Veer', 'Cruiser XL Nap System', 'Britax', 'Willow SC'),
  ('Veer', 'Cruiser XL Nap System', 'Cybex', 'Aton G2'),
  ('Veer', 'Cruiser XL Nap System', 'Cybex', 'Aton G2 Swivel'),
  ('Veer', 'Cruiser XL Nap System', 'Cybex', 'Cloud G Pro Comfort Extend'),
  ('Veer', 'Cruiser XL Nap System', 'Cybex', 'Cloud T'),
  ('Veer', 'Cruiser XL Nap System', 'Maxi-Cosi', 'Ambra'),
  ('Veer', 'Cruiser XL Nap System', 'Maxi-Cosi', 'Mico Luxe'),
  ('Veer', 'Cruiser XL Nap System', 'Maxi-Cosi', 'Mico Pro'),
  ('Veer', 'Cruiser XL Nap System', 'Maxi-Cosi', 'Peri 180'),
  ('Veer', 'Cruiser XL Nap System', 'Nuna', 'PIPA Aire'),
  ('Veer', 'Cruiser XL Nap System', 'Nuna', 'PIPA Aire rx'),
  ('Veer', 'Cruiser XL Nap System', 'Nuna', 'PIPA RX'),
  ('Veer', 'Cruiser XL Nap System', 'Nuna', 'PIPA urbn'),
  ('Veer', 'Cruiser XL Nap System', 'UPPAbaby', 'Aria'),
  ('Veer', 'Cruiser XL Nap System', 'UPPAbaby', 'Aria V2'),
  ('Veer', 'Cruiser XL Nap System', 'UPPAbaby', 'Mesa V3'),
  ('Veer', 'Switch&Jog', 'Britax', 'Cypress S'),
  ('Veer', 'Switch&Jog', 'Britax', 'Willow S'),
  ('Veer', 'Switch&Jog', 'Britax', 'Willow SC'),
  ('Veer', 'Switch&Jog', 'Graco', 'GoMax'),
  ('Veer', 'Switch&Jog', 'Graco', 'SnugRide Lite LX'),
  ('Veer', 'Switch&Jog', 'Graco', 'SnugRide SnugFit'),
  ('Veer', 'Switch&Jog', 'Graco', 'SnugRide SnugFit DLX'),
  ('Veer', 'Switch&Jog', 'Graco', 'SnugRide SnugFit LX'),
  ('Veer', 'Switch&Jog', 'Nuna', 'PIPA Aire'),
  ('Veer', 'Switch&Jog', 'Nuna', 'PIPA Aire rx'),
  ('Veer', 'Switch&Jog', 'Nuna', 'PIPA RX'),
  ('Veer', 'Switch&Jog', 'Nuna', 'PIPA urbn'),
  ('Veer', 'Switch&Jog', 'UPPAbaby', 'Aria'),
  ('Veer', 'Switch&Jog', 'UPPAbaby', 'Aria V2'),
  ('Veer', 'Switch&Jog', 'UPPAbaby', 'Mesa V3'),
  ('Veer', 'Switch&Jog Jogging', 'Britax', 'Cypress S'),
  ('Veer', 'Switch&Jog Jogging', 'Britax', 'Willow S'),
  ('Veer', 'Switch&Jog Jogging', 'Britax', 'Willow SC'),
  ('Veer', 'Switch&Jog Jogging', 'Graco', 'GoMax'),
  ('Veer', 'Switch&Jog Jogging', 'Graco', 'SnugRide Lite LX'),
  ('Veer', 'Switch&Jog Jogging', 'Graco', 'SnugRide SnugFit'),
  ('Veer', 'Switch&Jog Jogging', 'Graco', 'SnugRide SnugFit DLX'),
  ('Veer', 'Switch&Jog Jogging', 'Graco', 'SnugRide SnugFit LX'),
  ('Veer', 'Switch&Jog Jogging', 'Nuna', 'PIPA Aire'),
  ('Veer', 'Switch&Jog Jogging', 'Nuna', 'PIPA Aire rx'),
  ('Veer', 'Switch&Jog Jogging', 'Nuna', 'PIPA RX'),
  ('Veer', 'Switch&Jog Jogging', 'Nuna', 'PIPA urbn'),
  ('Veer', 'Switch&Jog Jogging', 'UPPAbaby', 'Aria'),
  ('Veer', 'Switch&Jog Jogging', 'UPPAbaby', 'Aria V2'),
  ('Veer', 'Switch&Jog Jogging', 'UPPAbaby', 'Mesa V3'),
  ('Veer', 'Switch&Roll', 'Britax', 'Cypress S'),
  ('Veer', 'Switch&Roll', 'Britax', 'Willow S'),
  ('Veer', 'Switch&Roll', 'Britax', 'Willow SC'),
  ('Veer', 'Switch&Roll', 'Graco', 'GoMax'),
  ('Veer', 'Switch&Roll', 'Graco', 'SnugRide Lite LX'),
  ('Veer', 'Switch&Roll', 'Graco', 'SnugRide SnugFit'),
  ('Veer', 'Switch&Roll', 'Graco', 'SnugRide SnugFit DLX'),
  ('Veer', 'Switch&Roll', 'Graco', 'SnugRide SnugFit LX'),
  ('Veer', 'Switch&Roll', 'Nuna', 'PIPA Aire'),
  ('Veer', 'Switch&Roll', 'Nuna', 'PIPA Aire rx'),
  ('Veer', 'Switch&Roll', 'Nuna', 'PIPA RX'),
  ('Veer', 'Switch&Roll', 'Nuna', 'PIPA urbn'),
  ('Veer', 'Switch&Roll', 'UPPAbaby', 'Aria'),
  ('Veer', 'Switch&Roll', 'UPPAbaby', 'Aria V2'),
  ('Veer', 'Switch&Roll', 'UPPAbaby', 'Mesa V3');

DELETE FROM "Compatibility" AS compat
USING _btv_audit_pairs AS audit
INNER JOIN "Stroller" AS stroller
  ON LOWER(stroller."brand") = LOWER(audit.stroller_brand)
 AND LOWER(stroller."model") = LOWER(audit.stroller_model)
INNER JOIN "CarSeat" AS seat
  ON LOWER(seat."brand") = LOWER(audit.car_seat_brand)
 AND LOWER(seat."model") = LOWER(audit.car_seat_model)
WHERE compat."strollerId" = stroller."id"
  AND compat."carSeatId" = seat."id";

CREATE TEMP TABLE _btv_visible_pairs (
  compatibility_id text NOT NULL,
  stroller_brand text NOT NULL,
  stroller_model text NOT NULL,
  car_seat_brand text NOT NULL,
  car_seat_model text NOT NULL,
  compatibility_type text NOT NULL,
  adapter_required boolean NOT NULL,
  adapter_type text,
  adapter_sku text,
  adapter_url text,
  notes text NOT NULL,
  confidence text NOT NULL
) ON COMMIT DROP;

INSERT INTO _btv_visible_pairs (
  compatibility_id, stroller_brand, stroller_model, car_seat_brand, car_seat_model,
  compatibility_type, adapter_required, adapter_type, adapter_sku, adapter_url, notes, confidence
)
VALUES
  ('bob-alterrain-pro__britax-cypress-s', 'BOB', 'Alterrain Pro', 'Britax', 'Cypress S', 'ADAPTER', true, 'BOB Single Britax ClickTight adapter', 'S943900', 'https://www.bobgear.com/accessories/single-jogging-stroller-adapter-for-select-britax-infant-car-seats', '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: BOB Single Britax ClickTight adapter (S943900). Source: BOB Single Britax ClickTight adapter.', 'HIGH'),
  ('bob-alterrain-pro__britax-willow-s', 'BOB', 'Alterrain Pro', 'Britax', 'Willow S', 'ADAPTER', true, 'BOB Single Britax ClickTight adapter', 'S943900', 'https://www.bobgear.com/accessories/single-jogging-stroller-adapter-for-select-britax-infant-car-seats', '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: BOB Single Britax ClickTight adapter (S943900). Source: BOB Single Britax ClickTight adapter.', 'HIGH'),
  ('bob-rambler__britax-cypress-s', 'BOB', 'Rambler', 'Britax', 'Cypress S', 'ADAPTER', true, 'BOB Single Britax ClickTight adapter', 'S943900', 'https://www.bobgear.com/accessories/single-jogging-stroller-adapter-for-select-britax-infant-car-seats', '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: BOB Single Britax ClickTight adapter (S943900). Source: BOB Single Britax ClickTight adapter.', 'HIGH'),
  ('bob-rambler__britax-willow-s', 'BOB', 'Rambler', 'Britax', 'Willow S', 'ADAPTER', true, 'BOB Single Britax ClickTight adapter', 'S943900', 'https://www.bobgear.com/accessories/single-jogging-stroller-adapter-for-select-britax-infant-car-seats', '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: BOB Single Britax ClickTight adapter (S943900). Source: BOB Single Britax ClickTight adapter.', 'HIGH'),
  ('bob-renegade-wagon__britax-cypress-s', 'BOB', 'Renegade Wagon', 'Britax', 'Cypress S', 'ADAPTER', true, 'BOB Renegade Wagon adapter', 'S14685500', 'https://www.bobgear.com/accessories/renegade-wagon-infant-car-seat-adapter', '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: BOB Renegade Wagon adapter (S14685500). Source: BOB Renegade Wagon adapter.', 'HIGH'),
  ('bob-renegade-wagon__britax-willow-s', 'BOB', 'Renegade Wagon', 'Britax', 'Willow S', 'ADAPTER', true, 'BOB Renegade Wagon adapter', 'S14685500', 'https://www.bobgear.com/accessories/renegade-wagon-infant-car-seat-adapter', '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: BOB Renegade Wagon adapter (S14685500). Source: BOB Renegade Wagon adapter.', 'HIGH'),
  ('bob-revolution-flex-3__britax-cypress-s', 'BOB', 'Revolution Flex 3.0', 'Britax', 'Cypress S', 'ADAPTER', true, 'BOB Single Britax ClickTight adapter', 'S943900', 'https://www.bobgear.com/accessories/single-jogging-stroller-adapter-for-select-britax-infant-car-seats', '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: BOB Single Britax ClickTight adapter (S943900). Source: BOB Single Britax ClickTight adapter.', 'HIGH'),
  ('bob-revolution-flex-3__britax-willow-s', 'BOB', 'Revolution Flex 3.0', 'Britax', 'Willow S', 'ADAPTER', true, 'BOB Single Britax ClickTight adapter', 'S943900', 'https://www.bobgear.com/accessories/single-jogging-stroller-adapter-for-select-britax-infant-car-seats', '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: BOB Single Britax ClickTight adapter (S943900). Source: BOB Single Britax ClickTight adapter.', 'HIGH'),
  ('cmrmw9w020009nxw1hrsqsjbs', 'BOB', 'Revolution Flex 3.0', 'Britax', 'Willow SC', 'ADAPTER', true, 'BOB Single Britax ClickTight adapter', 'S943900', 'https://www.bobgear.com/accessories/single-jogging-stroller-adapter-for-select-britax-infant-car-seats', '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: BOB Single Britax ClickTight adapter (S943900). Source: BOB Single Britax ClickTight adapter.', 'HIGH'),
  ('cmrjw737p001ey3w4o56l9mo7', 'BOB', 'Revolution Flex 3.0', 'Chicco', 'KeyFit 30', 'ADAPTER', true, 'BOB Single Chicco adapter', 'S12045900', 'https://www.bobgear.com/accessories/single-jogging-stroller-adapter-chicco-infant-car-seats', '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: BOB Single Chicco adapter (S12045900). Source: BOB Single Chicco adapter.', 'HIGH'),
  ('cmrjw738d001my3w4gk4yq3fm', 'BOB', 'Revolution Flex 3.0', 'Chicco', 'KeyFit 30 ClearTex', 'ADAPTER', true, 'BOB Single Chicco adapter', 'S12045900', 'https://www.bobgear.com/accessories/single-jogging-stroller-adapter-chicco-infant-car-seats', '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: BOB Single Chicco adapter (S12045900). Source: BOB Single Chicco adapter.', 'HIGH'),
  ('cmrjw8y8n0020y3w4ovzygjfm', 'BOB', 'Revolution Flex 3.0', 'Graco', 'SnugRide Lite LX', 'ADAPTER', true, 'BOB Single Graco adapter (All SnugRide)', 'S12045400', 'https://www.bobgear.com/accessories/single-jogging-stroller-adapter-graco-infant-car-seats', '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: BOB Single Graco adapter (All SnugRide) (S12045400). Source: BOB Single Graco adapter (All SnugRide).', 'HIGH'),
  ('cmrjw8y8n001yy3w438af6kdl', 'BOB', 'Revolution Flex 3.0', 'Graco', 'SnugRide SnugFit', 'ADAPTER', true, 'BOB Single Graco adapter (All SnugRide)', 'S12045400', 'https://www.bobgear.com/accessories/single-jogging-stroller-adapter-graco-infant-car-seats', '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: BOB Single Graco adapter (All SnugRide) (S12045400). Source: BOB Single Graco adapter (All SnugRide).', 'HIGH'),
  ('cmrjw8y8n001wy3w4uy8zqcus', 'BOB', 'Revolution Flex 3.0', 'Graco', 'SnugRide SnugFit DLX', 'ADAPTER', true, 'BOB Single Graco adapter (All SnugRide)', 'S12045400', 'https://www.bobgear.com/accessories/single-jogging-stroller-adapter-graco-infant-car-seats', '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: BOB Single Graco adapter (All SnugRide) (S12045400). Source: BOB Single Graco adapter (All SnugRide).', 'HIGH'),
  ('cmrjw8y8m001sy3w4jid1lrpy', 'BOB', 'Revolution Flex 3.0', 'Graco', 'SnugRide SnugFit LX', 'ADAPTER', true, 'BOB Single Graco adapter (All SnugRide)', 'S12045400', 'https://www.bobgear.com/accessories/single-jogging-stroller-adapter-graco-infant-car-seats', '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: BOB Single Graco adapter (All SnugRide) (S12045400). Source: BOB Single Graco adapter (All SnugRide).', 'HIGH'),
  ('cmrjwafcp0022y3w4vhh51q2w', 'BOB', 'Revolution Flex 3.0', 'Peg Perego', 'Primo Viaggio 4-35', 'ADAPTER', true, 'BOB Single Peg Perego adapter', 'S12045500', 'https://www.bobgear.com/accessories/single-jogging-stroller-adapter-peg-perego-infant-car-seats', '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: BOB Single Peg Perego adapter (S12045500). Source: BOB Single Peg Perego adapter.', 'HIGH'),
  ('cmrjwafcq0024y3w4v9f7s7ne', 'BOB', 'Revolution Flex 3.0', 'Peg Perego', 'Primo Viaggio Nido', 'ADAPTER', true, 'BOB Single Peg Perego adapter', 'S12045500', 'https://www.bobgear.com/accessories/single-jogging-stroller-adapter-peg-perego-infant-car-seats', '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: BOB Single Peg Perego adapter (S12045500). Source: BOB Single Peg Perego adapter.', 'HIGH'),
  ('cmrkx1ctx002u3k520a5or64n', 'BOB', 'Revolution Flex 3.0 Duallie', 'Chicco', 'KeyFit 30', 'ADAPTER', true, 'BOB Duallie Chicco adapter', 'S02984700', 'https://www.bobgear.com/accessories/chicco-duallie-infant-car-seats-adapter', '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: BOB Duallie Chicco adapter (S02984700). Source: BOB Duallie Chicco adapter.', 'HIGH'),
  ('cmrkx1ctx002q3k52iwz7jgul', 'BOB', 'Revolution Flex 3.0 Duallie', 'Chicco', 'KeyFit 30 ClearTex', 'ADAPTER', true, 'BOB Duallie Chicco adapter', 'S02984700', 'https://www.bobgear.com/accessories/chicco-duallie-infant-car-seats-adapter', '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: BOB Duallie Chicco adapter (S02984700). Source: BOB Duallie Chicco adapter.', 'HIGH'),
  ('cmrkwz1mk00283k52isz2mylw', 'BOB', 'Revolution Flex 3.0 Duallie', 'Graco', 'SnugRide Lite LX', 'ADAPTER', true, 'BOB Duallie Graco adapter (All SnugRide)', 'S02984500', 'https://www.bobgear.com/accessories/graco-duallie-infant-car-seats-adapter', '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: BOB Duallie Graco adapter (All SnugRide) (S02984500). Source: BOB Duallie Graco adapter (All SnugRide).', 'HIGH'),
  ('cmrkwz1ml002b3k52clxryp5p', 'BOB', 'Revolution Flex 3.0 Duallie', 'Graco', 'SnugRide SnugFit', 'ADAPTER', true, 'BOB Duallie Graco adapter (All SnugRide)', 'S02984500', 'https://www.bobgear.com/accessories/graco-duallie-infant-car-seats-adapter', '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: BOB Duallie Graco adapter (All SnugRide) (S02984500). Source: BOB Duallie Graco adapter (All SnugRide).', 'HIGH'),
  ('cmrkwz1ml002e3k524cqzkhh8', 'BOB', 'Revolution Flex 3.0 Duallie', 'Graco', 'SnugRide SnugFit DLX', 'ADAPTER', true, 'BOB Duallie Graco adapter (All SnugRide)', 'S02984500', 'https://www.bobgear.com/accessories/graco-duallie-infant-car-seats-adapter', '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: BOB Duallie Graco adapter (All SnugRide) (S02984500). Source: BOB Duallie Graco adapter (All SnugRide).', 'HIGH'),
  ('cmrkwz1ml002d3k52j60wsbdm', 'BOB', 'Revolution Flex 3.0 Duallie', 'Graco', 'SnugRide SnugFit LX', 'ADAPTER', true, 'BOB Duallie Graco adapter (All SnugRide)', 'S02984500', 'https://www.bobgear.com/accessories/graco-duallie-infant-car-seats-adapter', '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: BOB Duallie Graco adapter (All SnugRide) (S02984500). Source: BOB Duallie Graco adapter (All SnugRide).', 'HIGH'),
  ('bob-wayfinder__britax-cypress-s', 'BOB', 'Wayfinder', 'Britax', 'Cypress S', 'ADAPTER', true, 'BOB Wayfinder adapter (Nuna/Cybex/Maxi-Cosi/Britax)', 'S14664700', 'https://www.bobgear.com/accessories/wayfinder-universal-infant-car-seat-adapter', '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: BOB Wayfinder adapter (Nuna/Cybex/Maxi-Cosi/Britax) (S14664700). Source: BOB Wayfinder adapter (Nuna/Cybex/Maxi-Cosi/Britax).', 'HIGH'),
  ('bob-wayfinder__britax-willow-s', 'BOB', 'Wayfinder', 'Britax', 'Willow S', 'ADAPTER', true, 'BOB Wayfinder adapter (Nuna/Cybex/Maxi-Cosi/Britax)', 'S14664700', 'https://www.bobgear.com/accessories/wayfinder-universal-infant-car-seat-adapter', '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: BOB Wayfinder adapter (Nuna/Cybex/Maxi-Cosi/Britax) (S14664700). Source: BOB Wayfinder adapter (Nuna/Cybex/Maxi-Cosi/Britax).', 'HIGH'),
  ('cmqx6t1se000314fc5yv3sc3u', 'BOB', 'Wayfinder', 'Britax', 'Willow SC', 'ADAPTER', true, 'BOB Wayfinder adapter (Nuna/Cybex/Maxi-Cosi/Britax)', 'S14664700', 'https://www.bobgear.com/accessories/wayfinder-universal-infant-car-seat-adapter', '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: BOB Wayfinder adapter (Nuna/Cybex/Maxi-Cosi/Britax) (S14664700). Source: BOB Wayfinder adapter (Nuna/Cybex/Maxi-Cosi/Britax).', 'HIGH'),
  ('cms94su7e008gi76bl1f4iw1t', 'Thule', 'Shine', 'Chicco', 'KeyFit 30', 'ADAPTER', true, 'Thule Shine car seat adapter - Chicco', '11400503', 'https://www.thule.com/en-us/strollers/strollers-accessories/thule-shine-car-seat-adapter-chicco-_-11400503', '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule Shine car seat adapter - Chicco (11400503). Source: Thule Shine car seat adapter - Chicco.', 'HIGH'),
  ('cms94su7e008ii76brttdh9az', 'Thule', 'Shine', 'Chicco', 'KeyFit 30 ClearTex', 'ADAPTER', true, 'Thule Shine car seat adapter - Chicco', '11400503', 'https://www.thule.com/en-us/strollers/strollers-accessories/thule-shine-car-seat-adapter-chicco-_-11400503', '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule Shine car seat adapter - Chicco (11400503). Source: Thule Shine car seat adapter - Chicco.', 'HIGH'),
  ('cms94r0w80085i76blh6as5oo', 'Thule', 'Shine', 'Clek', 'Liing', 'ADAPTER', true, 'Thule Shine car seat adapter - Maxi-Cosi', '11400502', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule Shine car seat adapter - Maxi-Cosi (11400502). Source: Thule Shine car seat adapter - Maxi-Cosi.', 'HIGH'),
  ('cms94r0w70081i76byiyu4of5', 'Thule', 'Shine', 'Clek', 'Liingo', 'ADAPTER', true, 'Thule Shine car seat adapter - Maxi-Cosi', '11400502', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule Shine car seat adapter - Maxi-Cosi (11400502). Source: Thule Shine car seat adapter - Maxi-Cosi.', 'HIGH'),
  ('cmr1eu3el0009ab5gae25ss1h', 'Thule', 'Shine', 'Nuna', 'PIPA Aire', 'LIMITED', false, 'Thule Shine car seat adapter - Maxi-Cosi', '11400502', NULL, '[BTV_FROZEN_V1] Should work, but this exact pair is not named on the stroller maker''s current fit chart. Basis: manufacturer-documented seat platform anchored to Nuna PIPA RX. Verify the adapter before buying.', 'LOW'),
  ('cmr1eu3ka000bab5gq51keve8', 'Thule', 'Shine', 'Nuna', 'PIPA Aire rx', 'LIMITED', false, 'Thule Shine car seat adapter - Maxi-Cosi', '11400502', NULL, '[BTV_FROZEN_V1] Should work, but this exact pair is not named on the stroller maker''s current fit chart. Basis: manufacturer-documented seat platform anchored to Nuna PIPA RX. Verify the adapter before buying.', 'LOW'),
  ('cmr1eu3py000dab5guf7fmm9d', 'Thule', 'Shine', 'Nuna', 'PIPA RX', 'ADAPTER', true, 'Thule Shine car seat adapter - Maxi-Cosi', '11400502', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule Shine car seat adapter - Maxi-Cosi (11400502). Source: Thule Shine car seat adapter - Maxi-Cosi.', 'HIGH'),
  ('cmr1eu3vj000fab5gfnv7cuwv', 'Thule', 'Shine', 'Nuna', 'PIPA urbn', 'LIMITED', false, 'Thule Shine car seat adapter - Maxi-Cosi', '11400502', NULL, '[BTV_FROZEN_V1] Should work, but this exact pair is not named on the stroller maker''s current fit chart. Basis: manufacturer-documented seat platform anchored to Nuna PIPA RX. Verify the adapter before buying.', 'LOW'),
  ('cms9521j6009pi76bi1y5b7cv', 'Thule', 'Spring 2', 'Chicco', 'KeyFit 30', 'ADAPTER', true, 'Thule Spring car seat adapter - Chicco', '11300411', 'https://www.thule.com/en-us/strollers/strollers-accessories/thule-spring-car-seat-adapter-chicco-_-11300411', '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule Spring car seat adapter - Chicco (11300411). Source: Thule Spring car seat adapter - Chicco.', 'HIGH'),
  ('cms9521j6009ri76b01klzb9h', 'Thule', 'Spring 2', 'Chicco', 'KeyFit 30 ClearTex', 'ADAPTER', true, 'Thule Spring car seat adapter - Chicco', '11300411', 'https://www.thule.com/en-us/strollers/strollers-accessories/thule-spring-car-seat-adapter-chicco-_-11300411', '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule Spring car seat adapter - Chicco (11300411). Source: Thule Spring car seat adapter - Chicco.', 'HIGH'),
  ('cmr0r9piu0001rvv04yn52arl', 'Thule', 'Spring 2', 'Nuna', 'PIPA Aire', 'LIMITED', false, 'Thule Spring car seat adapter - Maxi-Cosi', '11300410', NULL, '[BTV_FROZEN_V1] Should work, but this exact pair is not named on the stroller maker''s current fit chart. Basis: manufacturer-documented seat platform anchored to Nuna PIPA RX. Verify the adapter before buying.', 'LOW'),
  ('cmr0r9ppo0003rvv0zmn6u2es', 'Thule', 'Spring 2', 'Nuna', 'PIPA Aire rx', 'LIMITED', false, 'Thule Spring car seat adapter - Maxi-Cosi', '11300410', NULL, '[BTV_FROZEN_V1] Should work, but this exact pair is not named on the stroller maker''s current fit chart. Basis: manufacturer-documented seat platform anchored to Nuna PIPA RX. Verify the adapter before buying.', 'LOW'),
  ('cmr0r9pu60005rvv0mup0ybb5', 'Thule', 'Spring 2', 'Nuna', 'PIPA RX', 'ADAPTER', true, 'Thule Spring car seat adapter - Maxi-Cosi', '11300410', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule Spring car seat adapter - Maxi-Cosi (11300410). Source: Thule Spring car seat adapter - Maxi-Cosi.', 'HIGH'),
  ('cmr0r9q1j0007rvv0h8a5flc5', 'Thule', 'Spring 2', 'Nuna', 'PIPA urbn', 'LIMITED', false, 'Thule Spring car seat adapter - Maxi-Cosi', '11300410', NULL, '[BTV_FROZEN_V1] Should work, but this exact pair is not named on the stroller maker''s current fit chart. Basis: manufacturer-documented seat platform anchored to Nuna PIPA RX. Verify the adapter before buying.', 'LOW'),
  ('cms99ygfi00a7i76byiszado7', 'Thule', 'Urban Glide 3', 'Clek', 'Liing', 'ADAPTER', true, 'Thule UG3 car seat adapter - Universal/Chicco', '20110762', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule UG3 car seat adapter - Universal/Chicco (20110762). Source: Thule UG3 car seat adapter - Universal/Chicco.', 'HIGH'),
  ('cms99ygfi00a9i76b5xe52n11', 'Thule', 'Urban Glide 3', 'Clek', 'Liingo', 'ADAPTER', true, 'Thule UG3 car seat adapter - Universal/Chicco', '20110762', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule UG3 car seat adapter - Universal/Chicco (20110762). Source: Thule UG3 car seat adapter - Universal/Chicco.', 'HIGH'),
  ('cms99ygg000adi76bp72bksyv', 'Thule', 'Urban Glide 3', 'Cybex', 'Cloud G Pro Comfort Extend', 'ADAPTER', true, 'Thule UG3 car seat adapter - Maxi-Cosi', '20110761', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule UG3 car seat adapter - Maxi-Cosi (20110761). Source: Thule UG3 car seat adapter - Maxi-Cosi.', 'HIGH'),
  ('cms99ygfj00abi76bkj8k933j', 'Thule', 'Urban Glide 3', 'Cybex', 'Cloud T', 'ADAPTER', true, 'Thule UG3 car seat adapter - Maxi-Cosi', '20110761', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule UG3 car seat adapter - Maxi-Cosi (20110761). Source: Thule UG3 car seat adapter - Maxi-Cosi.', 'HIGH'),
  ('cmqx8i41l002lbcx534ad5uuc', 'Thule', 'Urban Glide 3', 'Maxi-Cosi', 'Mico Luxe', 'ADAPTER', true, 'Thule UG3 car seat adapter - Maxi-Cosi', '20110761', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule UG3 car seat adapter - Maxi-Cosi (20110761). Source: Thule UG3 car seat adapter - Maxi-Cosi.', 'HIGH'),
  ('cms99z69h00aji76b171gsx82', 'Thule', 'Urban Glide 3', 'Maxi-Cosi', 'Mico XP', 'LIMITED', false, 'Thule UG3 car seat adapter - Maxi-Cosi', '20110761', NULL, '[BTV_FROZEN_V1] Should work, but this exact pair is not named on the stroller maker''s current fit chart. Basis: documented shared stroller-attachment platform anchored to Maxi-Cosi Mico Luxe. Verify the adapter before buying.', 'LOW'),
  ('cmqx8i48u002rbcx5zjaxiqgn', 'Thule', 'Urban Glide 3', 'Maxi-Cosi', 'Peri 180', 'ADAPTER', true, 'Thule UG3 car seat adapter - Maxi-Cosi', '20110761', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule UG3 car seat adapter - Maxi-Cosi (20110761). Source: Thule UG3 car seat adapter - Maxi-Cosi.', 'HIGH'),
  ('cmr0r9qxl000hrvv0z0cpw1zm', 'Thule', 'Urban Glide 3', 'Nuna', 'PIPA Aire', 'ADAPTER', true, 'Thule UG3 car seat adapter - Maxi-Cosi', '20110761', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule UG3 car seat adapter - Maxi-Cosi (20110761). Source: Thule UG3 car seat adapter - Maxi-Cosi.', 'HIGH'),
  ('cmr0r9r22000jrvv0062a4dgh', 'Thule', 'Urban Glide 3', 'Nuna', 'PIPA Aire rx', 'ADAPTER', true, 'Thule UG3 car seat adapter - Maxi-Cosi', '20110761', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule UG3 car seat adapter - Maxi-Cosi (20110761). Source: Thule UG3 car seat adapter - Maxi-Cosi.', 'HIGH'),
  ('cmr0r9r6h000lrvv0omtgeula', 'Thule', 'Urban Glide 3', 'Nuna', 'PIPA RX', 'ADAPTER', true, 'Thule UG3 car seat adapter - Maxi-Cosi', '20110761', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule UG3 car seat adapter - Maxi-Cosi (20110761). Source: Thule UG3 car seat adapter - Maxi-Cosi.', 'HIGH'),
  ('cmr0r9rb5000nrvv0mumjgooy', 'Thule', 'Urban Glide 3', 'Nuna', 'PIPA urbn', 'LIMITED', false, 'Thule UG3 car seat adapter - Maxi-Cosi', '20110761', NULL, '[BTV_FROZEN_V1] Should work, but this exact pair is not named on the stroller maker''s current fit chart. Basis: manufacturer-documented seat platform anchored to Nuna PIPA Aire. Verify the adapter before buying.', 'LOW'),
  ('cms94m2fz006oi76b5xjulny5', 'Thule', 'Urban Glide 3 Double', 'Clek', 'Liing', 'ADAPTER', true, 'Thule UG3 car seat adapter double - Universal', '20110764', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule UG3 car seat adapter double - Universal (20110764). Source: Thule UG3 car seat adapter double - Universal.', 'HIGH'),
  ('cms94m2fv006mi76bzd71bomd', 'Thule', 'Urban Glide 3 Double', 'Clek', 'Liingo', 'ADAPTER', true, 'Thule UG3 car seat adapter double - Universal', '20110764', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule UG3 car seat adapter double - Universal (20110764). Source: Thule UG3 car seat adapter double - Universal.', 'HIGH'),
  ('cms94m2g0006ri76bkv5bmw8d', 'Thule', 'Urban Glide 3 Double', 'Cybex', 'Cloud G Pro Comfort Extend', 'ADAPTER', true, 'Thule UG3 car seat adapter double - Maxi-Cosi', '20110763', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule UG3 car seat adapter double - Maxi-Cosi (20110763). Source: Thule UG3 car seat adapter double - Maxi-Cosi.', 'HIGH'),
  ('cms94m2gr006wi76bq2eyyj7r', 'Thule', 'Urban Glide 3 Double', 'Cybex', 'Cloud T', 'ADAPTER', true, 'Thule UG3 car seat adapter double - Maxi-Cosi', '20110763', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule UG3 car seat adapter double - Maxi-Cosi (20110763). Source: Thule UG3 car seat adapter double - Maxi-Cosi.', 'HIGH'),
  ('cmqx8i360001xbcx52ba7sa06', 'Thule', 'Urban Glide 3 Double', 'Maxi-Cosi', 'Mico Luxe', 'ADAPTER', true, 'Thule UG3 car seat adapter double - Maxi-Cosi', '20110763', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule UG3 car seat adapter double - Maxi-Cosi (20110763). Source: Thule UG3 car seat adapter double - Maxi-Cosi.', 'HIGH'),
  ('cms94nskg0076i76bfyoihqfh', 'Thule', 'Urban Glide 3 Double', 'Maxi-Cosi', 'Mico XP', 'LIMITED', false, 'Thule UG3 car seat adapter double - Maxi-Cosi', '20110763', NULL, '[BTV_FROZEN_V1] Should work, but this exact pair is not named on the stroller maker''s current fit chart. Basis: documented shared stroller-attachment platform anchored to Maxi-Cosi Mico Luxe. Verify the adapter before buying.', 'LOW'),
  ('cmqx8i3dl0023bcx5b5wpi1zw', 'Thule', 'Urban Glide 3 Double', 'Maxi-Cosi', 'Peri 180', 'ADAPTER', true, 'Thule UG3 car seat adapter double - Maxi-Cosi', '20110763', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule UG3 car seat adapter double - Maxi-Cosi (20110763). Source: Thule UG3 car seat adapter double - Maxi-Cosi.', 'HIGH'),
  ('cmr0r9rfv000prvv0nmwhyqan', 'Thule', 'Urban Glide 3 Double', 'Nuna', 'PIPA Aire', 'ADAPTER', true, 'Thule UG3 car seat adapter double - Maxi-Cosi', '20110763', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule UG3 car seat adapter double - Maxi-Cosi (20110763). Source: Thule UG3 car seat adapter double - Maxi-Cosi.', 'HIGH'),
  ('cmr0r9rki000rrvv0pc4ob41h', 'Thule', 'Urban Glide 3 Double', 'Nuna', 'PIPA Aire rx', 'ADAPTER', true, 'Thule UG3 car seat adapter double - Maxi-Cosi', '20110763', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule UG3 car seat adapter double - Maxi-Cosi (20110763). Source: Thule UG3 car seat adapter double - Maxi-Cosi.', 'HIGH'),
  ('cmr0r9rq2000trvv0gtcnm4e8', 'Thule', 'Urban Glide 3 Double', 'Nuna', 'PIPA RX', 'ADAPTER', true, 'Thule UG3 car seat adapter double - Maxi-Cosi', '20110763', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule UG3 car seat adapter double - Maxi-Cosi (20110763). Source: Thule UG3 car seat adapter double - Maxi-Cosi.', 'HIGH'),
  ('cmr0r9ruu000vrvv0r5j8ef1l', 'Thule', 'Urban Glide 3 Double', 'Nuna', 'PIPA urbn', 'LIMITED', false, 'Thule UG3 car seat adapter double - Maxi-Cosi', '20110763', NULL, '[BTV_FROZEN_V1] Should work, but this exact pair is not named on the stroller maker''s current fit chart. Basis: manufacturer-documented seat platform anchored to Nuna PIPA Aire. Verify the adapter before buying.', 'LOW'),
  ('cms94i2qc005xi76bpri7sv0k', 'Thule', 'Urban Glide 4-wheel', 'Chicco', 'KeyFit 30', 'ADAPTER', true, 'Thule UG3 car seat adapter - Universal/Chicco', '20110762', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule UG3 car seat adapter - Universal/Chicco (20110762). Source: Thule UG3 car seat adapter - Universal/Chicco.', 'HIGH'),
  ('cms94i2qa005ri76bfeiavwyq', 'Thule', 'Urban Glide 4-wheel', 'Chicco', 'KeyFit 30 ClearTex', 'ADAPTER', true, 'Thule UG3 car seat adapter - Universal/Chicco', '20110762', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule UG3 car seat adapter - Universal/Chicco (20110762). Source: Thule UG3 car seat adapter - Universal/Chicco.', 'HIGH'),
  ('cms6o9nn6000x13vzmrgyveys', 'Thule', 'Urban Glide 4-wheel', 'Clek', 'Liing', 'ADAPTER', true, 'Thule UG3 car seat adapter - Universal/Chicco', '20110762', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule UG3 car seat adapter - Universal/Chicco (20110762). Source: Thule UG3 car seat adapter - Universal/Chicco.', 'HIGH'),
  ('cms6o9nn6000u13vz2pharzt6', 'Thule', 'Urban Glide 4-wheel', 'Clek', 'Liingo', 'ADAPTER', true, 'Thule UG3 car seat adapter - Universal/Chicco', '20110762', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule UG3 car seat adapter - Universal/Chicco (20110762). Source: Thule UG3 car seat adapter - Universal/Chicco.', 'HIGH'),
  ('cms6o9nnk001213vzxnnuy9a2', 'Thule', 'Urban Glide 4-wheel', 'Cybex', 'Cloud G Pro Comfort Extend', 'ADAPTER', true, 'Thule UG3 car seat adapter - Maxi-Cosi', '20110761', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule UG3 car seat adapter - Maxi-Cosi (20110761). Source: Thule UG3 car seat adapter - Maxi-Cosi.', 'HIGH'),
  ('cms6o9nnn001513vz0nduyqyn', 'Thule', 'Urban Glide 4-wheel', 'Cybex', 'Cloud T', 'ADAPTER', true, 'Thule UG3 car seat adapter - Maxi-Cosi', '20110761', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule UG3 car seat adapter - Maxi-Cosi (20110761). Source: Thule UG3 car seat adapter - Maxi-Cosi.', 'HIGH'),
  ('cms6oaqoe001f13vz1tieocaw', 'Thule', 'Urban Glide 4-wheel', 'Maxi-Cosi', 'Mico Luxe', 'ADAPTER', true, 'Thule UG3 car seat adapter - Maxi-Cosi', '20110761', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule UG3 car seat adapter - Maxi-Cosi (20110761). Source: Thule UG3 car seat adapter - Maxi-Cosi.', 'HIGH'),
  ('cms6oaqoe001h13vzrrtqau33', 'Thule', 'Urban Glide 4-wheel', 'Maxi-Cosi', 'Mico XP', 'LIMITED', false, 'Thule UG3 car seat adapter - Maxi-Cosi', '20110761', NULL, '[BTV_FROZEN_V1] Should work, but this exact pair is not named on the stroller maker''s current fit chart. Basis: documented shared stroller-attachment platform anchored to Maxi-Cosi Mico Luxe. Verify the adapter before buying.', 'LOW'),
  ('cms6oaqoj001l13vzk6zxpyfs', 'Thule', 'Urban Glide 4-wheel', 'Maxi-Cosi', 'Peri 180', 'ADAPTER', true, 'Thule UG3 car seat adapter - Maxi-Cosi', '20110761', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule UG3 car seat adapter - Maxi-Cosi (20110761). Source: Thule UG3 car seat adapter - Maxi-Cosi.', 'HIGH'),
  ('cmr0r9rze000xrvv0dah4pos7', 'Thule', 'Urban Glide 4-wheel', 'Nuna', 'PIPA Aire', 'ADAPTER', true, 'Thule UG3 car seat adapter - Maxi-Cosi', '20110761', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule UG3 car seat adapter - Maxi-Cosi (20110761). Source: Thule UG3 car seat adapter - Maxi-Cosi.', 'HIGH'),
  ('cmr0r9s3u000zrvv0fbr4z3j5', 'Thule', 'Urban Glide 4-wheel', 'Nuna', 'PIPA Aire rx', 'ADAPTER', true, 'Thule UG3 car seat adapter - Maxi-Cosi', '20110761', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule UG3 car seat adapter - Maxi-Cosi (20110761). Source: Thule UG3 car seat adapter - Maxi-Cosi.', 'HIGH'),
  ('cmr0r9s8g0011rvv0igxf1qpj', 'Thule', 'Urban Glide 4-wheel', 'Nuna', 'PIPA RX', 'ADAPTER', true, 'Thule UG3 car seat adapter - Maxi-Cosi', '20110761', NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Thule UG3 car seat adapter - Maxi-Cosi (20110761). Source: Thule UG3 car seat adapter - Maxi-Cosi.', 'HIGH'),
  ('cmr0r9sd40013rvv020p8fk1w', 'Thule', 'Urban Glide 4-wheel', 'Nuna', 'PIPA urbn', 'LIMITED', false, 'Thule UG3 car seat adapter - Maxi-Cosi', '20110761', NULL, '[BTV_FROZEN_V1] Should work, but this exact pair is not named on the stroller maker''s current fit chart. Basis: manufacturer-documented seat platform anchored to Nuna PIPA Aire. Verify the adapter before buying.', 'LOW'),
  ('cmqt253vl002bfvq84s3zyv9s', 'Veer', 'All-Terrain Cruiser', 'Nuna', 'PIPA Aire', 'LIMITED', true, 'Veer Cruiser ICS Adapter - Cybex/Maxi-Cosi/Nuna/Clek', NULL, NULL, '[BTV_FROZEN_V1] Should work, but this exact pair is not named on the stroller maker''s current fit chart. Basis: manufacturer-documented seat platform anchored to Nuna PIPA Aire rx. Verify the adapter before buying.', 'LOW'),
  ('cmqt253xv002dfvq8p8tfw123', 'Veer', 'All-Terrain Cruiser', 'Nuna', 'PIPA Aire rx', 'ADAPTER', true, 'Veer Cruiser ICS Adapter - Cybex/Maxi-Cosi/Nuna/Clek', NULL, NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Veer Cruiser ICS Adapter - Cybex/Maxi-Cosi/Nuna/Clek. Source: Veer Cruiser ICS Adapter - Cybex/Maxi-Cosi/Nuna/Clek - first-party Veer compatibility manual.', 'HIGH'),
  ('cmqt253tb0029fvq84fnoj9z2', 'Veer', 'All-Terrain Cruiser', 'Nuna', 'PIPA RX', 'ADAPTER', true, 'Veer Cruiser ICS Adapter - Cybex/Maxi-Cosi/Nuna/Clek', NULL, NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Veer Cruiser ICS Adapter - Cybex/Maxi-Cosi/Nuna/Clek. Source: Veer Cruiser ICS Adapter - Cybex/Maxi-Cosi/Nuna/Clek - first-party Veer compatibility manual.', 'HIGH'),
  ('cmqt25405002ffvq8esap2m9g', 'Veer', 'All-Terrain Cruiser', 'Nuna', 'PIPA urbn', 'LIMITED', true, 'Veer Cruiser ICS Adapter - Cybex/Maxi-Cosi/Nuna/Clek', NULL, NULL, '[BTV_FROZEN_V1] Should work, but this exact pair is not named on the stroller maker''s current fit chart. Basis: manufacturer-documented seat platform anchored to Nuna PIPA Aire rx. Verify the adapter before buying.', 'LOW'),
  ('cmqx8pgsv0003gq0c0o1j8ux2', 'Veer', 'All-Terrain Cruiser', 'UPPAbaby', 'Aria', 'ADAPTER', true, 'Veer Cruiser ICS Adapter - Graco/Britax/UPPAbaby', NULL, NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Veer Cruiser ICS Adapter - Graco/Britax/UPPAbaby. Source: Veer Cruiser ICS Adapter - Graco/Britax/UPPAbaby - first-party Veer compatibility manual.', 'HIGH'),
  ('cmqx8pgv70005gq0ce6yo0z0s', 'Veer', 'All-Terrain Cruiser', 'UPPAbaby', 'Aria V2', 'LIMITED', true, 'Veer Cruiser ICS Adapter - Graco/Britax/UPPAbaby', NULL, NULL, '[BTV_FROZEN_V1] Should work, but this exact pair is not named on the stroller maker''s current fit chart. Basis: documented shared stroller-attachment platform anchored to UPPAbaby Aria. Verify the adapter before buying.', 'LOW'),
  ('cmqx8phup000zgq0cqmqy5ieu', 'Veer', 'Cruiser', 'Nuna', 'PIPA Aire', 'LIMITED', true, 'Veer Cruiser ICS Adapter - Cybex/Maxi-Cosi/Nuna/Clek', NULL, NULL, '[BTV_FROZEN_V1] Should work, but this exact pair is not named on the stroller maker''s current fit chart. Basis: manufacturer-documented seat platform anchored to Nuna PIPA Aire rx. Verify the adapter before buying.', 'LOW'),
  ('cmqx8phq5000vgq0cwcnswk7l', 'Veer', 'Cruiser', 'Nuna', 'PIPA Aire rx', 'ADAPTER', true, 'Veer Cruiser ICS Adapter - Cybex/Maxi-Cosi/Nuna/Clek', NULL, NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Veer Cruiser ICS Adapter - Cybex/Maxi-Cosi/Nuna/Clek. Source: Veer Cruiser ICS Adapter - Cybex/Maxi-Cosi/Nuna/Clek - first-party Veer compatibility manual.', 'HIGH'),
  ('cmqx8ph95000hgq0cb1ny4823', 'Veer', 'Cruiser', 'Nuna', 'PIPA RX', 'ADAPTER', true, 'Veer Cruiser ICS Adapter - Cybex/Maxi-Cosi/Nuna/Clek', NULL, NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Veer Cruiser ICS Adapter - Cybex/Maxi-Cosi/Nuna/Clek. Source: Veer Cruiser ICS Adapter - Cybex/Maxi-Cosi/Nuna/Clek - first-party Veer compatibility manual.', 'HIGH'),
  ('cmqx8phwz0011gq0cw56kywvk', 'Veer', 'Cruiser', 'Nuna', 'PIPA urbn', 'LIMITED', true, 'Veer Cruiser ICS Adapter - Cybex/Maxi-Cosi/Nuna/Clek', NULL, NULL, '[BTV_FROZEN_V1] Should work, but this exact pair is not named on the stroller maker''s current fit chart. Basis: manufacturer-documented seat platform anchored to Nuna PIPA Aire rx. Verify the adapter before buying.', 'LOW'),
  ('cmqx8ph2a000bgq0ccpdtlu9c', 'Veer', 'Cruiser', 'UPPAbaby', 'Aria', 'ADAPTER', true, 'Veer Cruiser ICS Adapter - Graco/Britax/UPPAbaby', NULL, NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Veer Cruiser ICS Adapter - Graco/Britax/UPPAbaby. Source: Veer Cruiser ICS Adapter - Graco/Britax/UPPAbaby - first-party Veer compatibility manual.', 'HIGH'),
  ('cmqx8ph4j000dgq0c0qu3a5sh', 'Veer', 'Cruiser', 'UPPAbaby', 'Aria V2', 'LIMITED', true, 'Veer Cruiser ICS Adapter - Graco/Britax/UPPAbaby', NULL, NULL, '[BTV_FROZEN_V1] Should work, but this exact pair is not named on the stroller maker''s current fit chart. Basis: documented shared stroller-attachment platform anchored to UPPAbaby Aria. Verify the adapter before buying.', 'LOW'),
  ('cmqzsb4ks004d12dx81kxlfd3', 'Veer', 'Cruiser City', 'Nuna', 'PIPA Aire', 'LIMITED', true, 'Veer Cruiser ICS Adapter - Cybex/Maxi-Cosi/Nuna/Clek', NULL, NULL, '[BTV_FROZEN_V1] Should work, but this exact pair is not named on the stroller maker''s current fit chart. Basis: manufacturer-documented seat platform anchored to Nuna PIPA Aire rx. Verify the adapter before buying.', 'LOW'),
  ('cmqzsb4g8004912dxp3m3n8mf', 'Veer', 'Cruiser City', 'Nuna', 'PIPA Aire rx', 'ADAPTER', true, 'Veer Cruiser ICS Adapter - Cybex/Maxi-Cosi/Nuna/Clek', NULL, NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Veer Cruiser ICS Adapter - Cybex/Maxi-Cosi/Nuna/Clek. Source: Veer Cruiser ICS Adapter - Cybex/Maxi-Cosi/Nuna/Clek - first-party Veer compatibility manual.', 'HIGH'),
  ('cmqzsb3zj003v12dxj8puj57j', 'Veer', 'Cruiser City', 'Nuna', 'PIPA RX', 'ADAPTER', true, 'Veer Cruiser ICS Adapter - Cybex/Maxi-Cosi/Nuna/Clek', NULL, NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Veer Cruiser ICS Adapter - Cybex/Maxi-Cosi/Nuna/Clek. Source: Veer Cruiser ICS Adapter - Cybex/Maxi-Cosi/Nuna/Clek - first-party Veer compatibility manual.', 'HIGH'),
  ('cmqzsb4n2004f12dxvkyl81sb', 'Veer', 'Cruiser City', 'Nuna', 'PIPA urbn', 'LIMITED', true, 'Veer Cruiser ICS Adapter - Cybex/Maxi-Cosi/Nuna/Clek', NULL, NULL, '[BTV_FROZEN_V1] Should work, but this exact pair is not named on the stroller maker''s current fit chart. Basis: manufacturer-documented seat platform anchored to Nuna PIPA Aire rx. Verify the adapter before buying.', 'LOW'),
  ('cmqzsb3s3003p12dx12rbtzit', 'Veer', 'Cruiser City', 'UPPAbaby', 'Aria', 'ADAPTER', true, 'Veer Cruiser ICS Adapter - Graco/Britax/UPPAbaby', NULL, NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Veer Cruiser ICS Adapter - Graco/Britax/UPPAbaby. Source: Veer Cruiser ICS Adapter - Graco/Britax/UPPAbaby - first-party Veer compatibility manual.', 'HIGH'),
  ('cmqzsb3ug003r12dxk29lqd57', 'Veer', 'Cruiser City', 'UPPAbaby', 'Aria V2', 'LIMITED', true, 'Veer Cruiser ICS Adapter - Graco/Britax/UPPAbaby', NULL, NULL, '[BTV_FROZEN_V1] Should work, but this exact pair is not named on the stroller maker''s current fit chart. Basis: documented shared stroller-attachment platform anchored to UPPAbaby Aria. Verify the adapter before buying.', 'LOW'),
  ('cmqzsb7by006l12dxcbldrxvm', 'Veer', 'Cruiser City XL Essentials', 'Nuna', 'PIPA Aire', 'LIMITED', true, 'Veer Cruiser ICS Adapter - Cybex/Maxi-Cosi/Nuna/Clek', NULL, NULL, '[BTV_FROZEN_V1] Should work, but this exact pair is not named on the stroller maker''s current fit chart. Basis: manufacturer-documented seat platform anchored to Nuna PIPA Aire rx. Verify the adapter before buying.', 'LOW'),
  ('cmqzsb77c006h12dxi6c1f037', 'Veer', 'Cruiser City XL Essentials', 'Nuna', 'PIPA Aire rx', 'ADAPTER', true, 'Veer Cruiser ICS Adapter - Cybex/Maxi-Cosi/Nuna/Clek', NULL, NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Veer Cruiser ICS Adapter - Cybex/Maxi-Cosi/Nuna/Clek. Source: Veer Cruiser ICS Adapter - Cybex/Maxi-Cosi/Nuna/Clek - first-party Veer compatibility manual.', 'HIGH'),
  ('cmqzsb6r3006312dx7lh55q29', 'Veer', 'Cruiser City XL Essentials', 'Nuna', 'PIPA RX', 'ADAPTER', true, 'Veer Cruiser ICS Adapter - Cybex/Maxi-Cosi/Nuna/Clek', NULL, NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Veer Cruiser ICS Adapter - Cybex/Maxi-Cosi/Nuna/Clek. Source: Veer Cruiser ICS Adapter - Cybex/Maxi-Cosi/Nuna/Clek - first-party Veer compatibility manual.', 'HIGH'),
  ('cmqzsb7ea006n12dxkr47vvcm', 'Veer', 'Cruiser City XL Essentials', 'Nuna', 'PIPA urbn', 'LIMITED', true, 'Veer Cruiser ICS Adapter - Cybex/Maxi-Cosi/Nuna/Clek', NULL, NULL, '[BTV_FROZEN_V1] Should work, but this exact pair is not named on the stroller maker''s current fit chart. Basis: manufacturer-documented seat platform anchored to Nuna PIPA Aire rx. Verify the adapter before buying.', 'LOW'),
  ('cmqzsb6i2005x12dx1l0y5qx8', 'Veer', 'Cruiser City XL Essentials', 'UPPAbaby', 'Aria', 'ADAPTER', true, 'Veer Cruiser ICS Adapter - Graco/Britax/UPPAbaby', NULL, NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Veer Cruiser ICS Adapter - Graco/Britax/UPPAbaby. Source: Veer Cruiser ICS Adapter - Graco/Britax/UPPAbaby - first-party Veer compatibility manual.', 'HIGH'),
  ('cmqzsb6ky005z12dxj0fq6gf0', 'Veer', 'Cruiser City XL Essentials', 'UPPAbaby', 'Aria V2', 'LIMITED', true, 'Veer Cruiser ICS Adapter - Graco/Britax/UPPAbaby', NULL, NULL, '[BTV_FROZEN_V1] Should work, but this exact pair is not named on the stroller maker''s current fit chart. Basis: documented shared stroller-attachment platform anchored to UPPAbaby Aria. Verify the adapter before buying.', 'LOW'),
  ('cmr49vtio001n8smgjyhn67b0', 'Veer', 'Switch&Jog', 'Britax', 'Cypress S', 'ADAPTER', true, 'Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family)', NULL, NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family). Source: Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family) - first-party Veer compatibility manual.', 'HIGH'),
  ('cmr49vtnc001p8smgjc3vdl8r', 'Veer', 'Switch&Jog', 'Britax', 'Willow S', 'ADAPTER', true, 'Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family)', NULL, NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family). Source: Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family) - first-party Veer compatibility manual.', 'HIGH'),
  ('cmr49vtry001r8smg13btww4i', 'Veer', 'Switch&Jog', 'Britax', 'Willow SC', 'ADAPTER', true, 'Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family)', NULL, NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family). Source: Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family) - first-party Veer compatibility manual.', 'HIGH'),
  ('cmr0shgyb00h1h1u894gh0rkg', 'Veer', 'Switch&Jog', 'Nuna', 'PIPA Aire', 'LIMITED', true, 'Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family)', NULL, NULL, '[BTV_FROZEN_V1] Should work, but this exact pair is not named on the stroller maker''s current fit chart. Basis: manufacturer-documented seat platform anchored to Nuna PIPA Aire rx. Verify the adapter before buying.', 'LOW'),
  ('cmr0shh2v00h3h1u84p9dywlr', 'Veer', 'Switch&Jog', 'Nuna', 'PIPA Aire rx', 'ADAPTER', true, 'Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family)', NULL, NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family). Source: Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family) - first-party Veer compatibility manual.', 'HIGH'),
  ('cmr0shh7g00h5h1u8dz0hhgyf', 'Veer', 'Switch&Jog', 'Nuna', 'PIPA RX', 'ADAPTER', true, 'Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family)', NULL, NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family). Source: Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family) - first-party Veer compatibility manual.', 'HIGH'),
  ('cmr0shhby00h7h1u866sbh0h4', 'Veer', 'Switch&Jog', 'Nuna', 'PIPA urbn', 'LIMITED', true, 'Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family)', NULL, NULL, '[BTV_FROZEN_V1] Should work, but this exact pair is not named on the stroller maker''s current fit chart. Basis: manufacturer-documented seat platform anchored to Nuna PIPA Aire rx. Verify the adapter before buying.', 'LOW'),
  ('cmr49vrrr000x8smgjf4me8pf', 'Veer', 'Switch&Jog', 'UPPAbaby', 'Aria', 'ADAPTER', true, 'Veer Switchback ICS Adapter - UPPAbaby', NULL, NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Veer Switchback ICS Adapter - UPPAbaby. Source: Veer Switchback ICS Adapter - UPPAbaby - first-party Veer compatibility manual.', 'HIGH'),
  ('cmr49vrwd000z8smgx5k59wd6', 'Veer', 'Switch&Jog', 'UPPAbaby', 'Aria V2', 'LIMITED', true, 'Veer Switchback ICS Adapter - UPPAbaby', NULL, NULL, '[BTV_FROZEN_V1] Should work, but this exact pair is not named on the stroller maker''s current fit chart. Basis: documented shared stroller-attachment platform anchored to UPPAbaby Aria. Verify the adapter before buying.', 'LOW'),
  ('cmr49vyfw003f8smg7kx0harf', 'Veer', 'Switch&Roll', 'Britax', 'Cypress S', 'ADAPTER', true, 'Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family)', NULL, NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family). Source: Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family) - first-party Veer compatibility manual.', 'HIGH'),
  ('cmr49vykg003h8smg3b20thq1', 'Veer', 'Switch&Roll', 'Britax', 'Willow S', 'ADAPTER', true, 'Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family)', NULL, NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family). Source: Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family) - first-party Veer compatibility manual.', 'HIGH'),
  ('cmr49vyp3003j8smg8hivh76p', 'Veer', 'Switch&Roll', 'Britax', 'Willow SC', 'ADAPTER', true, 'Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family)', NULL, NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family). Source: Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family) - first-party Veer compatibility manual.', 'HIGH'),
  ('cmr0shi0d00hhh1u88xq6jwgh', 'Veer', 'Switch&Roll', 'Nuna', 'PIPA Aire', 'LIMITED', true, 'Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family)', NULL, NULL, '[BTV_FROZEN_V1] Should work, but this exact pair is not named on the stroller maker''s current fit chart. Basis: manufacturer-documented seat platform anchored to Nuna PIPA Aire rx. Verify the adapter before buying.', 'LOW'),
  ('cmr0shi5100hjh1u8wf2io5r6', 'Veer', 'Switch&Roll', 'Nuna', 'PIPA Aire rx', 'ADAPTER', true, 'Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family)', NULL, NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family). Source: Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family) - first-party Veer compatibility manual.', 'HIGH'),
  ('cmr0shi9u00hlh1u8m4w637rp', 'Veer', 'Switch&Roll', 'Nuna', 'PIPA RX', 'ADAPTER', true, 'Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family)', NULL, NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family). Source: Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family) - first-party Veer compatibility manual.', 'HIGH'),
  ('cmr0shiel00hnh1u8391w5z1u', 'Veer', 'Switch&Roll', 'Nuna', 'PIPA urbn', 'LIMITED', true, 'Veer Switchback ICS Adapter - Maxi-Cosi/Nuna/Clek/Cybex (also covers newer Britax Cypress/Willow family)', NULL, NULL, '[BTV_FROZEN_V1] Should work, but this exact pair is not named on the stroller maker''s current fit chart. Basis: manufacturer-documented seat platform anchored to Nuna PIPA Aire rx. Verify the adapter before buying.', 'LOW'),
  ('cmr49vwio002p8smgh0if2xoo', 'Veer', 'Switch&Roll', 'UPPAbaby', 'Aria', 'ADAPTER', true, 'Veer Switchback ICS Adapter - UPPAbaby', NULL, NULL, '[BTV_FROZEN_V1] Manufacturer-listed adapter fit. Adapter: Veer Switchback ICS Adapter - UPPAbaby. Source: Veer Switchback ICS Adapter - UPPAbaby - first-party Veer compatibility manual.', 'HIGH'),
  ('cmr49vwvl002r8smg7pfc6xk0', 'Veer', 'Switch&Roll', 'UPPAbaby', 'Aria V2', 'LIMITED', true, 'Veer Switchback ICS Adapter - UPPAbaby', NULL, NULL, '[BTV_FROZEN_V1] Should work, but this exact pair is not named on the stroller maker''s current fit chart. Basis: documented shared stroller-attachment platform anchored to UPPAbaby Aria. Verify the adapter before buying.', 'LOW');

INSERT INTO "Compatibility" (
  "id",
  "strollerId",
  "carSeatId",
  "compatibilityType",
  "adapterRequired",
  "adapterType",
  "adapterBabylistSku",
  "adapterBabylistUrl",
  "notes",
  "confidence",
  "createdAt",
  "updatedAt"
)
SELECT
  visible.compatibility_id,
  stroller."id",
  seat."id",
  visible.compatibility_type::"CompatibilityType",
  visible.adapter_required,
  visible.adapter_type,
  visible.adapter_sku,
  visible.adapter_url,
  visible.notes,
  visible.confidence::"CompatibilityConfidence",
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
FROM _btv_visible_pairs AS visible
INNER JOIN "Stroller" AS stroller
  ON LOWER(stroller."brand") = LOWER(visible.stroller_brand)
 AND LOWER(stroller."model") = LOWER(visible.stroller_model)
INNER JOIN "CarSeat" AS seat
  ON LOWER(seat."brand") = LOWER(visible.car_seat_brand)
 AND LOWER(seat."model") = LOWER(visible.car_seat_model)
ON CONFLICT ("strollerId", "carSeatId") DO UPDATE
SET
  "compatibilityType" = EXCLUDED."compatibilityType",
  "adapterRequired" = EXCLUDED."adapterRequired",
  "adapterType" = EXCLUDED."adapterType",
  "adapterBabylistSku" = EXCLUDED."adapterBabylistSku",
  "adapterBabylistUrl" = EXCLUDED."adapterBabylistUrl",
  "notes" = EXCLUDED."notes",
  "confidence" = EXCLUDED."confidence",
  "updatedAt" = CURRENT_TIMESTAMP;
